---
permalink: protect-scsql/concept_snapcenter_plug_in_for_microsoft_sql_server_overview.html
sidebar: sidebar
keywords: SnapCenter Plug-in for Microsoft SQL Server
summary: 'The SnapCenter Plug-in for Microsoft SQL Server is a host-side component of the NetApp SnapCenter Software that enables application-aware data protection management of Microsoft SQL Server databases. The Plug-in for SQL Server automates SQL Server database backup, verify, restore, and cloning operations in your SnapCenter environment.'
---
= SnapCenter Plug-in for Microsoft SQL Server overview
:icons: font
:imagesdir: ../media/

[.lead]
The SnapCenter Plug-in for Microsoft SQL Server is a host-side component of the NetApp SnapCenter Software that enables application-aware data protection management of Microsoft SQL Server databases. The Plug-in for SQL Server automates SQL Server database backup, verify, restore, and cloning operations in your SnapCenter environment.

____
*Success story*: We have many Microsoft SQL databases in production with Agile development currently using DB copies that are over a week old and taking 5 to 6 hours to provision. With SnapCenter, cloning takes minutes to provision a Dev environment that is typically one day old.
____

____
_SQL DBA_
____

When the Plug-in for SQL Server is installed, you can use SnapCenter with NetApp SnapMirror technology to create mirror copies of backup sets on another volume and with NetApp SnapVault technology to perform disk-to-disk backup replication for standards compliance or archival purposes.
