---
permalink: protect-scsql/quick_start_to_install_snapcenter_plug-in_for_sql_server.html
sidebar: sidebar
keywords: credentials
summary: Provides instructions for installing the SnapCenter Server and the SnapCenter Plug-in for Microsoft SQL Server.
---
= Quick start to install SnapCenter Plug-in for SQL Server
:icons: font
:imagesdir: ../media/

[.lead]
Provides a condensed set of installation instructions for installing the SnapCenter Server and the SnapCenter Plug-in for Microsoft SQL Server.

== Prepare for installation
=== Domain and workgroup requirements

SnapCenter Server can be installed on systems that are either in a domain or in a workgroup. 

If you are using an Active Directory domain, you should use a Domain user with local administrator rights. The Domain user should be a member of the local Administrator group on the Windows host.

If you are using workgroups, you should use a local account that has local administrator rights.

=== License requirements

The type of licenses you install depends on your environment.

[cols="1,3"]
|===
| License | Where required

a| SnapCenter Standard controller-based
a| Required for FAS, AFF, or All SAN Array (ASA) storage controllers

SnapCenter Standard license is a controller-based license and is included as part of the premium bundle. If you have the SnapManager Suite license, you also get the SnapCenter Standard license entitlement.
If you want to install SnapCenter on a trial basis with FAS, AFF, or ASA storage, you can obtain a Premium Bundle evaluation license by contacting the sales representative.
a| SnapCenter Standard capacity-based
a| Required with ONTAP Select and Cloud Volumes ONTAP

If you are a Cloud Volumes ONTAP or ONTAP Select customer, you need to procure a per TB capacity-based license based on the data managed by SnapCenter.
By default, SnapCenter ships a built-in 90-day 100 TB SnapCenter Standard capacity-based trial license. For other details, contact the sales representative.
a| SnapMirror or SnapVault
a| ONTAP

Either SnapMirror or SnapVault license is required if replication is enabled in SnapCenter.
a| Additional licenses (optional)
a| See link:../install/concept_snapcenter_licenses.html[SnapCenter licenses^].
a| SnapCenter Standard licenses (optional)
a| Secondary destinations

NOTE: It is recommended, but not required, that you add SnapCenter Standard licenses to secondary destinations. If SnapCenter Standard licenses are not enabled on secondary destinations, you cannot use SnapCenter to backup resources on the secondary destination after performing a failover operation. However, a FlexClone license is required on secondary destinations to perform clone and verification operations.

|===

=== Host and port requirements

For ONTAP and application plug-in minimum requirements see https://imt.netapp.com/matrix/imt.jsp?components=105961;&solution=1259&isHWU&src=IMT[Interoperability Matrix Tool^].

[cols="1,3"]
|===
|Hosts |Minimum requirements

a|Operating System (64-bit)
a|See https://imt.netapp.com/matrix/imt.jsp?components=108408;&solution=1259&isHWU&src=IMT[Interoperability Matrix Tool^]

a|CPU
a|
* Server host: 4 cores

* Plug-in host: 1 core
a|RAM
a|
* Server host: 8 GB

* Plug-in host: 1 GB
a|Hard drive space
a|Server host:

* 4 GB for SnapCenter Server software and logs

* 6 GB for SnapCenter repository

* Each plug-in host: 2 GB for plug-in installation and logs, this is required only if plug-in is installed on a dedicated host.
a|Third-party libraries
a|Required on SnapCenter Server host and plug-in host:

* Microsoft .NET Framework 4.7.2 or later

* Windows Management Framework (WMF) 4.0 or later

* PowerShell 4.0 or later
a|Browsers
a|Chrome, Internet Explorer, and Microsoft Edge
|===

[cols="1,3"]
|===
|Port type |Default port

a|SnapCenter port
a|8146 (HTTPS), bidirectional, customizable, as in the URL _\https://server:8146_
a|SnapCenter SMCore communication port
a|8145 (HTTPS), bidirectional, customizable
a|Repository database
a|3306 (HTTPS), bidirectional
a|Windows plug-in hosts
a|135, 445 (TCP)

In addition to ports 135 and 445, the dynamic port range specified by Microsoft should also be open. Remote install operations use the Windows Management Instrumentation (WMI) service, which dynamically searches this port range.

For information on the dynamic port range supported, see https://docs.microsoft.com/en-US/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements[Service overview and network port requirements for Windows^].
a|SnapCenter Plug-in for Windows
a|8145 (HTTPS), bidirectional, customizable
a|ONTAP cluster or SVM communication port
a|443 (HTTPS), bidirectional;
80 (HTTP), bidirectional

The port is used for communication between the SnapCenter Server host, plug-in host, and SVM or ONTAP Cluster.
|===

=== SnapCenter Plug-in for Microsoft SQL Server requirements

You should have a user with local administrator privileges with local login permissions on the remote host. If you manage cluster nodes, you need a user with administrative privileges to all the nodes in the cluster.

You should have a user with sysadmin permissions on the SQL Server. The plug-in uses Microsoft VDI Framework, which requires sysadmin access.

== Install SnapCenter Server

=== Step 1: Download and install SnapCenter Server

. Download the SnapCenter Server installation package from the https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab[NetApp Support Site^] and then double-click the exe.
+
After you initiate the installation, all the prechecks are performed and if the minimum requirements are not met appropriate error or warning messages are displayed. You can ignore the warning messages and proceed with installation; however, errors should be fixed.
. Review the pre-populated values required for the SnapCenter Server installation and modify if required.
+
You do not have to specify the password for MySQL Server repository database. During SnapCenter Server installation the password is auto generated.
+
NOTE: The special character “%” is not supported in the custom path for installation. If you include “%” in the path, installation fails.

. Click *Install Now*.

=== Step 2: Log in to SnapCenter

. Launch SnapCenter from a shortcut on the host desktop or from the URL provided by the installation (_\https://server:8146_ for default port 8146 where SnapCenter Server is installed).
. Enter the credentials.
+
For a built-in domain admin username format, use: _NetBIOS\<username>_ or _<username>@<domain>_ or _<DomainFQDN>\<username>_.
+
For a built-in local admin username format, use _<username>_.
. Click *Sign In*.

=== Step 3: Add a SnapCenter Standard controller-based license

. Log in to the controller using the ONTAP command line and enter:
+
`system license add -license-code <license_key>`
. Verify the license:
+
`license show`

=== Step 4: Add a SnapCenter capacity-based license

. In the SnapCenter GUI left pane, click *Settings > Software*, and then in the License section, click *+*.
. Select one of two methods for obtaining the license:
+
** Enter your NetApp Support Site login credentials to import licenses.
** Browse to the location of the NetApp License File and click *Open*.
. In the Notifications page of the wizard, use the default capacity threshold of 90 percent.
. Click *Finish*.

=== Step 5: Set up storage system connections

. In the left pane, click *Storage Systems > New*.
. In the Add Storage System page, perform the following:
  .. Enter the name or IP address of the storage system.
  .. Enter the credentials that are used to access the storage system.
  .. Select the check boxes to enable Event Management System (EMS) and AutoSupport.
. Click *More Options* if you want to modify the default values assigned to platform, protocol, port, and timeout.
. Click *Submit*.

== Install the Plug-in for Microsoft SQL Server

=== Step 1: Set up Run As Credentials to install the Plug-in for Microsoft SQL Server

. In the left pane, click *Settings > Credentials > New*.
. Enter the credentials.
+
For a built-in domain admin username format, use: _NetBIOS\<username>_ or _<username>@<domain>_ or _<DomainFQDN>\<username>_.
+
For a built-in local admin username format, use _<username>_.

=== Step 2: Add a host and install the Plug-in for Microsoft SQL Server

. In the SnapCenter GUI left pane, click *Hosts > Managed Hosts > Add*.
. In the Hosts page of the wizard, perform the following:
  .. Host Type: Select Windows host type.
  .. Host name: Use the SQL host or specify the FQDN of a dedicated Windows host.
  .. Credentials: Select the valid credential name of the host that you created or create new credentials.
. In the Select Plug-ins to Install section, select *Microsoft SQL Server*.
. Click *More Options* to specify the following details:
  .. Port: Either retain the default port number or specify the port number.
  .. Installation Path: The default path is _C:\Program Files\NetApp\SnapCenter_.
  You can optionally customize the path.
  .. Add all hosts in the cluster: Select this check box if you are using SQL in WSFC.
  .. Skip preinstall checks: Select this check box if you already installed the plug-ins manually or you do not want to validate whether the host meets the requirements for installing the plug-in.
. Click *Submit*.
