---
permalink: protect-scsql/quick-start-to-prepare-for-snapcenter-plug-in-install-for-sql-server.html
sidebar: sidebar
keywords: credentials
summary: Provides instructions for preparing to install the SnapCenter Server and the SnapCenter Plug-in for Microsoft SQL Server.
---
= Quick start to install SnapCenter Plug-in for SQL Server
:icons: font
:imagesdir: ../media/

[.lead]
Provides a condensed set of preparation instructions for installing the SnapCenter Server and the SnapCenter Plug-in for Microsoft SQL Server.

== Prepare for installation
=== Domain and workgroup requirements

SnapCenter Server can be installed on systems that are either in a domain or in a workgroup. 

If you are using an Active Directory domain, you should use a Domain user with local administrator rights. The Domain user should be a member of the local Administrator group on the Windows host.

If you are using workgroups, you should use a local account that has local administrator rights.

=== License requirements

The type of licenses you install depends on your environment.

[width=100%]
[cols="1,3"]
|===
| License | Where required

a| SnapCenter Standard controller-based
a| Required for FAS or AFF storage controllers

SnapCenter Standard license is a controller-based license and is included as part of the premium bundle. If you have the SnapManager Suite license, you also get the SnapCenter Standard license entitlement.
If you want to install SnapCenter on a trial basis with FAS or AFF storage, you can obtain a Premium Bundle evaluation license by contacting the sales representative.
a| SnapCenter Standard capacity-based
a| Required with ONTAP Select and Cloud Volumes ONTAP

If you are a Cloud Volumes ONTAP or ONTAP Select customer, you need to procure a per TB capacity-based license based on the data managed by SnapCenter.
By default, SnapCenter ships a built-in 90-day 100 TB SnapCenter Standard capacity-based trial license. For other details, contact the sales representative.
a| SnapMirror or SnapVault
a| ONTAP

Either SnapMirror or SnapVault license is required if replication is enabled in SnapCenter.
a| Additional licenses (optional)
a| See link:../install/concept_snapcenter_licenses.html[SnapCenter licenses^].
a| SnapCenter Standard licenses (optional)
a| Secondary destinations

NOTE: It is recommended, but not required, that you add SnapCenter Standard licenses to secondary destinations. If SnapCenter Standard licenses are not enabled on secondary destinations, you cannot use SnapCenter to backup resources on the secondary destination after performing a failover operation. However, a FlexClone license is required on secondary destinations to perform clone and verification operations.

|===

=== Host and port requirements

For ONTAP and application plug-in minimum requirements see https://imt.netapp.com/matrix/imt.jsp?components=105961;&solution=1259&isHWU&src=IMT[Interoperability Matrix Tool^].

[width=100%]
[cols="1,3"]
|===
|Hosts |Minimum requirements

a|Operating System (64-bit)
a|See https://imt.netapp.com/matrix/imt.jsp?components=105961;&solution=1259&isHWU&src=IMT[Interoperability Matrix Tool^]

a|CPU
a|
* Server host: 4 cores

* Plug-in host: 1 core
a|RAM
a|
* Server host: 8 GB

* Plug-in host: 1 GB
a|Hard drive space
a|Server host:

* 4 GB for SnapCenter Server software and logs

* 6 GB for SnapCenter repository

* Each plug-in host: 2 GB for plug-in installation and logs, this is required only if plug-in is installed on a dedicated host.
a|Third-party libraries
a|Required on SnapCenter Server host and plug-in host:

* Microsoft .NET Framework 4.7.2 or later

* Windows Management Framework (WMF) 4.0 or later

* PowerShell 4.0 or later
a|Browsers
a|Chrome, Internet Explorer, and Microsoft Edge
|===

[width=100%]
[cols="1,3"]
|===
|Port type |Default port

a|SnapCenter port
a|8146 (HTTPS), bidirectional, customizable, as in the URL _\https://server:8146_
a|SnapCenter SMCore communication port
a|8145 (HTTPS), bidirectional, customizable
a|Repository database
a|3306 (HTTPS), bidirectional
a|Windows plug-in hosts
a|135, 445 (TCP)

In addition to ports 135 and 445, the dynamic port range specified by Microsoft should also be open. Remote install operations use the Windows Management Instrumentation (WMI) service, which dynamically searches this port range.

For information on the dynamic port range supported, see https://docs.microsoft.com/en-US/troubleshoot/windows-server/networking/service-overview-and-network-port-requirements[Service overview and network port requirements for Windows^].
a|SnapCenter Plug-in for Windows
a|8145 (HTTPS), bidirectional, customizable
a|ONTAP cluster or SVM communication port
a|443 (HTTPS), bidirectional;
80 (HTTP), bidirectional

The port is used for communication between the SnapCenter Server host, plug-in host, and SVM or ONTAP Cluster.
|===

=== SnapCenter Plug-in for Microsoft SQL Server requirements

You should have a user with local administrator privileges with local login permissions on the remote host. If you manage cluster nodes, you need a user with administrative privileges to all the nodes in the cluster.

You should have a user with sysadmin permissions on the SQL Server. The plug-in uses Microsoft VDI Framework, which requires sysadmin access.

If you were using SnapManager for Microsoft SQL Server and want to import data from SnapManager for Microsoft SQL Server to SnapCenter, see link:../protect-scsql/concept_import_archived_backups_from_snapmanager_for_sql_to_snapcenter.html[Import archived backups^]


