---
permalink: protect-scsql/reference_host_requirements_to_install_snapcenter_plug_in_package_for_windows.html
sidebar: sidebar
keywords: SAP HANA,Custom plug-ins
summary: 'Before you install the SnapCenter Plug-ins Package for Windows, you should be familiar with some basic host system space requirements and sizing requirements.'
---
= Host requirements to install SnapCenter Plug-ins Package for Windows
:icons: font
:imagesdir: ../media/

[.lead]
Before you install the SnapCenter Plug-ins Package for Windows, you should be familiar with some basic host system space requirements and sizing requirements.

|===
| Item| Requirements
a|
Operating Systems
a|
Microsoft Windows**Note:** You must enable the Cluster Shared Volumes (CSV) feature in Windows Server 2008 R2 SP1 if you want to create CSV-type disks.

For the latest information about supported versions, see the NetApp Interoperability Matrix Tool (IMT).

http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]

a|
Minimum RAM for the SnapCenter plug-in on host
a|
1 GB
a|
Minimum install and log space for the SnapCenter plug-in on host
a|
5 GB**Note:** You should allocate sufficient disk space and monitor the storage consumption by the logs folder. The log space required varies depending on the number of the entities to be protected and the frequency of data protection operations. If there is no sufficient disk space, the logs will not be created for the recently run operations.

a|
Required software packages
a|

* Microsoft .NET Framework 4.5.2 or later
* Windows Management Framework (WMF) 4.0 or later
* PowerShell 4.0 or later

For the latest information about supported versions, see the NetApp Interoperability Matrix Tool (IMT).

http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]

|===
