---
permalink: protect-scsql/task_import_archived_backups.html
sidebar: sidebar
keywords: SnapVault
summary: 'You can import only those backups that were archived using SnapVault technology from SnapManager for Microsoft SQL Server to SnapCenter from the command-line interface.'
---
= Import archived backups
:icons: font
:imagesdir: ../media/

[.lead]
You can import only those backups that were archived using SnapVault technology from SnapManager for Microsoft SQL Server to SnapCenter from the command-line interface.

* Both the SnapCenter Plug-in for Microsoft SQL Server and SnapManager for Microsoft SQL Server 7.x must be installed on the same host.
* For cluster support, both the plug-in and 7.x product must have been installed on each node in the cluster.
* You must have added the host or cluster to SnapCenter and discovered the resources available for backup on the host or cluster.
* You must have backed up the SnapManager for Microsoft SQL Server SnapInfo folder.
+
If the import operation fails, you can retrieve the backup metadata from the SnapInfo directory.

|===
a|
*Best Practice:* It is a best practice to configure the log backup folder for the SnapCenter Plug-in for Microsoft SQL Server.

|===
For information on SnapCenter installation and configuration tasks, see the SnapCenter installation information. For information on SnapManager for Microsoft SQL Server installation and configuration tasks, see the SnapManager installation information.

After the archived backups have been imported to SnapCenter from SnapManager for Microsoft SQL Server, you can perform restore and clone operations on these backups from SnapCenter. Simultaneously, you can also continue to perform backup, restore, and clone operations using SnapManager for Microsoft SQL Server.

. Perform the following steps to create schedules similar to SnapManager for Microsoft SQL Server schedules manually in SnapCenter:
 .. Retrieve the schedule information from SnapManager for Microsoft SQL Server by using the Get-SmSchedule cmdlet.
 .. Save the schedule information.
+
You can use this schedule information while creating policies in SnapCenter.

 .. Disable SnapManager for Microsoft SQL Server schedules by using the Get-SmSchedule -Hostname <hostname> -PluginCode SMSQL -DisableCurrentGenSchedule cmdlet.
. Import archived backups by using the Invoke-SmBackupMigration cmdlet.
