---
permalink: protect-scsql/task_migrate_resources_to_netapp_storage.html
sidebar: sidebar
keywords:
summary: 'After you have provisioned your NetApp storage system using SnapCenter Plug-in for Microsoft Windows, you can migrate your resources to the NetApp storage system or from one NetApp LUN to another NetApp LUN using either the SnapCenter graphical user interface \(GUI\) or using the PowerShell cmdlets.'
---
= Migrate resources to NetApp storage system
:icons: font
:imagesdir: ../media/

[.lead]
After you have provisioned your NetApp storage system using SnapCenter Plug-in for Microsoft Windows, you can migrate your resources to the NetApp storage system or from one NetApp LUN to another NetApp LUN using either the SnapCenter graphical user interface (GUI) or using the PowerShell cmdlets.

*What you will need*

* You must have added storage systems to SnapCenter Server.
* You must have refreshed (discovered) the SQL Server resources.

Most of the fields on these wizard pages are self-explanatory. The following information describes some of the fields for which you might require guidance.

*Steps*

. In the left navigation pane, click *Resources*, and then select the appropriate plug-in from the list.
. In the *Resources* page, select *Database* or *Instance* from the *View* drop-down list.
. Select either the database or the instance from the list and click *Migrate*.
. In the *Resources* page, perform the following actions:
+
|===
| For this field...| Do this...

a|
*Database Name* (optional)
a|
If you have selected an instance for migration, you must select the databases of that instance from the *Databases* drop-down list.
a|
*Choose Destinations*
a|
Select the target location for data and log files.

The data and log files are moved to Data and Log folder respectively under the selected NetApp drive. If any folder in the folder structure is not present, then a folder is created, and the resource is migrated.
a|
*Show database file details* (optional)
a|
Select this option when you want to migrate multiple files of a single database.

NOTE: This option is not displayed when you select the *Instance* resource.

a|
*Options*
a|
Select *Delete copy of Migrated Database at Original Location* to delete copy of database from the source.

Optional: *RUN UPDATE STATISTICS on tables before detaching the database*.
|===

. In the *Verify* page, perform the following actions:
+
|===
| For this field...| Do this...

a|
*Database Consistency Check Options*
a|
Select *Run before* to check the integrity of the database before migration.    Select *Run after* to check the integrity of the database after migration.
a|
*DBCC CHECKDB options*
a|
* Select *PHYSICAL_ONLY* option to limit the integrity check to the physical structure of the database and to detect torn pages, checksum failures, and common hardware failures that impact the database.

* Select *NO_INFOMSGS* option to suppress all of the informational messages.

* Select *ALL_ERRORMSGS* option to display all of the reported errors per object.

* Select *NOINDEX* option if you do not want to check nonclustered indexes.
+
The SQL Server database uses Microsoft SQL Server Database Consistency Checker (DBCC) to check the logical and physical integrity of the objects in the database.
+
NOTE: You might want to select this option to decrease the execution time.

* Select **TABLOCK** option to limit the checks and obtain locks instead of using an internal database Snapshot copy.
|===

.  Review the summary, and then click **Finish**.
