---
permalink: protect-scsql/task_create_a_storage_system_connection_and_a_credential_using_powershell_cmdlets.html
sidebar: sidebar
keywords: credentials
summary: 'You must create a storage virtual machine \(SVM\) connection and a credential before using PowerShell cmdlets to perform data protection operations.'
---
= Create a storage system connection and a credential using PowerShell cmdlets
:icons: font
:imagesdir: ../media/

[.lead]
You must create a storage virtual machine (SVM) connection and a credential before using PowerShell cmdlets to perform data protection operations.

* You should have prepared the PowerShell environment to execute the PowerShell cmdlets.
* You should have the required permissions in the Infrastructure Admin role to create storage connections.
* You should ensure that the plug-in installations are not in progress.
+
Host plug-in installations must not be in progress while adding a storage system connection because the host cache might not be updated and databases status might be displayed in the SnapCenter GUI as "`Not available for backup`" or "`Not on NetApp storage`".

* Storage system names should be unique.
+
SnapCenter does not support multiple storage systems with the same name on different clusters. Each storage system that is supported by SnapCenter should have a unique name and a unique data LIF IP address.

The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running Get-Helpcommand_name. Alternatively, you can also refer to the _Cmdlet Reference Guide_.

https://library.netapp.com/ecm/ecm_download_file/ECMLP2874310[SnapCenter Software 4.4 Cmdlet Reference Guide]

. Initiate a PowerShell connection session by using the Open-SmConnection cmdlet.
+
This example opens a PowerShell session:
+
----
PS C:\> Open-SmStorageConnection
----

. Create a new connection to the storage system by using the Add-SmStorageConnection cmdlet.
+
This example creates a new storage system connection:
+
----
PS C:\> Add-SmStorageConnection -Storage test_vs1 -Protocol Https
-Timeout 60
----

. Create a new credential by using the Add-SmCredential cmdlet.
+
This example creates a new credential named FinanceAdmin with Windows credentials:
+
----
PS C:> Add-SmCredential -Name FinanceAdmin -AuthMode Windows
-Credential sddev\administrator
----
