---
permalink: protect-scsql/task_clean_up_the_secondary_backup_count_using_powershell_cmdlets.html
sidebar: sidebar
keywords: backups
summary: 'You can use the Remove-SmBackup cmdlet to clean up the backup count for secondary backups that have no Snapshot copies. You might want use this cmdlet when the total Snapshot copies displayed in the Manage Copies topology do not match the secondary storage Snapshot copy retention setting.'
---
= Clean up the secondary backup count using PowerShell cmdlets
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Remove-SmBackup cmdlet to clean up the backup count for secondary backups that have no Snapshot copies. You might want use this cmdlet when the total Snapshot copies displayed in the Manage Copies topology do not match the secondary storage Snapshot copy retention setting.

You must have prepared the PowerShell environment to execute the PowerShell cmdlets.

The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running Get-Helpcommand_name. Alternatively, you can also refer to the _Cmdlet Reference Guide_.

https://library.netapp.com/ecm/ecm_download_file/ECMLP2874310[SnapCenter Software 4.4 Cmdlet Reference Guide]

. Initiate a connection session with the SnapCenter Server for a specified user by using the Open-SmConnection cmdlet.
+
----
Open-SmConnection  -SMSbaseurl  https:\\snapctr.demo.netapp.com:8146/
----

. Clean up secondary backups count using the -CleanupSecondaryBackups parameter.
+
This example cleans up the backup count for secondary backups with no Snapshot copies:
+
----
Remove-SmBackup -CleanupSecondaryBackups
Remove-SmBackup
Are you sure want to remove the backup(s).
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):
----

*Related information*

https://library.netapp.com/ecm/ecm_download_file/ECMLP2874310[SnapCenter Software 4.4 Cmdlet Reference Guide]
