---
permalink: protect-scsql/task_install_snapcenter_plug_in_package_for_windows_on_multiple_remote_hosts_using_cmdlets_scsql.html
sidebar: sidebar
keywords: credentials
summary: 'You can install the SnapCenter Plug-ins Package for Windows on multiple hosts simultaneously by using the Install-SmHostPackage PowerShell cmdlet.'
---
= Install SnapCenter Plug-in for Microsoft Windows on multiple remote hosts by using cmdlets
:icons: font
:imagesdir: ../media/

[.lead]
You can install the SnapCenter Plug-ins Package for Windows on multiple hosts simultaneously by using the Install-SmHostPackage PowerShell cmdlet.

You must have logged in to SnapCenter as a domain user with local administrator rights on each host on which you want to install the plug-in package.

. Launch PowerShell.
. On the SnapCenter Server host, establish a session using the Open-SmConnection cmdlet, and then enter your credentials.
. Install the SnapCenter Plug-in for Microsoft Windows on multiple remote hosts using the Install-SmHostPackage cmdlet and the required parameters.
+
The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running Get-Helpcommand_name. Alternatively, you can also refer to the _Cmdlet Reference Guide_.
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2874310[SnapCenter Software 4.4 Cmdlet Reference Guide]
+
You can use the -skipprecheck option when you have already installed the plug-ins manually and you do not want to validate whether the host meets the requirements for installing the plug-in.

. Enter your credentials for remote installation.
