---
permalink: protect-scsql/task_perform_clone_lifecycle_management.html
sidebar: sidebar
keywords:
summary: 'Using SnapCenter, you can create clones from a resource group or database. You can either perform on-demand clone or you can schedule recurring clone operations of a resource group or database . If you clone a backup periodically, you can use the clone to develop applications, populate data, or recover data.'
---
= Perform Clone Lifecycle
:icons: font
:imagesdir: ../media/

[.lead]
Using SnapCenter, you can create clones from a resource group or database. You can either perform on-demand clone or you can schedule recurring clone operations of a resource group or database. If you clone a backup periodically, you can use the clone to develop applications, populate data, or recover data.

SnapCenter enables you to schedule multiple clone operations to run simultaneously across multiple servers.

*What you will need*

* While cloning to a standalone database instance, ensure that the mount point path exists and it is a dedicated disk.
* While cloning to a Failover Cluster Instance (FCI), ensure that the mount points exists, it is a shared disk, and the path and the FCI should belong to the same SQL resource group.
* If the source database or the target instance is on a cluster shared volume (csv), then the cloned database will be on the csv.

NOTE: For virtual environments (VMDK/RDM), ensure that the mount point is a dedicated disk.

*Steps*

. In the left navigation pane, click *Resources*, and then select the appropriate plug-in from the list.
. In the Resources page, select either *Database* or *Resource Group* from the *View* list.
. Select the resource group or database, and then click *Clone Lifecycle*.
. In the Options page, perform the following actions:
+
|===
| For this field...| Do this...

a|
Clone job name
a|
Specify the clone life cycle job name that helps in monitoring and modifying the clone life cycle job.
a|
Clone server
a|
Choose the host on which the clone should be placed.
a|
Clone instance
a|
Choose the clone instance to which you want to clone the database.     This SQL instance must be located in the specified clone server.
a|
Clone suffix
a|
Enter a suffix that will be appended to the clone database to identify that it is a clone.     Each SQL instance that is used to create a clone resource group must have a unique database name. For example, if the clone resource group contains a source database "`db1`" from an SQL instance "`inst1`", and if "`db1`" is cloned to "`inst1`", then the clone database name should be "`db1__clone`". "`__clone`" is a mandatory user-defined suffix because the database is cloned to the same instance. If "`db1`" is cloned to the SQL instance "`inst2`", then the clone database name can remain "`db1`" (the suffix is optional) because the database is cloned to a different instance.
a|
Auto assign mount point or Auto assign volume mount point under path
a|
Choose whether to automatically assign a mount point or volume mount point under a path.     Choosing to auto assign a volume mount point under a path enables you to provide a specific directory. The mount points will be created within that directory. Before you choose this option, you must ensure that the directory is empty. If there is a database in the directory, the database will be in an invalid state after the mount operation.
|===

. In the Location page, select a storage location to create a clone.
. In the Script page, enter the path and the arguments of the prescript or postscript that should be run before or after the clone operation, respectively.
+
For example, you can run a script to update SNMP traps, automate alerts, send logs, and so on.
+
The default script timeout is 60 seconds.

. In the Schedule page, perform one of the following actions:
 ** Select *Run now* if you want to execute the clone job immediately.
 ** Select *Configure schedule* when you want to determine how frequently the clone operation should occur, when the clone schedule should start, on which day the clone operation should occur, when the schedule should expire, and whether the clones have to be deleted after the schedule expires.
. In the Notification page, from the *Email preference* drop-down list, select the scenarios in which you want to send the emails.
+
You must also specify the sender and receiver email addresses, and the subject of the email. If you want to attach the report of the clone operation performed, select *Attach Job Report*.
+
NOTE: For email notification, you must have specified the SMTP server details using the either the GUI or the PowerShell command Set-SmSmtpServer.

+
For EMS, you can refer to https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_ems_data_collection[Manage EMS data collection]

. Review the summary, and then click *Finish*.

You should monitor the cloning process using the *Monitor* > *Jobs* page.
