---
permalink: protect-scsql/task_set_up_credentials_for_snapcenter_plug_ins_package_for_windows.html
sidebar: sidebar
keywords: credentials
summary: 'SnapCenter uses credentials to authenticate users for SnapCenter operations. You should create credentials for installing SnapCenter plug-ins and additional credentials for performing data protection operations on databases or Windows file systems.'
---
= Set up credentials for the SnapCenter Plug-ins Package for Windows
:icons: font
:imagesdir: ../media/

[.lead]
SnapCenter uses credentials to authenticate users for SnapCenter operations. You should create credentials for installing SnapCenter plug-ins and additional credentials for performing data protection operations on databases or Windows file systems.

*What you will need*

* You must set up Windows credentials before installing plug-ins.
* You must set up the credentials with administrator privileges, including administrator rights on the remote host.
* SQL authentication on Windows hosts
+
You must set up SQL credentials after installing plug-ins.
+
If you are deploying SnapCenter Plug-in for Microsoft SQL Server, you must set up SQL credentials after installing plug-ins. Set up a credential for a user with SQL Server sysadmin permissions.
+
The SQL authentication method authenticates against a SQL Server instance. This means that a SQL Server instance must be discovered in SnapCenter. Therefore, before adding a SQL credential, you must add a host, install plug-in packages, and refresh resources. You need SQL Server authentication for performing operations such as scheduling or discovering resources.

*Steps*

. In the left navigation pane, click *Settings*.
. In the *Settings* page, click *Credential*.
. Click *New*.
. In the *Credential* page, specify the information required for configuring credentials:
+
|===
| For this field...| Do this...

a|
Credential name
a|
Enter a name for the credential.
a|
User name/Password
a|
Enter the user name and password that are to be used for authentication.

 ** Domain administrator
+
Specify the domain administrator on the system on which you are installing the SnapCenter plug-in. Valid formats for the Username field are:

  *** `NetBIOS\UserName`
  *** `Domain FQDN\UserName`

 ** Local administrator (for workgroups only)
+
For systems that belong to a workgroup, specify the built-in local administrator on the system on which you are installing the SnapCenter plug-in. You can specify a local user account that belongs to the local administrators group if the user account has elevated privileges or the User Access control feature is disabled on the host system. The valid format for the Username field is: `UserName`

+
Do not use double quotes (") in passwords.
a|
Authentication Mode
a|
Select the authentication mode that you want to use. If you select the SQL authentication mode, you must also specify the SQL server instance and the host where the SQL instance is located.
|===

. Click *OK*.

After you finish setting up the credentials, you might want to assign credential maintenance to a user or group of users on the *User and Access* page.
