---
permalink: protect-scsql/task_disaster_recovery_scsql.html
sidebar: sidebar
keywords:
summary: 'When the SnapCenter Plug-in for SQL Server is down, perform the following manual steps to recover the plug-in.'
---
= Disaster recovery of SnapCenter Plug-in for SQL Server
:icons: font
:imagesdir: ../media/

[.lead]
When the SnapCenter Plug-in for SQL Server is down, perform the following steps to switch to a different SQL host and recover the data.

.What you'll need

* The secondary host should have the same operating system, application, and host name as the primary host.
* Push the SnapCenter Plug-in for SQL Server to an alternative host using *Add host* or *Modify host* page. See link:https://docs.netapp.com/us-en/snapcenter/admin/concept_manage_hosts.html[Manage hosts] for more information.

.Steps

. Select the host from the *Hosts* page to modify and install the SnapCenter Plug-in for SQL Server.
. (Optional) Replace the SnapCenter Plug-in for SQL Server configuration files from disaster recovery (DR) backup to the new machine.
. Import Windows and SQL schedules from the SnapCenter Plug-in for SQL Server folder from the DR backup.

.For more information

See the link:https://www.youtube.com/watch?v=Nbr_wm9Cnd4&list=PLdXI3bZJEw7nofM6lN44eOe4aOSoryckg[Disaster Recovery APIs^] video.
