---
permalink: protect-sco/concept_install_snapcenter_plug_in_for_vmware_vsphere.html
sidebar: sidebar
keywords:
summary: 'If your database is stored on virtual machines \(VMs\), or if you want to protect VMs and datastores, you must deploy the SnapCenter Plug-in for VMware vSphere virtual appliance.'
---
= Install SnapCenter Plug-in for VMware vSphere
:icons: font
:imagesdir: ../media/

[.lead]
If your database is stored on virtual machines (VMs), or if you want to protect VMs and datastores, you must deploy the SnapCenter Plug-in for VMware vSphere virtual appliance.

The SnapCenter Plug-in for VMware vSphere documentation has more information.

https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_get_started_overview.html[SnapCenter Plug-in for VMware vSphere Deployment Guide]

== Deploying CA certificate for SnapCenter plug-in for VMware vSphere

To configure the CA Certificate with SnapCenter Plug-in for VMware vSphere, refer to https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_create_and_or_import_an_SSL_certificate_to_SnapCenter_Plug-in_for_VMware_vSphere_(SCV)[How to create and/or import an SSL certificate to SnapCenter Plug-in for VMware vSphere].

.Configure the CRL file for SnapCenter plug-in for VMware vSphere

* SnapCenter Plug-in for VMware vSphere will look for the CRL files in a pre-configured directory.
* Default directory of the CRL files for SnapCenter Plug-in for VMware vSphere is '/opt/netapp/config/crl'

You can place more than one CRL file in this directory. The incoming certificates will be verified against each CRL.
