---
permalink: protect-sco/concept_snapcenter_plug_in_for_oracle_database_features.html
sidebar: sidebar
keywords: plug-in for Oracle features
summary: 'The Plug-in for Oracle Database integrates with the Oracle database on the Linux or AIX host and with NetApp technologies on the storage system.'
---
= Features of Plug-in for Oracle Database
:icons: font
:imagesdir: ../media/

[.lead]
The Plug-in for Oracle Database integrates with the Oracle database on the Linux or AIX host and with NetApp technologies on the storage system.

* Unified graphical user interface
+
The SnapCenter interface provides standardization and consistency across plug-ins and environments. The SnapCenter interface enables you to complete consistent backup, restore, recovery, and clone operations across plug-ins, use centralized reporting, use at-a-glance dashboard views, set up role-based access control (RBAC), and monitor jobs across all plug-ins.

* Automated central administration
+
You can schedule backup and clone operations, configure policy-based backup retention, and perform restore operations. You can also proactively monitor your environment by configuring SnapCenter to send email alerts.

* Nondisruptive NetApp Snapshot technology
+
SnapCenter uses NetApp Snapshot technology with the Plug-in for Oracle Database and Plug-in for UNIX to back up databases. Snapshots consume minimal storage space.

The Plug-in for Oracle Database also offers the following benefits:

* Support for backup, restore, clone, mount, unmount, and verification workflows
* Automatic discovery of  Oracle databases configured on the host
* Support for cataloging and uncataloging using Oracle Recovery Manager (RMAN)
* RBAC-supported security and centralized role delegation
+
You can also set the credentials so that the authorized SnapCenter users have application-level permissions.

* Support for Archive Log Management (ALM) for restore and clone operations
* Creation of space-efficient and point-in-time copies of production databases for testing or data extraction by using NetApp FlexClone technology
+
A FlexClone license is required on the storage system where you want to create the clone.

* Support for consistency group (CG) feature of ONTAP as part of creating backups in SAN and ASM environments
* Nondisruptive and automated backup verification
* Capability to run multiple backups simultaneously across multiple database hosts
+
In a single operation, Snapshots are consolidated when databases in a single host share the same volume.

* Support for physical and virtualized infrastructures
* Support for NFS, iSCSI, Fibre Channel (FC), RDM, VMDK over NFS and VMFS, and ASM over NFS, SAN, RDM, and VMDK
* Support for the Selective LUN Map (SLM) feature of ONTAP
+
Enabled by default, the SLM feature periodically discovers the LUNs that do not have optimized paths and fixes them. You can configure SLM by modifying the parameters in the scu.properties file located at /var/opt/snapcenter/scu/etc.

 ** You can disable this by setting the value of ENABLE_LUNPATH_MONITORING parameter to false.
 ** You can specify the frequency in which the LUN paths will be fixed automatically by assigning the value (in hours) to LUNPATH_MONITORING_INTERVAL parameter.
For information about SLM, see the http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html[ONTAP 9 SAN Administration Guide^].

* Support for non-volatile memory express (NVMe) on Linux
** NVMe util should be installed on the host.
+
You must install NVMe util to clone or mount to alternate host.
** Backup, restore, clone, mount, unmount, catalog, uncatalog, and verification operations are supported on the NVMe hardware except for the virtualized environments like VMDK and RDM.
+
The above operations are supported on devices without partitions or with single partition.

NOTE: You can configure multipathing solution for NVMe devices by setting the native multipathing option in the kernel. Device Mapper (DM) multipathing is not supported. 

* Supports any non-default user instead of oracle and grid.
+
To support the non-default users, you should set the non-default users by modifying the values of the parameters in the *sco.properties* file located at _file  /var/opt/snapcenter/sco/etc/_. 
+
The default values of the parameters are set as oracle and grid.

** DB_USER=oracle
** DB_GROUP=oinstall
** GI_USER=grid
** GI_GROUP=oinstall

