---
permalink: protect-sco/concept_import_data_from_snapmanager_for_oracle_and_snapmanager_for_sap_to_snapcenter.html
sidebar: sidebar
keywords: import, SnapManager for Oracle, SnapManager for SAP
summary: 'Importing data from SnapManager for Oracle and SnapManager for SAP to SnapCenter enables you to continue to use your data from previous versions.'
---
= Import data from SnapManager for Oracle and SnapManager for SAP to SnapCenter
:icons: font
:imagesdir: ../media/

[.lead]
Importing data from SnapManager for Oracle and SnapManager for SAP to SnapCenter enables you to continue to use your data from previous versions.

You can import data from SnapManager for Oracle and SnapManager for SAP to SnapCenter by running the import tool from the command-line interface (Linux host CLI).

The import tool creates policies and resource groups in SnapCenter. The policies and resource groups created in SnapCenter correspond to the profiles and operations performed using those profiles in SnapManager for Oracle and SnapManager for SAP. The SnapCenter import tool interacts with the SnapManager for Oracle and SnapManager for SAP repository databases and the database that you want to import.

* Retrieves all the profiles, schedules, and operations performed using the profiles.
* Creates a SnapCenter backup policy for each unique operation and each schedule attached to a profile.
* Creates a resource group for each target database.

You can run the import tool by executing the sc-migrate script located at _/opt/NetApp/snapcenter/spl/bin_. When you install the SnapCenter Plug-ins Package for Linux on the database host that you want to import, the sc-migrate script is copied to _/opt/NetApp/snapcenter/spl/bin_.

NOTE: Importing data is not supported from SnapCenter graphical user interface (GUI).

SnapCenter does not support Data ONTAP operating in 7-Mode. You can use the 7-Mode Transition Tool to migrate data and configurations that are stored on a system running Data ONTAP operating in 7-Mode to an ONTAP system.

== Configurations supported for importing data

Before you import data from SnapManager 3.4.x for Oracle and SnapManager 3.4.x for SAP to SnapCenter, you should be aware of the configurations that are supported with the SnapCenter Plug-in for Oracle Database.

The configurations that are supported with the SnapCenter Plug-in for Oracle Database are listed in the https://imt.netapp.com/matrix/imt.jsp?components=112391;&solution=1259&isHWU&src=IMT[NetApp Interoperability Matrix Tool^].

== What gets imported to SnapCenter

You can import profiles, schedules, and operations performed using the profiles.

|===
| From SnapManager for Oracle and SnapManager for SAP | To SnapCenter

a|
Profiles without any operations and schedules
a|
A policy is created with default backup type as Online and backup scope as Full.
a|
Profiles with one or more operations
a|
Multiple policies are created based on a unique combination of a profile and operations performed using that profile.

The policies created in SnapCenter contain the archive log pruning and retention details retrieved from the profile and corresponding operations.

a|
Profiles with Oracle Recovery Manager (RMAN) configuration
a|
Policies are created with the *Catalog backup with Oracle Recovery Manager* option enabled.

If external RMAN cataloging was used in SnapManager, you must configure the RMAN catalog settings in SnapCenter. You can either select the existing credential or create a new credential.

If RMAN was configured through control file in SnapManager, then you do not have to configure RMAN in SnapCenter.

a|
Schedule attached to a profile
a|
A policy is created just for the schedule.
a|
Database
a|
A resource group is created for each database that is imported.

In a Real Application Clusters (RAC) setup, the node on which you run the import tool becomes the preferred node after importing and the resource group is created for that node.

|===
NOTE:  When a profile is imported, a verification policy is created along with the backup policy.

When SnapManager for Oracle and SnapManager for SAP profiles, schedules, and any operations performed using the profiles are imported to SnapCenter, the different parameters values are also imported.

|===
| SnapManager for Oracle and SnapManager for SAP parameter and values | SnapCenter parameter and values | Notes

a|
Backup Scope

* Full
* Data
* Log

a|
Backup Scope

* Full
* Data
* Log

a|

a|
Backup Mode

* Auto
* Online
* Offline

a|
Backup Type

* Online
* Offline Shutdown

a|
If the backup mode is Auto, then the import tool checks the database state when the operation was performed, and appropriately sets the backup type as either Online or Offline Shutdown.
a|
Retention

* Days
* Counts

a|
Retention

* Days
* Counts

a|
SnapManager for Oracle and SnapManager for SAP uses both Days and Counts to set the retention.

In SnapCenter, there is either Days _OR_ Counts. So, the retention is set with respect to days as the days get preference over counts in SnapManager for Oracle and SnapManager for SAP.
a|
Pruning for Schedules

* All
* system change number (SCN)
* Date
* Logs created before specified hours, days, weeks, and months

a|
Pruning for Schedules

* All
* Logs created before specified hours and days

a|
SnapCenter does not support pruning based on SCN, Date, weeks, and months.
a|
Notification

* Emails sent only for successful operations
* Emails sent only for failed operations
* Emails sent for both success and failed operations

a|
Notification

* Always
* On failure
* Warning
* Error

a|
The email notifications are imported.

However, you must manually update the SMTP server using the SnapCenter GUI. The subject of the email is left blank for you to configure.

|===

== What does not get imported to SnapCenter

The import tool does not import everything to SnapCenter.

You cannot import the following to SnapCenter:

* Backup metadata
* Partial backups
* Raw device mapping (RDM) and Virtual Storage Console (VSC) related backups
* Roles or any credentials available in the SnapManager for Oracle and SnapManager for SAP repository
* Data related to verification, restore, and clone operations
* Pruning for operations
* Replication details specified in the SnapManager for Oracle and SnapManager for SAP profile
+
After importing, you must manually edit the corresponding policy created in SnapCenter to include the replication details.

* Cataloged backup information

== Prepare to import data

Before you import data to SnapCenter, you must perform certain tasks to run the import operation successfully.

*Steps*

. Identify the database that you want to import.
. Using SnapCenter, add the database host and install SnapCenter Plug-ins Package for Linux.
. Using SnapCenter, set up the connections for the storage virtual machines (SVMs) used by the databases on the host.
. In the left navigation pane, click *Resources*, and then select the appropriate plug-in from the list.
. In the Resources page, ensure that the database to be imported is discovered and displayed.
+
When you want to run the import tool, the database must be accessible or else the resource group creation fails.
+
If the database has credentials configured, you must create a corresponding credential in SnapCenter, assign the credential to the database, and then re-run discovery of the database. If the database is residing on Automatic Storage Management (ASM), you must create credentials for the ASM instance, and assign the credential to the database.

. Ensure that the user running the import tool has sufficient privileges to run SnapManager for Oracle or SnapManager for SAP CLI commands (such as the command to suspend schedules) from SnapManager for Oracle or SnapManager for SAP host.
. Run the following commands on the SnapManager for Oracle or SnapManager for SAP host to suspend the schedules:
+
.. If you want to suspend the schedules on the SnapManager for Oracle host, run:
+
* `smo credential set -repository -dbname repository_database_name -host host_name -port port_number -login -username user_name_for_repository_database`
* `smo profile sync -repository -dbname repository_database_name -host host_name -port port_number -login -username host_user_name_for_repository_database`
* `smo credential set -profile -name profile_name`
+
NOTE: You must run the smo credential set command for each profile on the host.

+
.. If you want to suspend the schedules on the SnapManager for SAP host, run:
+
 ** `smsap credential set -repository -dbname repository_database_name -host host_name -port port_number -login -username user_name_for_repository_database`
 ** `smsap profile sync -repository -dbname repository_database_name -host host_name -port port_number -login -username host_user_name_for_repository_database`
 ** `smsap credential set -profile -name profile_name`
+
NOTE: You must run the smsap credential set command for each profile on the host.

. Ensure that fully qualified domain name (FQDN) of the database host is displayed when you run hostname -f.
+
If FQDN is not displayed, you must modify /etc/hosts to specify the FQDN of the host.

== Import data

You can import data by running the import tool from the database host.

*About this task*

The SnapCenter backup policies that are created after importing have different naming formats:

* Policies created for the profiles without any operations and schedules have the SM_PROFILENAME_ONLINE_FULL_DEFAULT_MIGRATED format.
+
When no operation is performed using a profile, the corresponding policy is created with default backup type as online and backup scope as full.

* Policies created for the profiles with one or more operations have the SM_PROFILENAME_BACKUPMODE_BACKUPSCOPE_MIGRATED format.
* Policies created for the schedules attached to the profiles have the SM_PROFILENAME_SMOSCHEDULENAME_BACKUPMODE_BACKUPSCOPE_MIGRATED format.

*Steps*

. Log in to the database host that you want to import.
. Run the import tool by executing the sc-migrate script located at _/opt/NetApp/snapcenter/spl/bin_.
. Enter the SnapCenter Server user name and password.
+
After validating the credentials, a connection is established with SnapCenter.

. Enter the SnapManager for Oracle or SnapManager for SAP repository database details.
+
The repository database lists the databases that are available on the host.

. Enter the target database details.
+
If you want to import all the databases on the host, enter all.

. If you want to generate a system log or send ASUP messages for failed operations, you must enable them either by running the _Add-SmStorageConnection_ or _Set-SmStorageConnection_ command.
+
NOTE: If you want to cancel an import operation, either while running the import tool or after importing, you must manually delete the SnapCenter policies, credentials, and resource groups that were created as part of import operation.

*Results*

The SnapCenter backup policies are created for profiles, schedules, and operations performed using the profiles. Resource groups are also created for each target database.

After importing the data successfully, the schedules associated with the imported database are suspended in SnapManager for Oracle and SnapManager for SAP.

NOTE: After importing, you must manage the imported database or file system using SnapCenter.


The logs for every execution of the import tool are stored in the _/var/opt/snapcenter/spl/logs_ directory with the name spl_migration_timestamp.log. You can refer to this log to review import errors and troubleshoot them.
