---
permalink: protect-sco/concept_what_you_can_do_with_the_snapcenter_plug_in_for_oracle_database.html
sidebar: sidebar
keywords: backup, restore, clone, oracle database
summary: 'You can use the Plug-in for Oracle Database to back up, verify, restore, recover, mount, unmount, and clone Oracle databases and their resources. You can also catalog or uncatalog the database backups with Oracle Recovery Manager (RMAN).'
---
= What can you do with the Plug-in for Oracle Database
:icons: font
:imagesdir: ../media/

[.lead]
The SnapCenter Plug-in for Oracle Database is a host-side component of the NetApp SnapCenter Software that enables application-aware data protection management of Oracle databases.

The Plug-in for Oracle Database automates the backup, cataloging and uncataloging with Oracle Recovery Manager (RMAN), verification, mounting, unmounting, restore, recovery, and cloning of Oracle databases in your SnapCenter environment.
The Plug-in for Oracle Database installs SnapCenter Plug-in for UNIX to perform all the data protection operations.

You can use the Plug-in for Oracle Database to manage backups of Oracle databases running SAP applications. However, SAP BR*Tools integration is not supported.

* Back up datafiles, control files, and archive log files.
+
Backup is supported only at container database (CDB) level.

* Restore and recovery of databases, CDBs, and pluggable databases (PDBs).
+
Incomplete recovery of PDBs are not supported.

* Create clones of production databases up to a point-in-time.
+
Cloning is supported only at CDB level.

* Verify backups immediately.
* Mount and unmount data and log backups for recovery operation.
* Schedule backup and verification operations.
* Monitor all operations.
* View reports for backup, restore, and clone operations.
