---
permalink: protect-sco/considerations_for_NVMe_configurations.html
sidebar: sidebar
keywords: plug-in for Oracle features
summary: 'Non-volatile memory express  (NVMe) is a data storage protocol that delivers the fastest response times for business-critical enterprise applications. SnapCenter supports NVMe for different Oracle layouts on LINUX Operating system.'
---
= Considerations for NVMe configurations
:icons: font
:imagesdir: ../media/

[.lead]
Non-volatile memory express  (NVMe) is a data storage protocol that delivers the fastest response times for business-critical enterprise applications. SnapCenter supports NVMe for different Oracle layouts on LINUX Operating system. You can use System Manager to configure the NVMe protocol.

You should know the supported storage system, operating system, protocols, Oracle configurations/layouts/versions, and SnapCenter features for NVMe configurations.

* ONTAP 9.6 or later
* Following are the Linux platforms supported
+
|===
|Linux platform |Version

a|
RHEL
a|
8.5
a|
OEL
a|
7.7, 7.8, 7.9, 8.1, 8.2
a|
SUSE
a|
15 SP1, 15 SP2, 15 SP3
a|
|===
+
For more information, see https://docs.netapp.com/us-en/ontap-sanhost.html[ONTAP SAN Host Configuration^]
* The protocols supported are FC, FCoE, TCP-IP, Inifiniband
* Following are the supported Oracle database configurations, layouts, and versions and data protection workflows.
+
|===
|Oracle database configuration |Oracle layouts| Oracle versions |SnapCenter workflows

a|
OMF, FRA, Standalone, RAC, Dataguard
a|
ASM on NVMe or
LVM on NVMe or
Filesystem on NVMe
a|
11g (11.2.0.4), 12cr1, 12cr2, 18c, 19c, 21c
a|
Backup, Restore, Clone, Delete Clone, Clone-split, Federated Backup, Refresh-SmClone, Clone/Mount to alternate host, Catalog, Verification, Mount, Unmount
a|
|===

* Following are the supported device layouts and filesystem types by SCU for NVMe.

|===
|Supported device layout |Unsupported device layout

a|
Non-LVM, LVM, Raw (ASM directly uses the device with proprietary filesystem) device
a|
Virtualization
(RDM, VMDK)
a|
|===

|===
|Device layout (single partition)|Device handled by Oracle|Supported filesystem types

a|
LVM
a|
NA
a|
ext3, ext4, xfs
a|
Non-LVM
a|
NA
a|
ext3, ext4, xfs
a|
Raw device
a|
ASM Udev, ASM FD, ASMLib
a|
NA
a|
|===
