---
permalink: protect-sco/predefined-environment-variables-prescript-postscript-restore.html
sidebar: sidebar
keywords: environment variable, predefined, prescript, postscript, restore
summary: 'SnapCenter allows you to use the predefined environment variables when you execute the prescript and postscript while restoring a database.'
---
= Predefined environment variables for restore specific prescript and postscript
:icons: font
:imagesdir: ../media/

[.lead]
SnapCenter allows you to use the predefined environment variables when you execute the prescript and postscript while restoring a database.

*Supported predefined environment variables for restoring a database*

|===
| Parameter name | Description | Sample data representation

a|
SC_JOB_ID
a|
Job ID of the operation.
a|
257
a|
SC_ORACLE_SID
a|
The system identifier of the database.

If the operation involves multiple databases, this will contain database names separated by double colons.
a|
NFSB31
a|
SC_HOST
a|
Host name of the database.

This parameter will be populated for application volumes.
a|
scsmohost2.gdl.englabe.netapp.com
a|
SC_OS_USER
a|
Operating System owner of the database.
a|
oracle
a|
SC_OS_GROUP
a|
Operating System group of the database.
a|
oinstall
a|
SC_BACKUP_NAME
a|
Name of the backup.

This parameter will be populated for application volumes.
a|
* For non ALM: DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0\|LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1
* For ALM: DATA@RG2_scspr2417819002_07-20-2021_12.16.48.9267_0\|LOG@RG2_scspr2417819002_07-20-2021_12.16.48.9267_1,RG2_scspr2417819002_07-21-2021_12.16.48.9267_1,RG2_scspr2417819002_07-22-2021_12.16.48.9267_1
a|
SC_BACKUP_ID
a|
ID of the backup.

This parameter will be populated for application volumes.
a|
* For non ALM: DATA@203\|LOG@205
* For ALM: DATA@203\|LOG@205,206,207
a|
SC_RESOURCE_GROUP_NAME
a|
The name of the resource group.
a|
RG1
a|
SC_ORACLE_HOME
a|
The path of the Oracle home directory.
a|
/ora01/app/oracle/product/18.1.0/db_1
a|
SC_RECOVERY_TYPE
a|
What files are recovered and the recovery scope.
a|
RESTORESCOPE:{usingBackupControlfile=false}\|RECOVERYSCOPE:{allLogs=true,noLogs=false,untiltime=false,untilscn=false}.
|===

For information about delimiters, see link:../protect-sco/predefined-environment-variables-prescript-postscript-backup.html#supported-delimiters[Supported delimiters^].
