---
permalink: protect-sco/reference_preferred_nodes_in_rac_setup.html
sidebar: sidebar
keywords: 
summary: 'In Oracle Real Application Clusters \(RAC\) setup, you can specify the preferred nodes on which the backup operation will be performed. If you do not specify the preferred node, SnapCenter automatically assigns a node as the preferred node and backup is created on that node.'
---
= Preferred nodes in RAC setup
:icons: font
:imagesdir: ../media/

[.lead]
In Oracle Real Application Clusters (RAC) setup, you can specify the preferred nodes on which the backup operation will be performed. If you do not specify the preferred node, SnapCenter automatically assigns a node as the preferred node and backup is created on that node.

The preferred nodes might be one or all of the cluster nodes where the RAC database instances are present. The backup operation will be triggered only on these preferred nodes in the order of the preference.

For example, the RAC database cdbrac has three instances: cdbrac1 on node1, cdbrac2 on node2, and cdbrac3 on node3. The node1 and node2 instances are configured to be the preferred nodes, with node2 as the first preference and node1 as the second preference. When you perform a backup operation, the operation is first attempted on node2 because it is the first preferred node. If node2 is not in the state to back up, which could be due to multiple reasons such as the plug-in agent is not running on the host, the database instance on the host is not in the required state for the specified backup type, or the database instance on node2 in a FlexASM configuration is not being served by the local ASM instance; then the operation will be attempted on node1. The node3 will not be used for backup because it is not on the list of preferred nodes.

Details about specifying preferred nodes are in the Administration Guide.

http://docs.netapp.com/ocsc-44/topic/com.netapp.doc.ocsc-ag/home.html[Performing administrative tasks]

== Required database state

The RAC database instances on the preferred nodes must be in the required state for the backup to finish successfully:

* One of the RAC database instances in the configured preferred nodes must be in the open state to create an online backup.
* One of the RAC database instances in the configured preferred nodes must be in the mount state, and all other instances, including other preferred nodes, must be in the mount state or lower to create an offline mount backup.
* RAC database instances can be in any state, but you must specify the preferred nodes to create an offline shutdown backup.
