---
permalink: protect-sco/reference_types_of_oracle_database_backups_supported_for_cloning.html
sidebar: sidebar
keywords: 
summary: 'SnapCenter supports cloning of different types of backups of Oracle databases.'
---
= Types of Oracle database backups supported for cloning
:icons: font
:imagesdir: ../media/

[.lead]
SnapCenter supports cloning of different types of backups of Oracle databases.

* Online data backup
* Online full backup
* Offline mount backup
* Offline shutdown backup
* Backups of Data Guard standby databases and Active Data Guard standby databases
* Online data backups, online full backups, offline mount backups, and offline shutdown backups in a Real Application Clusters (RAC) configuration
* Online data backups, online full backups, offline mount backups, and offline shutdown backups in an Automatic Storage Management (ASM) configuration
+
IMPORTANT: Oracle ASM configuration is not supported if user_friendly_names option in the multipath configuration file is set to yes and aliases or symbolic links are defined for the Oracle ASM disks using the udev rules file.

NOTE: Cloning of archive log backups is not supported.
