---
permalink: protect-sco/reference_sources_and_destinations_for_restoring_oracle_databases.html
sidebar: sidebar
keywords: 
summary: 'You can restore an Oracle database from a backup copy on either primary storage or secondary storage. You can only restore databases to the same location on the same database instance. However, in Real Application Cluster \(RAC\) setup, you can restore databases to other nodes.'
---
= Sources and destinations for restoring Oracle databases
:icons: font
:imagesdir: ../media/

[.lead]
You can restore an Oracle database from a backup copy on either primary storage or secondary storage. You can only restore databases to the same location on the same database instance. However, in Real Application Cluster (RAC) setup, you can restore databases to other nodes.

== Sources for restore operations

You can restore databases from a backup on primary storage or secondary storage. If you want to restore from a backup on the secondary storage in a multiple mirror configuration, you can select the secondary storage mirror as the source.

== Destinations for restore operations

You can only restore databases to the same location on the same database instance.

In a RAC setup, you can restore RAC databases from any nodes in the cluster.
