---
permalink: protect-sco/reference_types_of_restore_methods_supported_for_oracle_databases.html
sidebar: sidebar
keywords: SnapCenter Plug-in for Oracle Databases
summary: 'SnapCenter supports connect-and-copy or in-place restore for Oracle databases. During a restore operation, SnapCenter determines the restore method that is appropriate for the file system to be used for restore without any data loss.'
---
= Types of restore methods supported for Oracle databases
:icons: font
:imagesdir: ../media/

[.lead]
SnapCenter supports connect-and-copy or in-place restore for Oracle databases. During a restore operation, SnapCenter determines the restore method that is appropriate for the file system to be used for restore without any data loss.

NOTE: SnapCenter does not support volume-based SnapRestore.

== Connect-and-copy restore

If the database layout differs from the backup or if there are any new files after the backup was created, connect-and-copy restore is performed. In the connect-and-copy restore method, the following tasks are performed:

. The volume is cloned from the Snapshot copy and the file system stack is built on the host using the cloned LUNs or volumes.
. The files are copied from the cloned file systems to the original file systems.
. The cloned file systems are then unmounted from the host and the cloned volumes are deleted from ONTAP.

//Included the below info for BURT 1348035 for 4.5
NOTE: For a Flex ASM setup (where the cardinality is less than the number nodes in the RAC cluster) or ASM RAC databases on VMDK or RDM, only connect-and-copy restore method is supported.

Even if you have forcefully enabled in-place restore, SnapCenter performs connect-and-copy restore in the following scenarios:

* Restore from secondary storage system and if Data ONTAP is earlier than 8.3
* Restore of ASM disk groups present on nodes of an Oracle RAC setup on which database instance is not configured
* In Oracle RAC setup, on any of the peer nodes if the ASM instance or the cluster instance is not running or if the peer node is down
* Restore of control files only
* Restore a subset of tablespaces residing on a ASM disk group
* Disk group is shared between data files, sp file, and password file
* SnapCenter Plug-in Loader (SPL) service is not installed or not running on the remote node in a RAC environment
* New nodes are added to the Oracle RAC and the SnapCenter Server is not aware of the newly added nodes

== In-place restore

If the database layout is similar to the backup and has not undergone any configuration change on the storage and database stack, in-place restore is performed, wherein the restore of file or LUN is performed on ONTAP. SnapCenter supports only Single File SnapRestore (SFSR) as part of the in-place restore method.

NOTE: Data ONTAP 8.3 or later supports in-place restore from secondary location.

If you want to perform in-place restore on the database, ensure that you have only datafiles on the ASM disk group. You must create a backup after any changes are made to the ASM disk group or in the physical structure of the database. After performing in-place restore, the disk group will contain the same number datafiles as at the time of backup.

The in-place restore will be applied automatically when disk group or mount point matches the following criteria:

* No new datafiles are added after backup (foreign file check)
* No addition, deletion, or recreation of ASM disk or LUN after backup (ASM disk group structural change check)
* No addition, deletion, or recreation of LUNs to LVM disk group (LVM disk group structural change check)

NOTE: You can also forcefully enable in-place restore either using GUI, SnapCenter CLI, or PowerShell cmdlet to override the foreign file check and LVM disk group structural change check.

=== Performing In-place restore on ASM RAC

In SnapCenter, the node on which you perform restore is termed as primary node and all other nodes of the RAC on which ASM disk group resides are called peer nodes. SnapCenter changes the state of ASM disk group to dismount on all the nodes where the ASM disk group is in mount state before performing the storage restore operation. After the storage restore is complete, SnapCenter chnages the state of ASM disk group as it was before the restore operation.

In SAN environments, SnapCenter removes devices from all the peer nodes and performs LUN unmap operation before storage restore operation. After storage restore operation, SnapCenter performs LUN map operation and constructs devices on all the peer nodes. In a SAN environment if the Oracle RAC ASM layout is residing on LUNs, then while restoring SnapCenter performs LUN unmap, LUN restore, and LUN map operations on all the nodes of the RAC cluster where the ASM disk group resides. Before restoring even if all the initiators of the RAC nodes were not used for the LUNs, after restoring SnapCenter creates a new iGroup with all the initiators of all the RAC nodes.

* If there is any failure during prerestore activity on peer nodes, SnapCenter automatically rolls back the ASM disk group state as it was before performing restore on peer nodes on which prerestore operation was successful. Rollback is not supported for the primary and the peer node on which the operation failed. Before attempting another restore you must manually fix the issue on the peer node and bring the ASM disk group on the primary node back to mount state.
* If there is any failure during restore activity, then the restore operation fails and no roll back is performed. Before attempting another restore, you must manually fix the storage restore issue and bring the ASM disk group on the primary node back to mount state.
* If there is any failure during postrestore activity on any of the peer nodes, SnapCenter continues with the restore operation on the other peer nodes. You must manually fix the post restore issue on the peer node.
