---
permalink: protect-sco/reference_requirements_for_backing_up_an_oracle_database.html
sidebar: sidebar
keywords: requirements, prerequisites
summary: 'Before backing up an Oracle database, you should ensure that prerequisites are completed.'
---
= Requirements for backing up an Oracle database
:icons: font
:imagesdir: ../media/

[.lead]
Before backing up an Oracle database, you should ensure that prerequisites are completed.

* You must have created a resource group with a policy attached.
* If you want to back up a resource that has a SnapMirror relationship with a secondary storage, the ONTAP role assigned to the storage user should include the "`snapmirror all`" privilege. However, if you are using the "`vsadmin`" role, then the "`snapmirror all`" privilege is not required.
* You must have assigned the aggregate that is being used by the backup operation to thestorage virtual machine (SVM) used by the database.
* You should have verified that all data volumes and archive log volumes belonging to the database are protected if secondary protection is enabled for that database.
* You should have verified that the database that has files on the ASM disk groups should be in either "`MOUNT`" or "`OPEN`" state to verify its backups using the Oracle DBVERIFY utility.
* You should have verified that the volume mount point length does not exceed 240 characters.
* You should increase value of RESTTimeout to 86400000 seconds in _C:\Program Files\NetApp \SMCore\SMCoreServiceHost.exe.config_ file in the SnapCenter Server host, if the database being backed up is large (size in TBs).
+
While modifying the values ensure that there are no running jobs and restart the SnapCenter SMCore service after increasing the value.
