---
permalink: protect-sco/reference_types_of_backup_supported_for_oracle_databases.html
sidebar: sidebar
keywords: 
summary: 'Backup type specifies the type of backup that you want to create. SnapCenter supports online and offline backup types for Oracle databases.'
---
= Types of backup supported for Oracle databases
:icons: font
:imagesdir: ../media/

[.lead]
Backup type specifies the type of backup that you want to create. SnapCenter supports online and offline backup types for Oracle databases.

== Online backup

A backup that is created when the database is in the online state is called an online backup. Also called a hot backup, an online backup enables you to create a backup of the database without shutting it down.

As part of online backup, you can create a backup of the following files:

* Datafiles and control files only
* Archive log files only (the database is not brought to backup mode in this scenario)
* Full database that includes datafiles, control files, and archive log files

== Offline backup

A backup created when the database is either in a mounted or shutdown state is called an offline backup. An offline backup is also called a cold backup. You can include only datafiles and control files in offline backups. You can create either an offline mount or offline shutdown backup.

* When creating an offline mount backup, you must ensure that the database is in a mounted state.
+
If the database is in any other state, the backup operation fails.

* When creating an offline shutdown backup, the database can be in any state.
+
The database state is changed to the required state to create a backup. After creating the backup, the database state is reverted to the original state.
