---
permalink: protect-sco/reference_what_gets_imported_to_snapcenter.html
sidebar: sidebar
keywords: 
summary: 'You can import profiles, schedules, and operations performed using the profiles.'
---
= What gets imported to SnapCenter
:icons: font
:imagesdir: ../media/

[.lead]
You can import profiles, schedules, and operations performed using the profiles.

|===
| From SnapManager for Oracle and SnapManager for SAP| To SnapCenter
a|
Profiles without any operations and schedules
a|
A policy is created with default backup type as Online and backup scope as Full.
a|
Profiles with one or more operations
a|
Multiple policies are created based on a unique combination of a profile and operations performed using that profile. The policies created in SnapCenter contain the archive log pruning and retention details retrieved from the profile and corresponding operations.

a|
Profiles with Oracle Recovery Manager (RMAN) configuration
a|
Policies are created with the *Catalog backup with Oracle Recovery Manager* option enabled.If external RMAN cataloging was used in SnapManager, you must configure the RMAN catalog settings in SnapCenter. You can either select the existing credential or create a new credential.

If RMAN was configured through control file in SnapManager, then you do not have to configure RMAN in SnapCenter.

a|
Schedule attached to a profile
a|
A policy is created just for the schedule.
a|
Database
a|
A resource group is created for each database that is imported.In a Real Application Clusters (RAC) setup, the node on which you run the import tool becomes the preferred node after importing and the resource group is created for that node.

|===
*Note:* When a profile is imported, a verification policy is created along with the backup policy.

When SnapManager for Oracle and SnapManager for SAP profiles, schedules, and any operations performed using the profiles are imported to SnapCenter, the different parameters values are also imported.

|===
| SnapManager for Oracle and SnapManager for SAP parameter and values| SnapCenter parameter and values| Notes
a|
Backup Scope

* Full
* Data
* Log

a|
Backup Scope

* Full
* Data
* Log

a|
 
a|
Backup Mode

* Auto
* Online
* Offline

a|
Backup Type

* Online
* Offline Shutdown

a|
If the backup mode is Auto, then the import tool checks the database state when the operation was performed, and appropriately sets the backup type as either Online or Offline Shutdown.
a|
Retention

* Days
* Counts

a|
Retention

* Days

a|
SnapManager for Oracle and SnapManager for SAP uses both Days and Counts to set the retention. In SnapCenter, there is either Days _OR_ Counts. So, the retention is set with respect to days as the days get preference over counts in SnapManager for Oracle and SnapManager for SAP.
a|
Pruning for Schedules

* All
* system change number (SCN)
* Date
* Logs created before specified hours, days, weeks, and months

a|
Pruning for Schedules

* All
* Logs created before specified hours and days

a|
SnapCenter does not support pruning based on SCN, Date, weeks, and months.
a|
Notification

* Emails sent only for successful operations
* Emails sent only for failed operations
* Emails sent for both success and failed operations

a|
Notification

* Always
* On failure
* Always

a|
The email notifications are imported. However, you must manually update the SMTP server using the SnapCenter GUI. The subject of the email is left blank for you to configure.

|===
