---
permalink: protect-sco/reference_requirements_for_cloning_an_oracle_database.html
sidebar: sidebar
keywords:
summary: 'Before cloning an Oracle database, you should ensure that prerequisites are completed.'
---
= Requirements for cloning an Oracle database
:icons: font
:imagesdir: ../media/

[.lead]
Before cloning an Oracle database, you should ensure that prerequisites are completed.

* You should have created a backup of the database using SnapCenter.
+
You should have successfully created online data and log backups or offline (mount or shutdown) backups for the cloning operation to succeed.

* If you want to customize the control file or redo log file paths, you should have preprovisioned the required file system or Automatic Storage Management (ASM) disk group.
+
By default, redo log and control files of the cloned database are created on the ASM disk group or the file system provisioned by SnapCenter for the data files of the clone database.

* If you are using ASM over NFS, you should add _/var/opt/snapcenter/scu/clones/*/*_ to the existing path defined in the asm_diskstring parameter.
* If you are using ASMFD or ASMLIB, you should use _AFD:*_ and _ORCL:*_ in the asm_diskstring parameter.

NOTE: For information on how to edit the asm_diskstring parameter, see https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/Disk_paths_are_not_added_to_the_asm_diskstring_database_parameter[How to add disk paths to asm_diskstring]

* If you are creating the clone on an alternate host, the alternate host should meet the following requirements:
 ** SnapCenter Plug-in for Oracle Database should be installed on the alternate host.
 ** The clone host should be able to discover LUNs from primary or secondary storage.
  *** If you are cloning from primary storage or secondary (Vault or Mirror) storage to an alternate host, then make sure that an iSCSI session is either established between the secondary storage and the alternate host, or zoned properly for FC.
   **** https://library.netapp.com/ecm/ecm_download_file/ECMLP2547936[Linux Host Utilities Installation and Setup Guide]
   **** https://library.netapp.com/ecm/ecm_download_file/ECMP1119223[AIX Host Utilities Installation and Setup Guide]
  *** If you are cloning from Vault or Mirror storage to the same host, then make sure that an iSCSI session is either established between the Vault or Mirror storage and the host, or zoned properly for FC.
  *** If you are cloning in a virtualized environment, ensure that an iSCSI session is either established between the primary or secondary storage and the ESX server hosting the alternate host, or zoned properly for FC.
 ** If the source database is an ASM database:
  *** The ASM instance should be up and running on the host where the clone will be performed.
  *** The ASM disk group should be provisioned prior to the clone operation if you want to place archive log files of the cloned database in a dedicated ASM disk group.
  *** The name of the data disk group can be configured, but ensure that the name is not used by any other ASM disk group on the host where the clone will be performed.
+
Data files residing on the ASM disk group are provisioned as part of the SnapCenter clone workflow.
* The protection type for the data LUN and the log LUN, such as mirror, vault, or mirror-vault, should be the same to discover secondary locators during cloning to an alternate host using log backups.
* You should set the value of exclude_seed_cdb_view to FALSE in the source database parameter file to retrieve seed PDB related information for cloning a backup of 12__c__ database.
+
The seed PDB is a system-supplied template that the CDB can use to create PDBs. The seed PDB is named PDB$SEED. For information about PDB$SEED, see the Oracle Doc ID 1940806.1.
+
NOTE: You should set the value before backing up 12__c__ database.

* SnapCenter supports backup of file systems that are managed by the autofs subsystem. If you are cloning the database, ensure that data mount points are not under the root of the autofs mount point because the root user of the plug-in host does not have permission to create directories under the root of the autofs mount point.
+
If control and redo log files are under data mount point, you should modify the control file path, and then redo log file path accordingly.
+
NOTE: You can manually register the new cloned mount points with the autofs subsystem. The new cloned mount points will not be registered automatically.

* If you have a TDE (auto login) and want to clone the database on the same or alternate host, you should copy wallet (key files) under _/etc/ORACLE/WALLET/$ORACLE_SID_ from the source database to the cloned database.
* You should set the value of use_lvmetad = 0 in _/etc/lvm/lvm.conf_ and stop the lvm2-lvmetad service to successfully perform cloning in storage area network (SAN) environments on Oracle Linux 7 or later or Red Hat Enterprise Linux (RHEL) 7 or later.
* You should install the 13366202 Oracle patch if you are using Oracle database 11.2.0.3 or later and the database ID for the auxiliary instance is changed using an NID script.
* You should ensure that the aggregates hosting the volumes should be in the assigned aggregates list of the storage virtual machine (SVM).
