---
permalink: protect-sco/reference_supported_oracle_database_configurations_for_backups.html
sidebar: sidebar
keywords: 
summary: 'SnapCenter supports backup of different Oracle database configurations.'
---
= Supported Oracle database configurations for backups
:icons: font
:imagesdir: ../media/

[.lead]
SnapCenter supports backup of different Oracle database configurations.

* Oracle Standalone
* Oracle Real Application Clusters (RAC)
* Oracle Standalone Legacy
* Oracle Standalone Container Database (CDB)
* Oracle Data Guard standby
+
You can create only offline (mount or shutdown) backups of Data Guard standby databases. Archive log-only backup or full backup is not supported.

* Oracle Active Data Guard standby
+
You can create data only online backups of Active Data Guard standby databases. Archive log-only backup or full backup is not supported.

* Automatic Storage Management (ASM)
 ** ASM standalone and ASM RAC on Virtual Machine Disk (VMDK)
+
NOTE: Among all the restore methods supported for Oracle databases, you can perform only connect-and-copy restore of ASM RAC databases on VMDK.

 ** ASM standalone and ASM RAC on Raw device mapping (RDM)
You can perform backup, restore, and clone operations on Oracle databases on ASM, with or without ASMLib.
* Oracle ASM Filter Driver (ASMFD)

NOTE: PDB migration and PDB cloning operations are not supported.

For the latest information about supported versions, see the NetApp Interoperability Matrix Tool (IMT).

http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]

NOTE: Before creating a backup of Data Guard standby or Active Data Guard standby database, the managed recovery process (MRP) is stopped and once the backup is created, MRP is started.
