---
permalink: protect-sco/reference_limitations_related_to_restore_and_recovery_of_oracle_databases.html
sidebar: sidebar
keywords:
summary: 'Before you perform restore and recovery operations, you must be aware of the limitations.'
---
= Limitations related to restore and recovery of Oracle databases
:icons: font
:imagesdir: ../media/

[.lead]
Before you perform restore and recovery operations, you must be aware of the limitations.

If you are using any version of Oracle from 11.2.0.4 to 12.1.0.1, the restore operation will be in hung state when you run the renamedg command. You can apply the Oracle patch 19544733 to fix this issue.

The following restore and recovery operations are not supported:

* Restore and recovery of tablespaces of the root container database (CDB)
* Restore of temporary tablespaces and temporary tablespaces associated with PDBs
* Restore and recovery of tablespaces from multiple PDBs simultaneously
* Restore of log backups
* Restore of backups to a different location
* Restore of redo log files in any configuration other than Data Guard standby or Active Data Guard standby databases
* Restore of SPFILE and Password file
* When you perform a restore operation on a database that was re-created using the preexisting database name on the same host, was managed by SnapCenter, and had valid backups, the restore operation overwrites the newly created database files even though the DBIDs are different.
+
This can be avoided by performing either of following actions:

 ** Discover the SnapCenter resources after the database is re-created
 ** Create a backup of the re-created database

== Limitations related to point-in-time recovery of tablespaces

* Point-in-time recovery (PITR) of SYSTEM, SYSAUX, and UNDO tablespaces is not supported
* PITR of tablespaces cannot be performed along with other types of restore
* If a tablespace is renamed and you want to recover it to a point before it was renamed, you should specify the earlier name of the tablespace
* If constraints for the tables in one tablespace are contained in another tablespace, you should recover both the tablespaces
* If a table and its indexes are stored in different tablespaces, then the indexes should be dropped before performing PITR
* PITR cannot be used to recover the current default tablespace
* PITR cannot be used to recover tablespaces containing any of the following objects:
 ** Objects with underlying objects (such as materialized views) or contained objects (such as partitioned tables) unless all the underlying or contained objects are in the recovery set
+
Additionally, if the partitions of a partitioned table are stored in different tablespaces, then you should either drop the table before performing PITR or move all the partitions to the same tablespace before performing PITR.

 ** Undo or rollback segments
 ** Oracle 8 compatible advanced queues with multiple recipients
 ** Objects owned by the SYS user
+
Examples of these types of objects are PL/SQL, Java classes, call out programs, views, synonyms, users, privileges, dimensions, directories, and sequences.
