---
permalink: protect-sco/reference_storage_types_supported_by_snapcenter_plug_in_for_oracle_database.html
sidebar: sidebar
keywords: storage types, iSCSI, NFS, RDM, VMDK, NFS, LVM, ASM, SAN filesystem
summary: 'SnapCenter supports a wide range of storage types on both physical and virtual machines. You must verify the support for your storage type before installing the SnapCenter Plug-ins Package for Linux or SnapCenter Plug-ins Package for AIX.'
---
= Storage types supported by Plug-in for Oracle Database
:icons: font
:imagesdir: ../media/

[.lead]
SnapCenter supports a wide range of storage types on both physical and virtual machines. You must verify the support for your storage type before installing the SnapCenter Plug-ins Package for Linux or SnapCenter Plug-ins Package for AIX.

SnapCenter does not support storage provisioning for Linux and AIX.

== Storage types supported on Linux

The following table lists the storage types supported on Linux.

|===
| Machine | Storage type

a|
Physical server
a|
* FC-connected LUNs
* iSCSI-connected LUNs
* NFS-connected volumes
a|
VMware ESXi
a|
* RDM LUNs connected by an FC or iSCSI ESXi HBAScanning of host bus adapters (HBAs) might take long time to complete because SnapCenter scans all the host bus adaptors present in the host.
+
You can edit the *LinuxConfig.pm* file located at _/opt/NetApp/snapcenter/spl/plugins/scu/scucore/modules/SCU/Config_ to set the value of the *SCSI_HOSTS_OPTIMIZED_RESCAN* parameter to 1 to rescan only those HBAs that are listed in HBA_DRIVER_NAMES.
* iSCSI LUNs connected directly to the guest system by the iSCSI initiator
* VMDKs on VMFS or NFS datastores
* NFS volumes connected directly to the guest system
|===

== Storage types supported on AIX

The following table lists the storage types supported on AIX.

|===
| Machine | Storage type

a|
Physical server
a|
* FC-connected and iSCSI-connected LUNs.
+
In a SAN environment, ASM, LVM, and SAN file systems are supported.
// [SD]: Updated for BURT 1391312 in 4.5
+
NOTE: NFS on AIX and filesystem is not supported.

// [SD]: Updated for BURT 1391312 in 4.5

* Enhanced Journaled File System (JFS2)
// [SD]: Included for BURT 1391312 in 4.5
+
Supports inline logging on SAN filesystems and LVM layout.
|===

The https://imt.netapp.com/matrix/imt.jsp?components=103047;&solution=1257&isHWU&src=IMT[NetApp Interoperability Matrix Tool] contains the latest information about the suported versions.
