---
permalink: protect-sco/reference_requirements_for_restoring_an_oracle_database.html
sidebar: sidebar
keywords:
summary: 'Before restoring an Oracle database, you should ensure that prerequisites are completed.'
---
= Requirements for restoring an Oracle database
:icons: font
:imagesdir: ../media/

[.lead]
Before restoring an Oracle database, you should ensure that prerequisites are completed.

* You should have defined your restore and recovery strategy.
* The SnapCenter administrator should have assigned you the storage virtual machines (SVMs) for both the source volumes and destination volumes if you are replicating Snapshot copies to a mirror or vault.
* If archive logs are pruned as part of backup, you should have manually mounted the required archive log backups.
* If you want to restore Oracle databases that are residing on a Virtual Machine Disk (VMDK), you should ensure that the guest machine has the required number of free slots for allocating the cloned VMDKs.
* You should ensure that all data volumes and archive log volumes belonging to the database are protected if secondary protection is enabled for that database.
* You should ensure that the RAC One Node database is in "nomount" state to perform control file or full database restore.
* If you have an ASM database instance in NFS environment, you should add the ASM disk path _/var/opt/snapcenter/scu/clones/*/*_ to the existing path defined in the asm_diskstring parameter to successfully mount the ASM log backups as part of recovery operation.
* In the asm_diskstring parameter, you should configure _AFD:*_ if you are using ASMFD or configure _ORCL:*_ if you are using ASMLIB.
+
NOTE: For information on how to edit the asm_diskstring parameter, see https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/Disk_paths_are_not_added_to_the_asm_diskstring_database_parameter[How to add disk paths to asm_diskstring^]

* You should configure the static listener in the *listener.ora* file available at _$ORACLE_HOME/network/admin_ for non ASM databases and _$GRID_HOME/network/admin_ for ASM databases if you have disabled OS authentication and enabled Oracle database authentication for an Oracle database, and want to restore the datafiles and control files of that database.
* You should increase value of SCORestoreTimeout parameter by running the Set- SmConfigSettings command if the database size is in terabytes (TB).
* You should ensure that all the licenses required for vCenter are installed and up to date.
+
If the licenses are not installed or up to date, a warning message is displayed. If you ignore the warning and proceed, restore from RDM fails.
