---
permalink: protect-sco/reference_how_snapcenter_discovers_oracle_databases.html
sidebar: sidebar
keywords:
summary: '“Resources” are Oracle databases on the host that are maintained by SnapCenter. You can add these databases to resource groups to perform data protection operations after you discover the databases that are available. You should be aware of the process that SnapCenter follows to discover different types and versions of Oracle databases.'
---
= How SnapCenter discovers Oracle databases
:icons: font
:imagesdir: ../media/

[.lead]
"`Resources`" are Oracle databases on the host that are maintained by SnapCenter. You can add these databases to resource groups to perform data protection operations after you discover the databases that are available. You should be aware of the process that SnapCenter follows to discover different types and versions of Oracle databases.

|===
| For Oracle versions 11__g__ to 12__c__R1 | For Oracle versions 12__c__R2 to 18__c__

a|
*RAC database*: The RAC databases are discovered only on the basis of /etc/oratab entries.

You should have the database entries in the /etc/oratab file.

a|
*RAC database*: The RAC databases are discovered using the srvctl config command.
a|
*Standalone*: The standalone databases are discovered only on the basis of /etc/oratab entries.

You should have the database entries in the /etc/oratab file.

a|
*Standalone*: The standalone databases are discovered based on the entries in the /etc/oratab file and the output of the srvctl config command.
a|
*ASM*: The ASM instance entry should be available in the /etc/oratab file.
a|
*ASM*: The ASM instance entry need not be in the /etc/oratab file.
a|
*RAC One Node*: The RAC One Node databases are discovered only on the basis of /etc/oratab entries.

The databases should be either in `nomount`, `mount`, or `open` state.You should have the database entries in the /etc/oratab file.

The RAC One Node database status will be marked as renamed or deleted if the database is already discovered and backups are associated with the database.

You should perform the following steps if the database is relocated:

. Manually add the relocated database entry in the /etc/oratab file on the failed-over RAC node.
. Manually refresh the resources.
. Select the RAC One Node database from the resource page, and then click *Database Settings*.
. Configure the database to set the preferred cluster nodes to the RAC node currently hosting the database.
. Perform the SnapCenter operations.

//Included this for the BURT 1391253 for 4.5
NOTE: If you have relocated a database from one node to another node and if the oratab entry in the earlier node is not deleted, you should manually delete the oratab entry to avoid the same database being displayed twice.

a|
*RAC One Node*: The RAC One Node databases are discovered using the srvctl config command only.

The databases should be either in `nomount`, `mount`, or `open` state.The RAC One Node database status will be marked as renamed or deleted if the database is already discovered and backups are associated with the database.

You should perform the following steps if the database is relocated:

. Manually refresh the resources.
. Select the RAC One Node database from the resource page, and then click**Database Settings**.
. Configure the database to set the preferred cluster nodes to the RAC node currently hosting the database.
. Perform the SnapCenter operations.

|===
*Note:*

* If there are any Oracle 12__c__R2 and 18__c__ database entries in the /etc/oratab file and the same database is registered with the srvctl config command, SnapCenter will eliminate the duplicate database entries.
* If there are stale database entries, the database will be discovered but the database will be unreachable and the status will be offline.
