---
permalink: protect-sco/task_restore_and_recover_oracle_databases_using_unix_commands.html
sidebar: sidebar
keywords: 
summary: 'The restore and recovery workflow includes planning, performing the restore and recovery operations, and monitoring the operations.'
---
= Restore and recover Oracle databases using UNIX commands
:icons: font
:imagesdir: ../media/

[.lead]
The restore and recovery workflow includes planning, performing the restore and recovery operations, and monitoring the operations.

* You should have established the connection session with the SnapCenter Server.

You should execute the following commands to establish the connection with the SnapCenter Server, list the backups and retrieve its information, and restore the backup.

The information regarding the parameters that can be used with the command and their descriptions can be obtained by running helpcommand_name. Alternatively, you can also refer to the _Command Reference Guide_.

https://library.netapp.com/ecm/ecm_download_file/ECMLP2874313[SnapCenter Software 4.4 Command Reference Guide]

. Initiate a connection session with the SnapCenter Server for a specified user: Open-SmConnection
. Retrieve the information about the backups that you want to restore: Get-SmBackup
. Retrieve the detailed information about the specified backup: Get-SmBackupDetails
+
This command retrieves the detailed information about the backup of a specified resource with a given backup ID. The information includes database name, version, home, start and end SCN, tablespaces, pluggable databases, and its tablespaces.

. Restore data from the backup: Restore-SmBackup
