---
permalink: protect-sco/task_set_up_credentials_for_installing_the_plug_in_package_for_linux_or_aix.html
sidebar: sidebar
keywords: credentials, authenticate, domain administrator, local administrator, workgroup, sudo, non-root user, root user
summary: 'SnapCenter uses credentials to authenticate users for SnapCenter operations. You should create credentials for installing the plug-in package on Linux or AIX hosts.'
---
= Set up credentials for installing Plug-ins Package for Linux or AIX
:icons: font
:imagesdir: ../media/

[.lead]
SnapCenter uses credentials to authenticate users for SnapCenter operations. You should create credentials for installing the plug-in package on Linux or AIX hosts.

*About this task*

The credentials are created either for the root user or for a non-root user who has sudo privileges to install and start the plug-in process.

For information, see link:../protect-sco/reference_host_requirements_for_installing_the_snapcenter_plug_in_package_for_linux.html#configuring-sudo-privileges-for-non-root-users-for-linux-plug-in-host[Configure sudo privileges for Linux host^] or link:../protect-sco/reference_host_requirements_for_installing_the_snapcenter_plug_ins_package_for_aix.html#configure-sudo-privileges-for-non-root-user-for-aix-plug-in-host[Configure sudo privileges for AIX host^].

|===
*Best Practice:* Although you are allowed to create credentials after deploying hosts and installing plug-ins, the best practice is to create credentials after you add SVMs, before you deploy hosts and install plug-ins.
|===

*Steps*

. In the left navigation pane, click *Settings*.
. In the Settings page, click *Credential*.
. Click *New*.
. In the Credential page, enter the credential information:
+
|===
| For this field...| Do this...

a|
Credential name
a|
Enter a name for the credentials.
a|
User name/Password
a|
Enter the user name and password that are to be used for authentication.

 ** Domain administrator
+
Specify the domain administrator on the system on which you are installing the SnapCenter plug-in. Valid formats for the Username field are:

  *** _NetBIOS\UserName_
  *** _Domain FQDN\UserName_

 ** Local administrator (for workgroups only)
+
For systems that belong to a workgroup, specify the built-in local administrator on the system on which you are installing the SnapCenter plug-in. You can specify a local user account that belongs to the local administrators group if the user account has elevated privileges or the User Access control feature is disabled on the host system. The valid format for the Username field is: _UserName_

a|
Authentication Mode
a|
Select the authentication mode that you want to use.

Depending on the operating system of the plug-in host, select either Linux or AIX.
a|
Use sudo privileges
a|
Select the *Use sudo privileges* check box if you are creating credentials for a non-root user.
|===

. Click *OK*.

After you finish setting up the credentials, you might want to assign credential maintenance to a user or group of users on the My SnapCenter Assets page.
