---
permalink: protect-sco/task_installing_snapcenter_plug_ins_package_for_linux_or_aix_on_cluster_host.html
sidebar: sidebar
keywords: 
summary: 'You should install SnapCenter Plug-ins Package for Linux or SnapCenter Plug-ins Package for AIX on both the nodes of the cluster host.'
---
= Installing SnapCenter Plug-ins Package for Linux or AIX on cluster host
:icons: font
:imagesdir: ../media/

[.lead]
You should install SnapCenter Plug-ins Package for Linux or SnapCenter Plug-ins Package for AIX on both the nodes of the cluster host.

Each of the nodes of the cluster host has two IPs. One of the IPs will be the public IP of the respective nodes and the second IP will be the cluster IP that is shared between both the nodes.

. Install SnapCenter Plug-ins Package for Linux or SnapCenter Plug-ins Package for AIX on both the nodes of the cluster host.
+
See _Installing the SnapCenter Plug-ins Package for Linux or AIX interactively_.

. Validate that the correct values for SNAPCENTER_SERVER_HOST, SPL_PORT, SNAPCENTER_SERVER_PORT, and SPL_ENABLED_PLUGINS parameters are specified in the spl.properties file located at /var/opt/snapcenter/spl/etc/.
+
If SPL_ENABLED_PLUGINS is not specified in spl.properties, you can add it and assign the value SCO,SCU.

. On the SnapCenter Server host, establish a session using the Open-SmConnection cmdlet, and then enter your credentials.
. In each of the nodes, set the preferred IPs of the node using the Set-PreferredHostIPsInStorageExportPolicy sccli command and the required parameters.
. In the SnapCenter Server host, add an entry for the cluster IP and corresponding DNS name in C:\Windows\System32\drivers\etc\hosts.
. Add the node to the SnapCenter Server using the Add-SmHost cmdlet by specifying the cluster IP for the host name.
+
The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running Get-Helpcommand_name. Alternatively, you can also refer to the _Cmdlet Reference Guide_.
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2874310[SnapCenter Software 4.4 Cmdlet Reference Guide]

Discover the Oracle database on node 1 (assuming the cluster IP is hosted on node 1) and create a backup of the database. If a fail over happens, you can use the backup created on node 1 to restore the database on node 2. You can also use the backup created on node 1 to create a clone on node 2.

NOTE: There will be stale volumes, directories, and lock file if the fail over happens while any other SnapCenter operations are running.
