---
permalink: protect-sco/task_installing_the_snapcenter_plug_ins_package_for_linux_interactively.html
sidebar: sidebar
keywords: 
summary: 'You can use the installation wizard to install the SnapCenter Plug-ins Package for Linux interactively on a Linux host.'
---
= Installing the SnapCenter Plug-ins Package for Linux interactively
:icons: font
:imagesdir: ../media/

[.lead]
You can use the installation wizard to install the SnapCenter Plug-ins Package for Linux interactively on a Linux host.

* You should review the prerequisites for installing the plug-ins package.
* You should set the DISPLAY environment variable to specify the IP address and port number of the Linux host where you want to launch the wizard.

. Download the SnapCenter Plug-ins Package for Linux from the SnapCenter Server installation location.
+
The default installation path is C:\ProgramData\NetApp\SnapCenter\Package Repository. This path is accessible from the host where the SnapCenter Server is installed.

. Copy the installation file to the host on which you want to install the plug-in.
. From the command prompt, navigate to the directory where you downloaded the installation file.
. Run `./SnapCenter_linux_host_plugin.bin –i swing`
. Follow the on-screen prompts in the wizard to install the plug-ins package.
. Click *Finish* to complete the installation.
