---
permalink: protect-sco/task_installing_the_snapcenter_plug_ins_package_for_linux_in_silent_or_console_mode.html
sidebar: sidebar
keywords: 
summary: 'You can install the SnapCenter Plug-ins Package for Linux either in console mode or in silent mode by using the command-line interface \(CLI\).'
---
= Installing the SnapCenter Plug-ins Package for Linux in silent mode or console mode
:icons: font
:imagesdir: ../media/

[.lead]
You can install the SnapCenter Plug-ins Package for Linux either in console mode or in silent mode by using the command-line interface (CLI).

* You should review the prerequisites for installing the plug-ins package.
* You should ensure that the DISPLAY environment variable is not set.
+
If the DISPLAY environment variable is set, you should run unset DISPLAY, and then try to manually install the plug-in.

You are required to provide the necessary installation information while installing in console mode, whereas in silent mode installation you do not have to provide any installation information.

. Download the SnapCenter Plug-ins Package for Linux from the SnapCenter Server installation location.
+
The default installation path is C:\ProgramData\NetApp\SnapCenter\Package Repository. This path is accessible from the host where the SnapCenter Server is installed.

. From the command prompt, navigate to the directory where you downloaded the installation file.
. Depending on your preferred mode of installation, perform one of the following step.
+
|===
| Install mode| Steps
a|
*Console mode*
a|

 .. Run `./SnapCenter_linux_host_plugin.bin –i console`
 .. Follow the on-screen prompts to complete the installation.

a|
*Silent mode*
a|
Run `./SnapCenter_linux_host_plugin.bin-i silent-DPORT=8145-DSERVER_IP=SnapCenter_Server_FQDN-DSERVER_HTTPS_PORT=SnapCenter_Server_Port-DUSER_INSTALL_DIR==/opt/custom_path`
|===

. Edit the spl.properties file located at /var/opt/snapcenter/spl/etc/ to add SPL_ENABLED_PLUGINS=SCO,SCU, and then restart the SnapCenter Plug-in Loader service.

The installation of the plug-ins package registers the plug-ins on the host and not on the SnapCenter Server. You should register the plug-ins on the SnapCenter Server by adding the host using the SnapCenter GUI or PowerShell cmdlet. After the host is added, the installed plug-ins are automatically discovered.
