---
permalink: protect-sco/task_install_snapcenter_plug_ins_package_for_linux_or_aix_on_multiple_remote_hosts_using_cmdlets.html
sidebar: sidebar
keywords: credentials
summary: 'You should use the Install-SmHostPackage PowerShell cmdlet to install the SnapCenter Plug-ins Package for Linux or SnapCenter Plug-ins Package for AIX on multiple hosts.'
---
= Install SnapCenter Plug-ins Package for Linux or AIX on multiple remote hosts using cmdlets
:icons: font
:imagesdir: ../media/

[.lead]
You should use the Install-SmHostPackage PowerShell cmdlet to install the SnapCenter Plug-ins Package for Linux or SnapCenter Plug-ins Package for AIX on multiple hosts.

You should be logged in to SnapCenter as a domain user with local administrator rights on each host on which you want to install the plug-in package.

. Launch PowerShell.
. On the SnapCenter Server host, establish a session using the Open-SmConnection cmdlet, and then enter your credentials.
. Install the SnapCenter Plug-ins Package for Linux or SnapCenter Plug-ins Package for AIX using the Install-SmHostPackage cmdlet and the required parameters.
+
The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running Get-Helpcommand_name. Alternatively, you can also refer to the _Cmdlet Reference Guide_.
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2874310[SnapCenter Software 4.4 Cmdlet Reference Guide]
+
You use the -skipprecheck option when you have already installed the plug-ins manually and do not want to validate whether the host meets the requirements to install the plug-in.
+
NOTE: The precheck script does not validate the plug-in port firewall status if it is specified in the firewall reject rules.

. Enter your credentials for remote installation.
