---
permalink: protect-sce/concept_snapcenter_plug_in_for_exchange_server_overview.html
sidebar: sidebar
keywords: SnapCenter Plug-in for Exchange Server
summary: 'The SnapCenter Plug-in for Microsoft Exchange Server is a host-side component of the NetAppSnapCenter Software that enables application-aware data protection management of Exchange databases. The Plug-in for Exchange automates the backup and restore of Exchange databases in your SnapCenter environment.'
---
= SnapCenter Plug-in for Microsoft Exchange Server overview
:icons: font
:imagesdir: ../media/

[.lead]
The SnapCenter Plug-in for Microsoft Exchange Server is a host-side component of the NetApp SnapCenter Software that enables application-aware data protection management of Exchange databases. The Plug-in for Exchange automates the backup and restore of Exchange databases in your SnapCenter environment.

When the Plug-in for Exchange is installed, you can use SnapCenter with NetApp SnapMirror technology to create mirror copies of backup sets on another volume and with NetApp SnapVault technology to perform disk-to-disk backup replication for standards compliance or archival purposes.

//Included in 4.5 as per input from Subhash and Manoah
If you want to restore and recover mails or mailbox instead of the complete Exchange Database, you can use the Single Mailbox Recovery (SMBR) software.

== What you can do with SnapCenter Plug-in for Microsoft Exchange Server

You can use the Plug-in for Exchange to back up and restore Exchange Server databases.

* View and manage an active inventory of Exchange Database Availability Groups (DAGs), databases, and replica sets
* Define policies that provide the protection settings for backup automation
* Assign policies to resource groups
* Protect individual DAGs and databases
* Back up primary and secondary Exchange mailbox databases
* Restore databases from primary and secondary backups

== Storage types supported by SnapCenter Plug-in for Microsoft Windows and for Microsoft Exchange Server

SnapCenter supports a wide range of storage types on both physical machines and virtual machines. You must verify whether support is available for your storage type before installing the package for your host.

SnapCenter provisioning and data protection support is available on Windows Server. For the latest information about supported versions, see the http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool^].


|===
| Machine| Storage type| Provision using| Support notes

a|
Physical server
a|
FC-connected LUNs
a|
SnapCenter graphical user interface (GUI) or PowerShell cmdlets
a|

a|
Physical server
a|
iSCSI-connected LUNs
a|
SnapCenter GUI or PowerShell cmdlets
a|

a|
VMware VM
a|
RDM LUNs connected by an FC or iSCSI HBA
a|
PowerShell cmdlets
a|
Physical compatibility only

NOTE: VMDKs are not supported.

a|
VMware VM
a|
iSCSI LUNs connected directly to the guest system by the iSCSI initiator
a|
SnapCenter GUI or PowerShell cmdlets
a|

NOTE: VMDKs are not supported.

a|
Hyper-V VM
a|
Virtual FC (vFC) LUNs connected by a virtual Fibre Channel Switch
a|
SnapCenter GUI or PowerShell cmdlets
a|
You must use Hyper-V Manager to provision Virtual FC (vFC) LUNs connected by a virtual Fibre Channel Switch.

NOTE: Hyper-V pass through disks and backing up databases on VHD(x) that are provisioned on NetApp storage are not supported.

a|
Hyper-V VM
a|
iSCSI LUNs connected directly to the guest system by the iSCSI initiator
a|
SnapCenter GUI or PowerShell cmdlets
a|

NOTE: Hyper-V pass through disks and backing up databases on VHD(x) that are provisioned on NetApp storage are not supported.

|===

== Minimum ONTAP privileges required

include::../_include/reuse_concept_minimum_privileges_required_for_sap_hana_and_exchange_plug_in.adoc[]

== Prepare storage systems for SnapMirror and SnapVault replication

include::../_include/reuse_reference_prepare_storage_systems_for_snapmirror_and_snapvault_replication.adoc[]

== Define a backup strategy for Exchange Server resources

Defining a backup strategy before you create your backup jobs helps ensure that you have the backups that you require to successfully restore your databases. Your Service Level Agreement (SLA), Recovery Time Objective (RTO), and Recovery Point Objective (RPO) largely determine your backup strategy.

An SLA defines the level of service expected and addresses many service-related issues, including the availability and performance of service. The RTO is the time by when a business process must be restored after a disruption in service. An RPO defines the strategy for the age of the files that must be recovered from backup storage for regular operations to resume after a failure. The SLA, RTO, and RPO contribute to the backup strategy.

=== Types of backups supported for Exchange database

Backing up Exchange mailboxes using SnapCenter requires that you choose the resource type, such as databases and Database Availability Groups (DAG). Snapshot copy technology is leveraged to create online, read-only copies of the volumes on which the resources reside.

|===
| Backup type| Description

a|
Full and log backup
a|
Backs up the databases and all transaction logs, including the truncated logs.

After a full backup is complete, the Exchange Server truncates the transaction logs that are already committed to the database.

Typically, you should choose this option. However, if your backup time is short, you can choose not to run a transaction log backup with full backup.

a|
Full backup
a|
Backs up databases and transaction logs.

The truncated transaction logs are not backed up.

a|
Log backup
a|
Backs up all the transaction logs.

The truncated logs that are already committed to the database are not backed up. If you schedule frequent transaction log backups between full database backups, you can choose granular recovery points.

|===

=== Backup schedules for database plug-ins

include::../_include/reuse_concept_backup_schedules_for_database_plug_ins.adoc[]

=== Number of backup jobs needed for databases

Factors that determine the number of backup jobs that you need include the size of the resource, the number of volumes used, the rate of change of the resource, and your Service Level Agreement (SLA).

=== Backup naming conventions

include::../_include/reuse_concept_backup_naming_conventions.adoc[]

=== Backup retention options

include::../_include/reuse_concept_backup_retention_options.adoc[]

=== How long to retain transaction log backups on the source storage volume for Exchange Server

SnapCenter Plug-in for Microsoft Exchange Server needs transaction log backups to perform up-to-the-minute restore operations, which restore your database to a time between two full backups.

For example, if Plug-in for Exchange took a full plus transaction log backup at 8:00 a.m. and another full plus transaction log backup at 5:00 p.m., it could use the latest transaction log backup to restore the database to any time between 8:00 a.m. and 5:00 p.m. If transaction logs are not available, Plug-in for Exchange can perform point-in-time restore operations only, which restore a database to the time that Plug-in for Exchange completed a full backup.

Typically, you require up-to-the-minute restore operations for only a day or two. By default, SnapCenter retains a minimum of two days.

== Define a restore strategy for Exchange databases

Defining a restoration strategy for Exchange Server enables you to restore your database successfully.

=== Sources for a restore operation in Exchange Server
You can restore an Exchange Server database from a backup copy on primary storage.

You can restore databases from primary storage only.

=== Types of restore operations supported for Exchange Server
You can use SnapCenter to perform different types of restore operations on Exchange resources.

* Restore up-to-the-minute
* Restore to a previous point in time

=== Restore up to the minute

In an up-to-the-minute restore operation, databases are recovered up to the point of failure. SnapCenter accomplishes this by performing the following sequence:

. Restores the databases from the full database backup that you select.
. Applies all the transaction logs that were backed up, as well as any new logs that were created since the most recent backup.
+
Transaction logs are moved ahead and applied to any selected databases.
+
Exchange creates a new log chain after a restore completes.
+
|===
*Best Practice:* It is recommended that you perform a new full and log backup after a restore completes.
|===
An up-to-the-minute restore operation requires a contiguous set of transaction logs.
+
After you perform an up-to-the-minute restore, the backup you used for the restore is available only for point-in-time restore operations.
+
If you do not need to retain up-to-the-minute restore capability for all backups, you can configure your system's transaction log backup retention through the backup policies.

=== Restore to a previous point in time

In a point-in-time restore operation, databases are restored only to a specific time from the past. A point-in-time restore operation occurs in the following restore situations:

* The database is restored to a given time in a backed-up transaction log.
* The database is restored, and only a subset of backed-up transaction logs are applied to it.
