---
permalink: protect-sce/concept_snapcenter_plug_in_for_exchange_server_overview.html
sidebar: sidebar
keywords: SnapCenter Plug-in for Exchange Server
summary: 'The SnapCenter Plug-in for Microsoft Exchange Server is a host-side component of the NetAppSnapCenter Software that enables application-aware data protection management of Exchange databases. The Plug-in for Exchange automates the backup and restore of Exchange databases in your SnapCenter environment.'
---
= SnapCenter Plug-in for Microsoft Exchange Server overview
:icons: font
:imagesdir: ../media/

[.lead]
The SnapCenter Plug-in for Microsoft Exchange Server is a host-side component of the NetApp SnapCenter Software that enables application-aware data protection management of Exchange databases. The Plug-in for Exchange automates the backup and restore of Exchange databases in your SnapCenter environment.

When the Plug-in for Exchange is installed, you can use SnapCenter with NetApp SnapMirror technology to create mirror copies of backup sets on another volume and with NetApp SnapVault technology to perform disk-to-disk backup replication for standards compliance or archival purposes.

//Included in 4.5 as per input from Subhash and Manoah
If you want to restore and recover mails or mailbox instead of the complete Exchange Database, you can use the Single Mailbox Recovery (SMBR) software.
