---
permalink: protect-sce/reference_granular_recovery_of_mails_and_mailbox.html
sidebar: sidebar
keywords: SMBR, Single Mailbox recovery, Exchange database
summary: 'Single Mailbox Recovery (SMBR) software allows you to restore and recover mails or mailbox instead of the complete Exchange Database.'
---
= Granular recovery of mails and mailbox
:icons: font
:imagesdir: ../media/

[.lead]
Single Mailbox Recovery (SMBR) software allows you to restore and recover mails or mailbox instead of the complete Exchange Database.

Restoring complete database just to recover a single mail will consume lot of time and resource. SMBR helps in quickly recovering the mails by creating clone copy of the Snapshot and then using Microsoft API’s to mount the mailbox in SMBR.
For information on how to use SMBR, see https://library.netapp.com/ecm/ecm_download_file/ECMLP2871407[SMBR Administration Guide^].

For additional information on SMBR, refer the following:

* https://kb.netapp.com/Legacy/SMBR/How_to_manually_restore_a_single_item_with_SMBR[How to manually restore a single item with SMBR ( also applicable for Ontrack Power Control restores)]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Single_Mailbox_Recovery_(SMBR)/How_to_restore_from_secondary_storage_in_SMBR_with_SnapCenter[How to restore from secondary storage in SMBR with SnapCenter^]
* https://www.youtube.com/watch?v=fOMuaaXrreI&list=PLdXI3bZJEw7nofM6lN44eOe4aOSoryckg&index=3[Recovering Microsoft Exchange Mail From SnapVault Using SMBR^]
