---
permalink: protect-sce/reference_prerequisites_to_add_hosts_and_install_snapcenter_plug_in_for_microsoft_exchange_server.html
sidebar: sidebar
keywords:
summary: 'Before you add a host and install the plug-in packages, you must complete all the requirements.'
---
= Prerequisites to add hosts and install SnapCenter Plug-in for Microsoft Exchange Server
:icons: font
:imagesdir: ../media/

[.lead]
Before you add a host and install the plug-in packages, you must complete all the requirements.

* If you are using iSCSI, the iSCSI service must be running.
* You must have a domain user with local administrator privileges with local login permissions on the remote host.
* You must be using Microsoft Exchange Server 2013, 2016, or 2019 for standalone and Database Availability Group configurations.
* When installing a plug-in on a Windows host, if you specify a credential that is not built-in or if the user belongs to a local workgroup user, you must disable UAC on the host.
* If you manage cluster nodes in SnapCenter, you must have a user with administrative privileges to all the nodes in the cluster.
* You must have a user with administrative permissions on the Exchange Server.
* If SnapManager for Microsoft Exchange Server and SnapDrive for Windows are already installed, you must unregister the VSS Hardware Provider used by SnapDrive for Windows before you and install Plug-in for Exchange on the same Exchange Server to ensure successful data protection using SnapCenter.
* If SnapManager for Microsoft Exchange Server and Plug-in for Exchange are installed on the same server, you must suspend or delete from the Windows scheduler all schedules created by SnapManager for Microsoft Exchange Server.
* The host must be resolvable to the fully qualified domain name (FQDN) from the server. If the hosts file is modified to make it resolvable and if both the short name and the FQDN are specified in the hosts file, create a entry in the SnapCenter hosts file in the following format: `<ip_address> <host_fqdn> <host_name>`
* Ensure the following ports are not blocked in the firewall:
** Port range 50000 - 51000 for Windows 2016 and Exchange 2016
** Port range 6000 - 6500 for Windows 2012 R2 and Exchange 2013
** Port range 49152 - 65536 for Windows 2019


http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]
