---
permalink: protect-sce/task_reseed_a_replica_using_powershell_cmdlets_for_exchange_database.html
sidebar: sidebar
keywords:
summary: 'You can use PowerShell cmdlets to restore an unhealthy replica by using either the most recent copy on the same host or the most recent copy from an alternate host.'
---
= Reseed a replica using PowerShell cmdlets for Exchange database
:icons: font
:imagesdir: ../media/

[.lead]
You can use PowerShell cmdlets to restore an unhealthy replica by using either the most recent copy on the same host or the most recent copy from an alternate host.

The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running _Get-Help command_name_. Alternatively, you can also refer to the https://library.netapp.com/ecm/ecm_download_file/ECMLP2885482[SnapCenter Software Cmdlet Reference Guide^].

*Steps*

. Initiate a connection session with the SnapCenter Server for a specified user by using the `Open-SmConnection` cmdlet.
+
----
Open-smconnection  -SMSbaseurl  https:\\snapctr.demo.netapp.com:8146/
----

. Reseed the database by using the `reseed-SmDagReplicaCopy` cmdlet.
+
This example reseeds the failed copy of the database called execdb on the host "mva-rx200.netapp.com" using the latest backup on that host.
+
----
reseed-SmDagReplicaCopy -ReplicaHost "mva-rx200.netapp.com" -Database execdb
----
+
This example reseeds the failed copy of the database called execdb using the latest backup of the database (production/copy) on an alternate host "mva-rx201.netapp.com."
+
----
reseed-SmDagReplicaCopy -ReplicaHost "mva-rx200.netapp.com" -Database  execdb -BackupHost "mva-rx201.netapp.com"
----
