---
permalink: protect-sce/task_add_hosts_and_install_plug_in_for_exchange.html
sidebar: sidebar
keywords:
summary: 'You can use the SnapCenterAdd Host page to add Windows hosts. The Plug-in for Exchange is automatically installed on the specified host. This is the recommended method for installing plug-ins. You can add a host and install a plug-in either for an individual host or a cluster.'
---
= Add hosts and install Plug-in for Exchange
:icons: font
:imagesdir: ../media/

[.lead]
You can use the SnapCenterAdd Host page to add Windows hosts. The Plug-in for Exchange is automatically installed on the specified host. This is the recommended method for installing plug-ins. You can add a host and install a plug-in either for an individual host or a cluster.

*What you will need*

* You must be a user that is assigned to a role that has the plug-in install and uninstall permissions, such as the SnapCenter Admin.
* When installing a plug-in on a Windows host, if you specify a credential that is not built-in, or if the user belongs to a local workgroup user, you must disable UAC on the host.
* The message queueing service must be running.
* If you are using group Managed Service Account (gMSA), you should configure gMSA with administrative privileges. For information, see
link:task_configure_gMSA_on_windows_server_2012_or_later_for_exchange_server.html[Configure group Managed Service Account on Windows Server 2012 or later^].

*About this task*

You cannot add a SnapCenter Server as a plug-in host to another SnapCenter Server.

You can add a host and install plug-in packages either for an individual host or a cluster. If you are installing plug-ins on a cluster (Exchange DAG), they are installed on all of the nodes of the cluster even if some of nodes do not have databases on NetApp LUNs.

Plug-in for Exchange depends on SnapCenter Plug-ins Package for Windows, and the versions must be the same. During the Plug-in for Exchange installation, SnapCenter Plug-ins Package for Windows is selected by default and is installed along with the VSS Hardware Provider.

If SnapManager for Microsoft Exchange Server and SnapDrive for Windows are already installed, and you want to install Plug-in for Exchange on the same Exchange Server, you must unregister the VSS Hardware Provider used by SnapDrive for Windows because it is incompatible with the VSS Hardware Provider installed with Plug-in for Exchange and SnapCenter Plug-ins Package for Windows.

*Steps*

. In the left navigation pane, click *Hosts*.
. Verify that *Managed Hosts* is selected at the top.
. Click *Add*.
. On the *Hosts* page, do the following:
+
|===
| For this field...| Do this...

a|
Host Type
a|
Select *Windows* as the host type.

SnapCenter Server adds the host and then installs on the host the Plug-in for Windows and the Plug-in for Exchange if they are not already installed.

Plug-in for Windows and Plug-in for Exchange must be the same version. If a different version of Plug-in for Windows was previously installed, SnapCenter updates the version as part of the installation.
a|
Host name
a|
Enter the fully qualified domain name (FQDN) or the IP address of the host.

SnapCenter depends on the proper configuration of the DNS. Therefore, the best practice is to enter the fully qualified domain name (FQDN).

An IP address is supported for untrusted domain hosts only if it resolves to the FQDN.

You can enter IP addresses or the FQDN of one of the following:

 ** Stand-alone host
 ** Exchange DAG

If you are adding a host using SnapCenter and it is part of a subdomain, you must provide the FQDN.

You can also add the IP less DAG cluster by providing the IP address or the FQDN of one of the DAG cluster nodes.
a|
Credentials
a|
Select the credential name that you created, or create the new credentials.

The credential must have administrative rights on the remote host. For details, see information about creating a credential.

You can view details about the credentials by positioning your cursor over the credential name that you specified.

NOTE: Credentials authentication mode is determined by the host type that you specify in the Add Host wizard.
|===

. In the Select Plug-ins to Install section, select the plug-ins to install.
+
When you select Plug-in for Exchange, SnapCenter Plug-in for Microsoft SQL Server is deselected automatically. Microsoft recommends that SQL Server and Exchange server not be installed on the same system due to the amount of memory used and other resource usage required by Exchange.

. (Optional) Click *More Options*.
+
|===
| For this field...| Do this...

a|
Port
a|
Either retain the default port number or specify the port number.

The default port number is 8145. If the SnapCenter Server was installed on a custom port, that port number will be displayed as the default port.

NOTE: If you manually installed the plug-ins and specified a custom port, you must specify the same port. Otherwise, the operation fails.

a|
Installation Path
a|
The default path is `C:\Program Files\NetApp\SnapCenter`.

You can optionally customize the path.
a|
Add all hosts in the DAG
a|
Select this check box when you add a DAG.
a|
Skip preinstall checks
a|
Select this check box if you already installed the plug-ins manually and you do not want to validate whether the host meets the requirements for installing the plug-in.
a|
Use group Managed Service Account (gMSA) to run the plug-in services
a|
Select this check box if you want to use group Managed Service Account (gMSA) to run the plug-in services.

Provide the gMSA name in the following format: _domainName\accountName$_.

NOTE: gMSA will be used as a log on service account only for SnapCenter Plug-in for Windows service.
|===

. Click *Submit*.
+
If you have not selected the Skip prechecks check box, the host is validated to determine whether it meets the requirements to install the plug-in. If the minimum requirements are not met, the appropriate error or warning messages are displayed.
+
If the error is related to disk space or RAM, you can update the web.config file located at `C:\Program Files\NetApp\SnapCenter` WebApp to modify the default values. If the error is related to other parameters, you must fix the issue.
+
NOTE: In an HA setup, if you are updating web.config file, you must update the file on both nodes.

. Monitor the installation progress.

== Install Plug-in for Exchange from the SnapCenter Server host using PowerShell cmdlets

You should install the Plug-in for Exchange from the SnapCenter GUI. If you do not want to use the GUI, you can use PowerShell cmdlets on the SnapCenter Server host or on a remote host.

*What you will need*

* SnapCenter Server must have been installed and configured.
* You must be a local administrator on the host or a user with administrative privileges.
* You must be a user that is assigned to a role that has the plug-in, install, and uninstall permissions, such as the SnapCenter Admin.
* You must have reviewed the installation requirements and types of supported configurations before installing the Plug-in for Exchange.
* The host on which you want the Plug-in for Exchange installed must be a Windows host.

*Steps*

. On the SnapCenter Server host, establish a session using the _Open-SmConnection_ cmdlet, and then enter your credentials.
. Add the host on which you want to install the Plug-in for Exchange using the _Add-SmHost_ cmdlet with the required parameters.
+
The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running _Get-Help command_name_. Alternatively, you can also refer to the https://library.netapp.com/ecm/ecm_download_file/ECMLP2877143[SnapCenter Software Cmdlet Reference Guide^].
+
The host can be a standalone host or a DAG. If you specify a DAG, the _-IsDAG_ parameter is required.

. Install the Plug-in for Exchange using the _Install-SmHostPackage_ cmdlet with the required parameters.
+
This command installs the Plug-in for Exchange on the specified host, and then registers the plug-in with SnapCenter.

== Install the SnapCenter Plug-in for Exchange silently from the command line

You should install Plug-in for Exchange from within the SnapCenter user interface. However, if you cannot for some reason, you can run the Plug-in for Exchange installation program unattended in silent mode from the Windows command line.

*What you will need*

* You must have backed up your Microsoft Exchange Server resources.
* You must have installed the SnapCenter plug-in packages.
* You must delete the earlier release of SnapCenter Plug-in for Microsoft SQL Server before installing.
+
For more information, see https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_Install_a_SnapCenter_Plug-In_manually_and_directly_from_thePlug-In_Host[How to Install a SnapCenter Plug-In manually and directly from the Plug-In Host^].

*Steps*

. Validate whether _C:\temp_ folder exists on the plug-in host and the logged in user has full access to it.
. Download the SnapCenter Plug-in for Microsoft Windows from _C:\ProgramData\NetApp\SnapCenter\Package_ Repository.
+
This path is accessible from the host where the SnapCenter Server is installed.

. Copy the installation file to the host on which you want to install the plug-in.
. From a Windows command prompt on the local host, navigate to the directory to which you saved the plug-in installation files.
. Enter the following command to install replacing the variables with your data:
+
_snapcenter_windows_host_plugin.exe"/silent /debuglog"<Debug_Log_Path>" /log"<Log_Path>" BI_SNAPCENTER_PORT=<Num> SUITE_INSTALLDIR="<Install_Directory_Path>" BI_SERVICEACCOUNT=<domain\administrator> BI_SERVICEPWD=<password> ISFeatureInstall=HPPW,SCW,SCE_
+
For example:
+
_C:\ProgramData\NetApp\SnapCenter\Package Repository\snapcenter_windows_host_plugin.exe"/silent /debuglog"C:\HPPW_SCSQL_Install.log" /log"C:\temp" BI_SNAPCENTER_PORT=8145 SUITE_INSTALLDIR="C:\Program Files\NetApp\SnapCenter" BI_SERVICEACCOUNT=domain\administrator BI_SERVICEPWD=password ISFeatureInstall=HPPW,SCW,SCE_
+
NOTE: All the parameters passed during the installation of Plug-in for Exchange are case sensitive.

.. _/silent /debuglog"C:\Installdebug.log" /log"C:\temp" BI_SNAPCENTER_PORT=8145 SUITE_INSTALLDIR="C:\Program Files" BI_SERVICEACCOUNT=demo\administrator BI_SERVICEPWD=Netapp1! ISFeatureInstall=HPPW,SCW_
+
Enter the following values for the variables:
+
|===
| Variable| Value

a|
_/debuglog"<Debug_Log_Path>_
a|
Specify the name and location of the suite installer log file, as in the following example:

_Setup.exe /debuglog"C:\PathToLog\setupexe.log_
a|
BI_SNAPCENTER_PORT
a|
Specify the port on which SnapCenter communicates with SMCore.
a|
SUITE_INSTALLDIR
a|
Specify host plug-in package installation directory.
a|
BI_SERVICEACCOUNT
a|
Specify SnapCenter Plug-in for Microsoft Windows web service account.
a|
BI_SERVICEPWD
a|
Specify the password for SnapCenter Plug-in for Microsoft Windows web service account.
a|
ISFeatureInstall
a|
Specify the solution to be deployed by SnapCenter on remote host.
|===

. Monitor the Windows task scheduler, the main installation log file _C:\Installdebug.log_, and the additional installation files in _C:\Temp_.
. Monitor the _%temp%_ directory to check if the _msiexe.exe_ installers are installing the software without errors.
+
NOTE: The installation of Plug-in for Exchange registers the plug-in on the host and not on the SnapCenter Server. You can register the plug-in on the SnapCenter Server by adding the host using the SnapCenter GUI or PowerShell cmdlet. After the host is added, the plug-in is automatically discovered.

== Monitor SnapCenter plug-in package installation status

include::../_include/reuse_task_monitor_snapcenter_plug_in_package_installation_status.adoc[]
