---
permalink: protect-sce/task_install_plug_in_for_exchange_from_the_snapcenter_server_host_using_powershell_cmdlets.html
sidebar: sidebar
keywords: SnapCenter plug-in for Exchange Server
summary: 'You should install the Plug-in for Exchange from the SnapCenter GUI. If you do not want to use the GUI, you can use PowerShell cmdlets on the SnapCenter Server host or on a remote host.'
---
= Install Plug-in for Exchange from the SnapCenter Server host using PowerShell cmdlets
:icons: font
:imagesdir: ../media/

[.lead]
You should install the Plug-in for Exchange from the SnapCenter GUI. If you do not want to use the GUI, you can use PowerShell cmdlets on the SnapCenter Server host or on a remote host.

.Before you begin

* SnapCenter Server must have been installed and configured.
* You must be a local administrator on the host or a user with administrative privileges.
* You must be a user that is assigned to a role that has the plug-in, install, and uninstall permissions, such as the SnapCenter Admin.
* You must have reviewed the installation requirements and types of supported configurations before installing the Plug-in for Exchange.
* The host on which you want the Plug-in for Exchange installed must be a Windows host.

.Steps

. On the SnapCenter Server host, establish a session using the _Open-SmConnection_ cmdlet, and then enter your credentials.
. Add the host on which you want to install the Plug-in for Exchange using the _Add-SmHost_ cmdlet with the required parameters.
+
The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running _Get-Help command_name_. Alternatively, you can also refer to the https://library.netapp.com/ecm/ecm_download_file/ECMLP3323469[SnapCenter Software Cmdlet Reference Guide^].
+
The host can be a standalone host or a DAG. If you specify a DAG, the _-IsDAG_ parameter is required.

. Install the Plug-in for Exchange using the _Install-SmHostPackage_ cmdlet with the required parameters.
+
This command installs the Plug-in for Exchange on the specified host, and then registers the plug-in with SnapCenter.
