---
permalink: protect-sce/task_add_hosts_and_install_plug_in_for_exchange.html
sidebar: sidebar
keywords: SnapCenter Plug-in for Microsoft Exchange Server, NET TCP
summary: 'You can use the SnapCenterAdd Host page to add Windows hosts. The Plug-in for Exchange is automatically installed on the specified host. This is the recommended method for installing plug-ins. You can add a host and install a plug-in either for an individual host or a cluster.'
---
= Add hosts and install Plug-in for Exchange
:icons: font
:imagesdir: ../media/

[.lead]
You can use the SnapCenter Add Host page to add Windows hosts. The Plug-in for Exchange is automatically installed on the specified host. This is the recommended method for installing plug-ins. You can add a host and install a plug-in either for an individual host or a cluster.

.Before you begin

* If the operating system of the SnapCenter Server host is Windows 2019 and the operating system of the plug-in host is Windows 2022, you should perform the following:
** Upgrade to Windows Server 2019 (OS Build 17763.5936) or later
** Upgrade to Windows Server 2022 (OS Build 20348.2402) or later
* You must be a user that is assigned to a role that has the plug-in install and uninstall permissions, such as the SnapCenter Admin.
* When installing a plug-in on a Windows host, if you specify a credential that is not built-in, or if the user belongs to a local workgroup user, you must disable UAC on the host.
* The message queueing service must be running.
* If you are using group Managed Service Account (gMSA), you should configure gMSA with administrative privileges. For information, see
link:task_configure_gMSA_on_windows_server_2012_or_later.html[Configure group Managed Service Account on Windows Server 2016 or later for Microsoft Exchange Server^].

.About this task

* You cannot add a SnapCenter Server as a plug-in host to another SnapCenter Server.
* You can add a host and install plug-in packages either for an individual host or a cluster.
* If an exchange node is part of a DAG, you cannot add only one node into the SnapCenter Server.
* If you are installing plug-ins on a cluster (Exchange DAG), they are installed on all of the nodes of the cluster even if some of nodes do not have databases on NetApp LUNs.

Beginning with SnapCenter 4.6, SCE supports multitenancy and you can add a host using the following methods:

|===
| Add host operation | 4.5 and earlier |4.6 and later

| Add IP-less DAG in cross or different domain
| Not supported
| Supported
| Add multiple IP DAGs with unique names, residing in the same or cross domain
| Supported
| Supported
| Add multiple IP or IP-less DAGs which have same host names and/or DB name in cross domain
| Not supported
| Supported
| Add multiple IP/IP-less DAGs with the same name and cross domain
| Not supported
| Supported
| Add multiple standalone hosts with the same name and cross domain
| Not supported
| Supported
|===

Plug-in for Exchange depends on SnapCenter Plug-ins Package for Windows, and the versions must be the same. During the Plug-in for Exchange installation, SnapCenter Plug-ins Package for Windows is selected by default and is installed along with the VSS Hardware Provider.

If SnapManager for Microsoft Exchange Server and SnapDrive for Windows are already installed, and you want to install Plug-in for Exchange on the same Exchange Server, you must unregister the VSS Hardware Provider used by SnapDrive for Windows because it is incompatible with the VSS Hardware Provider installed with Plug-in for Exchange and SnapCenter Plug-ins Package for Windows. For more information, see https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_manually_register_the_Data_ONTAP_VSS_Hardware_Provider[How to manually register the Data ONTAP VSS Hardware Provider].

.Steps

. In the left navigation pane, click *Hosts*.
. Verify that *Managed Hosts* is selected at the top.
. Click *Add*.
. In the Hosts page, do the following:
+
|===
| For this field...| Do this...

a|
Host Type
a|
Select *Windows* as the host type.

SnapCenter Server adds the host and then installs on the host the Plug-in for Windows and the Plug-in for Exchange if they are not already installed.

Plug-in for Windows and Plug-in for Exchange must be the same version. If a different version of Plug-in for Windows was previously installed, SnapCenter updates the version as part of the installation.
a|
Host name
a|
Enter the fully qualified domain name (FQDN) or the IP address of the host.

SnapCenter depends on the proper configuration of the DNS. Therefore, the best practice is to enter the fully qualified domain name (FQDN).

An IP address is supported for untrusted domain hosts only if it resolves to the FQDN.

If you are adding a host using SnapCenter and it is part of a subdomain, you must provide the FQDN.

You can enter IP addresses or the FQDN of one of the following:

 ** Stand-alone host
 ** Exchange DAG
+
For an Exchange DAG, you can:

* Add a DAG by providing the DAG name, DAG IP address, node name, or node IP address.
* Add the IP less DAG cluster by providing the IP address or the FQDN of one of the DAG cluster nodes.
* Add IP less DAG that resides in the same domain or different domain. You can also add multiple IP/IP less DAGs with the same name but different domains.

[NOTE]
 For a stand-alone host or an Exchange DAG (cross-domain or same domain), it is recommended to provide FQDN or the IP address of the host or DAG.

a|
Credentials
a|
Select the credential name that you created, or create the new credentials.

The credential must have administrative rights on the remote host. For details, see information about creating a credential.

You can view details about the credentials by positioning your cursor over the credential name that you specified.

NOTE: Credentials authentication mode is determined by the host type that you specify in the Add Host wizard.
|===

. In the Select Plug-ins to Install section, select the plug-ins to install.
+
When you select Plug-in for Exchange, SnapCenter Plug-in for Microsoft SQL Server is deselected automatically. Microsoft recommends that SQL Server and Exchange server not be installed on the same system due to the amount of memory used and other resource usage required by Exchange.

. (Optional) Click *More Options*.
+
|===
| For this field...| Do this...

a|
Port
a|
Either retain the default port number or specify the port number.

The default port number is 8145. If the SnapCenter Server was installed on a custom port, that port number will be displayed as the default port.

NOTE: If you manually installed the plug-ins and specified a custom port, you must specify the same port. Otherwise, the operation fails.

a|
Installation Path
a|
The default path is `C:\Program Files\NetApp\SnapCenter`.

You can optionally customize the path.
a|
Add all hosts in the DAG
a|
Select this check box when you add a DAG.
a|
Skip preinstall checks
a|
Select this check box if you already installed the plug-ins manually and you do not want to validate whether the host meets the requirements for installing the plug-in.
a|
Use group Managed Service Account (gMSA) to run the plug-in services
a|
Select this check box if you want to use group Managed Service Account (gMSA) to run the plug-in services.

Provide the gMSA name in the following format: _domainName\accountName$_.

NOTE: gMSA will be used as a log on service account only for SnapCenter Plug-in for Windows service.
|===

. Click *Submit*.
+
If you have not selected the Skip prechecks check box, the host is validated to determine whether it meets the requirements to install the plug-in. If the minimum requirements are not met, the appropriate error or warning messages are displayed.
+
If the error is related to disk space or RAM, you can update the web.config file located at `C:\Program Files\NetApp\SnapCenter` WebApp to modify the default values. If the error is related to other parameters, you must fix the issue.
+
NOTE: In an HA setup, if you are updating web.config file, you must update the file on both nodes.

. Monitor the installation progress.

== Configure custom port for NET TCP communication

By default, beginning with SnapCenter 6.0 release, SnapCenter plug-in for Windows uses the port 909 for NET TCP communication. If the port 909 is in use, you can configure another port for NET TCP communication.

.Steps

. Modify the value of the _NetTCPPort_ key located at _C:\Program Files\NetApp\SnapCenter\SnapCenter Plug-in for Microsoft Windows\vssproviders\navssprv.exe.config_ to the required port number.
`<add key="NetTCPPort" value="new_port_number" />`
. Modify the value of the _NetTCPPort_ key located at _C:\Program Files\NetApp\SnapCenter\SnapCenter Plug-in for Microsoft Windows\SnapDriveService.dll.config_ to the required port number.
`<add key="NetTCPPort" value="new_port_number" />`
. Unregister the _Data ONTAP VSS Hardware Provider_ service by running below command:
`"C:\Program Files\NetApp\SnapCenter\SnapCenter Plug-in for Microsoft Windows\navssprv.exe" -r service -u`
+
Verify that the service is not displayed in the list of services in _services.msc_.
. Register the _Data ONTAP VSS Hardware Provider_ service by running below command:
`"C:\Program Files\NetApp\SnapCenter\SnapCenter Plug-in for Microsoft Windows\vssproviders\navssprv.exe" -r service -a ".\LocalSystem"``
+
Verify if the service is now displayed in the list of services in _services.msc_.
. Restart the _Plug-in for Windows_ service.
