---
permalink: protect-sce/task_reseed_a_passive_exchange_node_replica.html
sidebar: sidebar
keywords:
summary: 'If you need to reseed a replica copy, for instance when a copy is corrupt, you can reseed to the latest backup using the reseed feature in SnapCenter.'
---
= Reseed a passive Exchange node replica
:icons: font
:imagesdir: ../media/

[.lead]
If you need to reseed a replica copy, for instance when a copy is corrupt, you can reseed to the latest backup using the reseed feature in SnapCenter.

.Before you begin

You must have created a backup of the database you want to reseed.
+
To avoid lagging between nodes, you can either create a new backup before you perform a reseed operation, or choose the host with the latest backup.

.Steps

. In the left navigation pane, click *Resources*, and then select *Microsoft Exchange Server plug-in* from the list.
. In the Resources page, select the appropriate option from the View list:
+
|===
| Option| Description

a|
To reseed a single database
a|
Select *Database* from the View list.
a|
To reseed databases in a DAG
a|
Select *Database Availability Group* from the View list.
|===

. Select the resource you want to reseed.
. In the Manage Copies page, click *Reseed*.
. From the list of unhealthy databases copies in the Reseed wizard, select the one you want to reseed, and then click *Next*.
. In the Host window, select the host with the backup from which you want to reseed, and then click *Next*.
. In the Notification page, from the *Email preference* drop-down list, select the scenarios in which you want to send the emails.
+
You must also specify the sender and receiver email addresses, and the subject of the email.

. Review the summary, and then click *Finish*.
. You can view the status of the job by expanding the Activity panel at the bottom of the page.
+
NOTE: Reseed operation is not supported if the passive database copy resides on non-NetApp storage.
