---
permalink: protect-sce/task_install_plug_in_for_exchange_from_the_snapcenter_server_host_using_powershell_cmdlets.html
sidebar: sidebar
keywords:
summary: 'You should install the Plug-in for Exchange from the SnapCenter GUI. If you do not want to use the GUI, you can use PowerShell cmdlets on the SnapCenter Server host or on a remote host.'
---
= Install Plug-in for Exchange from the SnapCenter Server host using PowerShell cmdlets
:icons: font
:imagesdir: ../media/

[.lead]
You should install the Plug-in for Exchange from the SnapCenter GUI. If you do not want to use the GUI, you can use PowerShell cmdlets on the SnapCenter Server host or on a remote host.

* SnapCenter Server must have been installed and configured.
* You must be a local administrator on the host or a user with administrative privileges.
* You must be a user that is assigned to a role that has the plug-in, install, and uninstall permissions, such as the SnapCenter Admin.
* You must have reviewed the installation requirements and types of supported configurations before installing the Plug-in for Exchange.
* The host on which you want the Plug-in for Exchange installed must be a Windows host.

. On the SnapCenter Server host, establish a session using the `Open-SmConnection` cmdlet, and then enter your credentials.
. Add the host on which you want to install the Plug-in for Exchange using the `Add-SmHost` cmdlet with the required parameters.
+
The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running `Get-Helpcommand_name`. Alternatively, you can also refer to the _Cmdlet Reference Guide_.
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2877143[SnapCenter Software Cmdlet Reference Guide]
+
The host can be a standalone host or a DAG. If you specify a DAG, the `-IsDAG` parameter is required.

. Install the Plug-in for Exchange using the `Install-SmHostPackage` cmdlet with the required parameters.
+
This command installs the Plug-in for Exchange on the specified host, and then registers the plug-in with SnapCenter.
