dist: xenial
language: ruby
rvm:
- 2.4.3
env:
  global:
    - FRAMEWORK_BRANCH=main
jobs:
  include:
    - stage: deploy
      if: branch = main OR repo =~ /-internal/
      before_install:
      - echo -e "machine github.com\n login $GH_TOKEN" > ~/.netrc && chmod 600 ~/.netrc
      - git submodule add -b $FRAMEWORK_BRANCH https://github.com/NetAppDocs/jekyll dependencies/jekyll
      - gem update --system && gem install bundler && gem update bundler
      - if [[ -z "$DEPLOY_BRANCH" ]]; then export DEPLOY_BRANCH=gh-pages; fi
      - cp -rl dependencies/jekyll/search.html ./admin/search.html
      - sed -i 's/permalink\:\s*\/search\.html/permalink\:\ admin\/search\.html/g' ./admin/search.html
      - cp -rl dependencies/jekyll/search.html ./concept/search.html
      - sed -i 's/permalink\:\s*\/search\.html/permalink\:\ concept\/search\.html/g' ./concept/search.html
      - cp -rl dependencies/jekyll/search.html ./install/search.html
      - sed -i 's/permalink\:\s*\/search\.html/permalink\:\ install\/search\.html/g' ./install/search.html
      - cp -rl dependencies/jekyll/search.html ./protect-hana/search.html
      - sed -i 's/permalink\:\s*\/search\.html/permalink\:\ protect-hana\/search\.html/g' ./protect-hana/search.html
      - cp -rl dependencies/jekyll/search.html ./protect-scc/search.html
      - sed -i 's/permalink\:\s*\/search\.html/permalink\:\ protect-scc\/search\.html/g' ./protect-scc/search.html
      - cp -rl dependencies/jekyll/search.html ./protect-sce/search.html
      - sed -i 's/permalink\:\s*\/search\.html/permalink\:\ protect-sce\/search\.html/g' ./protect-sce/search.html
      - cp -rl dependencies/jekyll/search.html ./protect-sco/search.html
      - sed -i 's/permalink\:\s*\/search\.html/permalink\:\ protect-sco\/search\.html/g' ./protect-sco/search.html
      - cp -rl dependencies/jekyll/search.html ./protect-scsql/search.html
      - sed -i 's/permalink\:\s*\/search\.html/permalink\:\ protect-scsql\/search\.html/g' ./protect-scsql/search.html
      - cp -rl dependencies/jekyll/search.html ./protect-scw/search.html
      - sed -i 's/permalink\:\s*\/search\.html/permalink\:\ protect-scw\/search\.html/g' ./protect-scw/search.html
      - cp -rl dependencies/jekyll/search.html ./sc-automation/search.html
      - sed -i 's/permalink\:\s*\/search\.html/permalink\:\ sc-automation\/search\.html/g' ./sc-automation/search.html
      - cp -rl dependencies/jekyll/search.html ./uninstall/search.html
      - sed -i 's/permalink\:\s*\/search\.html/permalink\:\ uninstall\/search\.html/g' ./uninstall/search.html
      - cp -rl dependencies/jekyll/search.html ./upgrade/search.html
      - sed -i 's/permalink\:\s*\/search\.html/permalink\:\ upgrade\/search\.html/g' ./upgrade/search.html
      - mv dependencies/jekyll/prod-build.sh ./ && ./prod-build.sh
      - sudo apt-get -y install graphicsmagick graphicsmagick-libmagick-dev-compat libmagickwand-dev
      script:
      - if [[ ! -z "$FEATURE_FLAG" ]]; then bundle exec rake buildAll; fi
      - mkdir -p /tmp/output && bundle exec jekyll build --trace --destination /tmp/output --config _config.yml,project.yml
      - touch /tmp/output/.nojekyll
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GH_TOKEN
        keep_history: false
        local_dir: /tmp/output
        target_branch: $DEPLOY_BRANCH
        verbose: true
        on:
          all_branches: true
    - state: i18n
      if: branch = main OR repo =~ /-internal/
      before_install:
      - echo -e "machine github.com\n login $GH_TOKEN" >> ~/.netrc && chmod 600 ~/.netrc
      - git submodule add https://github.com/NetAppDocs/jekyll-harmony dependencies/jekyll-harmony
      - gem update --system && gem install bundler && gem update bundler
      install:
      - cd dependencies/jekyll-harmony
      - bundle install --jobs=3 --retry=3
      - bundle exec rake install
      - cd -
      script:
      - if [[ ! -z "$HARMONY_FLAG" ]]; then i18n-translate; fi
