sidebar:
  entries:
    - title: SnapCenter Software documentation
      url: /index.html
    - title: Release notes
      url: /reference_release_notes.html
    - section: concept
    - section: install
    - section: protect-scsql
    - section: protect-scw
    - section: protect-sco
    - section: protect-sce
    - section: protect-hana
    - section: protect-scc
    - section: admin
    - section: upgrade
    - section: uninstall
    - section: sc-automation
    - title: Legal notices
      url: /reference_legal_notices.html


homepage:
  tiles:
    - title: Get started
      links:
        - title: Learn about SnapCenter
          summary: Get an overview of SnapCenter before you get started.
          url: /concept/concept_snapcenter_overview.html
        - title: Install SnapCenter Server
          summary: Quickly install SnapCenter Server.
          url: /install/task_install_the_snapcenter_server_using_the_install_wizard.html
    - title: Documentation for previous versions
      links:
        - title: Snapcenter 4.4 documentation
          url: https://docs.netapp.com/ocsc-44/index.jsp
        - title: Snapcenter 4.3 documentation
          url: https://docs.netapp.com/ocsc-43/index.jsp
        - title: Snapcenter 4.2 documentation
          url: https://docs.netapp.com/ocsc-42/index.jsp
        - title: Snapcenter 4.1 documentation
          url: https://docs.netapp.com/ocsc-41/index.jsp
        - title: Snapcenter 4.0 documentation
          url: https://docs.netapp.com/ocsc-40/index.jsp
