---
permalink: protect-scw/concept_snapcenter_plug_in_for_microsoft_windows_overview.html
sidebar: sidebar
keywords: SnapCenter Plug-in for Microsoft Windows
summary: 'The SnapCenter Plug-in for Microsoft Windows is a host-side component of the NetApp SnapCenter Software that enables application-aware data protection management of Microsoft file system resources. In addition, it provides storage provisioning, Snapshot consistency, and space reclamation for Windows file systems. The Plug-in for Windows automates file system backup, restore, and cloning operations in your SnapCenter environment.'
---
= SnapCenter Plug-in for Microsoft Windows overview
:icons: font
:imagesdir: ../media/

[.lead]
The SnapCenter Plug-in for Microsoft Windows is a host-side component of the NetApp SnapCenter Software that enables application-aware data protection management of Microsoft file system resources. In addition, it provides storage provisioning, Snapshot consistency, and space reclamation for Windows file systems. The Plug-in for Windows automates file system backup, restore, and cloning operations in your SnapCenter environment.

When the Plug-in for Windows is installed, you can use SnapCenter with NetApp SnapMirror technology to create mirror copies of backup sets on another volume and with NetApp SnapVault technology to perform disk-to-disk backup replication for archival or standards compliance.

* Enables application-aware data protection for other plug-ins that are running in Windows hosts in your SnapCenter environment
* Automates application-aware backup, restore, and clone operations for Microsoft file systems in your SnapCenter environment
* Supports storage provisioning, Snapshot consistency, and space reclamation for Windows hosts

NOTE: The Plug-in for Windows provisions SMB shares and Windows file systems on physical and RDM LUNs but does not support backup operations for Windows file systems on SMB shares.
