---
permalink: protect-scw/concept_snapcenter_plug_in_for_microsoft_windows_overview.html
sidebar: sidebar
keywords: SnapCenter Plug-in for Microsoft Windows
summary: 'The SnapCenter Plug-in for Microsoft Windows is a host-side component of the NetAppSnapCenter Software that enables application-aware data protection management of Microsoft file system resources. In addition, it provides storage provisioning, Snapshot copy consistency, and space reclamation for Windows file systems. The Plug-in for Windows automates file system backup, restore, and cloning operations in your SnapCenter environment.'
---
= SnapCenter Plug-in for Microsoft Windows overview
:icons: font
:imagesdir: ../media/

[.lead]
The SnapCenter Plug-in for Microsoft Windows is a host-side component of the NetAppSnapCenter Software that enables application-aware data protection management of Microsoft file system resources. In addition, it provides storage provisioning, Snapshot copy consistency, and space reclamation for Windows file systems. The Plug-in for Windows automates file system backup, restore, and cloning operations in your SnapCenter environment.

When the Plug-in for Windows is installed, you can use SnapCenter with NetApp SnapMirror technology to create mirror copies of backup sets on another volume and with NetApp SnapVault technology to perform disk-to-disk backup replication for archival or standards compliance.

The Data Protection Guide for your plug-in has information about data protection operations.

The SnapCenter concepts documentation has information about the SnapCenter architecture, features, and benefits.

*Related information*

http://docs.netapp.com/ocsc-44/topic/com.netapp.doc.ocsc-con/home.html[Concepts]

http://docs.netapp.com/ocsc-44/topic/com.netapp.doc.ocsc-isg/home.html[Installing and setting up SnapCenter]
