---
permalink: protect-scw/concept_backup_naming_convention_for_windows_file_systems.html
sidebar: sidebar
keywords: 
summary: 'Windows file system backups use the default Snapshot copy naming convention. The default backup naming convention adds a timestamp to Snapshot copy names that helps you identify when the copies were created.'
---
= Backup naming convention for Windows file systems
:icons: font
:imagesdir: ../media/

[.lead]
Windows file system backups use the default Snapshot copy naming convention. The default backup naming convention adds a timestamp to Snapshot copy names that helps you identify when the copies were created.

The Snapshot copy uses the following default naming convention: `resourcegroupname_hostname_timestamp`

You should name your backup resource groups logically, as in the following example:

----
dts1_mach1x88_03-12-2015_23.17.26
----

In this example, the syntax elements have the following meanings:

* `dts1` is the resource group name.
* `mach1x88` is the host name.
* `03-12-2016_23.17.26` is the date and timestamp.

When creating a backup, you can also add a descriptive tag to help identify the backup. In contrast, if you want to use a customized backup naming convention, you need to rename the backup after the backup operation is complete.
