---
permalink: protect-scw/reference_installation_requirements_for_snapcenter_plug_in_for_microsoft_windows.html
sidebar: sidebar
keywords: requirements
summary: 'You should be aware of certain installation requirements before you install the Plug-in for Windows.'
---
= Installation requirements for SnapCenter Plug-in for Microsoft Windows
:icons: font
:imagesdir: ../media/

[.lead]
You should be aware of certain installation requirements before you install the Plug-in for Windows.

Before you begin to use the Plug-in for Windows, the SnapCenter administrator must install and configure SnapCenter Server and perform prerequisite tasks.

* You must have SnapCenter admin privileges to install the Plug-in for Windows.
+
The SnapCenter admin role must have admin privileges.

* You must have installed and configured the SnapCenter Server.
* When installing a plug-in on a Windows host, if you specify a credential that is not built-in or if the user belongs to a local workgroup user, you must disable UAC on the host.
* You must set up SnapMirror and SnapVault if you want backup replication.

== Host requirements to install SnapCenter Plug-ins Package for Windows

include::../_include/reuse_reference_host_requirements_to_install_snapcenter_plug_in_package_for_windows.adoc[]

== Set up your credentials for the Plug-in for Windows

SnapCenter uses credentials to authenticate users for SnapCenter operations. You should create credentials for installing SnapCenter plug-ins, and additional credentials for performing data protection operations on Windows file systems.

*What you will need*

* You must set up Windows credentials before installing plug-ins.

* You must set up the credentials with administrator privileges, including administrator rights, on the remote host.

* If you set up credentials for individual resource groups, and the user does not have full admin privileges, you must assign at least the resource group and backup privileges to the user.

*Steps*

. In the left navigation pane, click *Settings*.
. In the Settings page, click *Credential*.
. Click *New*.
. In the Credential page, do the following:
+
|===
| For this field...| Do this...

a|
Credential name
a|
Enter a name for the credentials.
a|
User name/Password
a|
Enter the user name and password used for authentication.

 ** Domain administrator or any member of the administrator group
+
Specify the domain administrator or any member of the administrator group on the system on which you are installing the SnapCenter plug-in. Valid formats for the Username field are as follows:

  *** `NetBIOS\UserName`
  *** `Domain FQDN\UserName`
  *** `UserName@upn`

 ** Local administrator (for workgroups only)
+
For systems that belong to a workgroup, specify the built-in local administrator on the system on which you are installing the SnapCenter plug-in. You can specify a local user account that belongs to the local administrators group if the user account has elevated privileges or the User Access control feature is disabled on the host system. The valid format for the Username field is as follows: `UserName`

+
Do not use double quotes (") or backtick (`) in the passwords. You should not use the less than (<) and exclamation (!) symbols together in passwords. For example, lessthan<!10, lessthan10<!, backtick`12.
a|
Password
a|
Enter the password used for authentication.

|===

. Click *OK*.
+
After you finish setting up credentials, you might want to assign credential maintenance to a user or group of users on the User and Access page.

== Configure gMSA on Windows Server 2016 or later

include::../_include/reuse_task_configure_gMSA_on_windows_server_2012_or_later.adoc[]
