---
permalink: protect-scw/task_set_up_your_credentials_for_the_plug_in_for_windows.html
sidebar: sidebar
keywords: credentials
summary: 'SnapCenter uses credentials to authenticate users for SnapCenter operations. You should create credentials for installing SnapCenter plug-ins, and additional credentials for performing data protection operations on Windows file systems.'
---
= Set up your credentials for the Plug-in for Windows
:icons: font
:imagesdir: ../media/

[.lead]
SnapCenter uses credentials to authenticate users for SnapCenter operations. You should create credentials for installing SnapCenter plug-ins, and additional credentials for performing data protection operations on Windows file systems.

*What you will need*

* You must set up Windows credentials before installing plug-ins.

* You must set up the credentials with administrator privileges, including administrator rights, on the remote host.

* If you set up credentials for individual resource groups, and the user does not have full admin privileges, you must assign at least the resource group and backup privileges to the user.

*Steps*

. In the left navigation pane, click *Settings*.
. In the Settings page, click *Credential*.
. Click *New*.
. In the Credential page, do the following:
+
|===
| For this field...| Do this...

a|
Credential name
a|
Enter a name for the credentials.
a|
User name/Password
a|
Enter the user name and password used for authentication.

 ** Domain administrator or any member of the administrator group
+
Specify the domain administrator or any member of the administrator group on the system on which you are installing the SnapCenter plug-in. Valid formats for the Username field are as follows:

  *** `NetBIOS\UserName`
  *** `Domain FQDN\UserName`
  *** `UserName@upn`

 ** Local administrator (for workgroups only)
+
For systems that belong to a workgroup, specify the built-in local administrator on the system on which you are installing the SnapCenter plug-in. You can specify a local user account that belongs to the local administrators group if the user account has elevated privileges or the User Access control feature is disabled on the host system. The valid format for the Username field is as follows: `UserName`

+
Do not use double quotes (") in passwords.
a|
Password
a|
Enter the password used for authentication.

|===

. Click *OK*.
+
After you finish setting up credentials, you might want to assign credential maintenance to a user or group of users on the *User and Access* page.
