---
permalink: protect-scw/task_install_on_multiple_remote_hosts_using_powershell_cmdlets.html
sidebar: sidebar
keywords: install, snapcenter
summary: 'If you want to install SnapCenter Plug-in for Microsoft Windows on multiple hosts at one time, you can do so by using the Install-SmHostPackage PowerShell cmdlet.'
---
= Install SnapCenter Plug-in for Microsoft Windows on multiple remote hosts using PowerShell cmdlets
:icons: font
:imagesdir: ../media/

[.lead]
If you want to install SnapCenter Plug-in for Microsoft Windows on multiple hosts at one time, you can do so by using the `Install-SmHostPackage` PowerShell cmdlet.

You must have logged in to SnapCenter as a domain user with local administrator rights on each host on which you want to install plug-ins.

.Steps

. Launch PowerShell.
. On the SnapCenter Server host, establish a session using the `Open-SmConnection` cmdlet, and then enter your credentials.
. Add the standalone host or the cluster to SnapCenter using the `Add-SmHost` cmdlet and the required parameters.
+
The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running _Get-Help command_name_. Alternatively, you can also refer to the https://library.netapp.com/ecm/ecm_download_file/ECMLP2886205[SnapCenter Software Cmdlet Reference Guide^].

. Install the plug-in on multiple hosts using the `Install-SmHostPackage` cmdlet and the required parameters.
+
You can use the `-skipprecheck` option when you have installed the plug-ins manually and do not want to validate whether the host meets the requirements to install the plug-in.
