---
permalink: concept/concept_disaster_recovery.html
sidebar: sidebar
keywords: Disaster Recovery
summary: 'You can recover the SnapCenter Server in the event of disasters like resource corruption or server crash using the SnapCenter disaster recovery feature.'
---
= SnapCenter Disaster Recovery
:icons: font
:imagesdir: ../media/

[.lead]
You can recover the SnapCenter Server in the event of disasters like resource corruption or server crash using the SnapCenter disaster recovery (DR) feature. You can recover SnapCenter repository, server schedules, and server configuration components. You can also recover the SnapCenter Plug-in for SQL Server and SnapCenter Plug-in for SQL Server storage.

This section describes the two types of disaster recovery (DR) in SnapCenter:

.SnapCenter Server DR

* SnapCenter Server data is backed up and can be recovered without any plug-in added to or managed by the SnapCenter Server.
* Secondary SnapCenter Server should be installed on the same installation directory and on the same port as the primary SnapCenter Server.
* For Multi-factor authentication (MFA), during Snapcenter Server DR, close all the  browser tabs and reopen a browser to login again. This will clear the existing or active session cookies and update that the correct configuration data.
* SnapCenter disaster recovery functionality uses REST APIs to backup SnapCenter Server. See link:../tech-refresh/task_tech_refresh_server_host.html[REST API workflows for disaster recovery of SnapCenter Server].
* Audit settings related configuration file is not backed up in DR backup and neither on the DR server after restore operation. You should manually repeat the Audit log settings.

.SnapCenter Plug-in and Storage DR

DR is supported only for SnapCenter Plug-in for SQL Server. When the SnapCenter Plug-in for SQL Server is down, switch to a different SQL host and recover the data by performing few steps. See link:../protect-scsql/task_disaster_recovery_scsql.html[Disaster recovery of SnapCenter Plug-in for SQL Server].

SnapCenter uses ONTAP SnapMirror technology to replicate data. It can be used to replicate data to a secondary site for DR and keep it in sync. A failover can be initiated by breaking the replication relationship in SnapMirror. During failback the synchronization can be reversed and data from the DR site can be replicated back to the primary location.
