---
permalink: concept/concept_types_of_role_based_access_control_in_snapcenter.html
sidebar: sidebar
keywords: 
summary: 'SnapCenter role-based access control \(RBAC\) and ONTAP permissions enable SnapCenter administrators to create roles and set access permissions. This centrally managed access empowers application administrators to work securely within delegated environments.'
---
= Types of role-based access control in SnapCenter
:icons: font
:imagesdir: ../media/

[.lead]
SnapCenter role-based access control (RBAC) and ONTAP permissions enable SnapCenter administrators to create roles and set access permissions. This centrally managed access empowers application administrators to work securely within delegated environments.

SnapCenter uses the following types of role-based access control:

* SnapCenter RBAC
* SnapCenter plug-in RBAC (for some plug-ins)
* Application-level RBAC
* ONTAP permissions

== SnapCenter RBAC

* *Roles and permissions*
+
SnapCenter ships with predefined roles with permissions already assigned. You can assign users or groups of users to these roles. You can also create new roles and manage permissions and users.

 ** Assigning permissions to users or groups
+
You can assign permissions to users or groups to access SnapCenter objects such as hosts, storage connections, and resource groups. You cannot change the permissions of the SnapCenterAdmin role.
+
You can assign RBAC permissions to users and groups within the same forest and to users belonging to different forests. You cannot assign RBAC permissions to users belonging to nested groups across forests.

+
NOTE: If you create a custom role, it must contain all of the permissions of the SnapCenter Admin role. If you only copy some of the permissions, for example, Host add or Host remove, you cannot perform those operations.

* *Authentication*
+
Users are required to provide authentication during login, through the graphical user interface (GUI) or using PowerShell cmdlets. If users are members of more than one role, after entering login credentials, they are prompted to specify the role they want to use. Users are also required to provide authentication to run the APIs.

== Application-level RBAC

SnapCenter uses credentials to verify that authorized SnapCenter users also have application-level permissions.

For example, if you want to perform Snapshot copy and data protection operations in a SQL Server environment, you must set credentials with the proper Windows or SQL credentials. The SnapCenter Server authenticates the credentials set using either method. If you want to perform Snapshot copy and data protection operations in a Windows file system environment on ONTAP storage, the SnapCenter admin role must have admin privileges on the Windows host.

Similarly, if you want to perform data protection operations on an Oracle database and if the operating system (OS) authentication is disabled in the database host, you must set credentials with the Oracle database or Oracle ASM credentials. The SnapCenter Server authenticates the credentials set using one of these methods depending on the operation.

== SnapCenter Plug-in for VMware vSphere RBAC

If you are using the SnapCenter VMware plug-in for VM-consistent data protection, the vCenter Server provides an additional level of RBAC. tHE SnapCenter VMware plug-in supports both vCenter Server RBAC and Data ONTAP RBAC.

NOTE: The SnapCenter Plug-in for VMware vSphere is deployed as a standalone virtual appliance (Open Virtual Appliance format). The SnapCenter Plug-in for VMware vSphere documentation has more information.

https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_role_based_access_control.html[SnapCenter Plug-in for VMware vSphere Data Protection Guide]

== ONTAP permissions

You must have vsadmin account permissions to access the storage system. A list is minimum required ONTAP privileges is included in the SnapCenter Server installation guide.
