---
permalink: concept/concept_snapcenter_repository.html
sidebar: sidebar
keywords: repository
summary: 'The SnapCenter repository, sometimes referred to as the NSM database, stores information and metadata for every SnapCenter operation.'
---
= SnapCenter repository
:icons: font
:imagesdir: ../media/

[.lead]
The SnapCenter repository, sometimes referred to as the NSM database, stores information and metadata for every SnapCenter operation.

MySQL Server repository database is installed by default when you install the SnapCenter Server. If MySQL Server is already installed and you are doing a fresh installation of SnapCenter Server, you should uninstall MySQL Server.

SnapCenter supports MySQL Server 5.7.25 or later as the SnapCenter repository database. If you were using an earlier version of MySQL Server with an earlier release of SnapCenter, during SnapCenter upgrade, the MySQL Server is upgraded to 5.7.25 or later.

The SnapCenter repository stores the following information and metadata:

* Backup, clone, restore, and verification metadata
* Reporting, job, and event information
* Host and plug-in information
* Role, user, and permission details
* Storage system connection information

SnapCenter can back up its own repository by using the SnapCenter repository management features. The _Administration Guide_ or the _Windows Cmdlet Reference Guide_ contain the details.

The NetAppInteroperability Matrix Tool (IMT) contains the latest information about the MySQL supported versions.

http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]
