---
permalink: concept/reference_data_security.html
sidebar: sidebar
keywords: security,authentication, CA certificates
summary: 'SnapCenter employs strict security and authentication features to enable you to keep your data secure.'
---
= Security features
:icons: font
:imagesdir: ../media/

[.lead]
SnapCenter employs strict security and authentication features to enable you to keep your data secure.

SnapCenter includes the following security features:

* All communication to SnapCenter uses HTTP over SSL (HTTPS).
* All credentials in SnapCenter are protected using Advanced Encryption Standard (AES) encryption.
* SnapCenter uses security algorithms that are compliant with the Federal Information Processing Standard (FIPS).
* SnapCenter supports using the authorized CA certificates provided by the customer.
* SnapCenter 4.1.1 or later supports Transport Layer Security (TLS) 1.2 communication with ONTAP. You can also use TLS 1.2 communication between clients and servers.
* SnapCenter is installed inside your company's firewall to enable access to the SnapCenter Server and to enable communication between the SnapCenter Server and the plug-ins.
* SnapCenter API and operation access uses tokens encrypted with AES encryption, which expire after 24 hours.
* SnapCenter integrates with Windows Active Directory for login and role-based access control (RBAC) that govern access permissions.
* SnapCenter PowerShell cmdlets are session secured.
* After a default period of 15 minutes of inactivity, SnapCenter warns you that you will be logged out in 5 minutes. After 20 minutes of inactivity, SnapCenter logs you out, and you must log in again. You can modify the log out period.
* Login is temporarily disabled after 5 or more incorrect login attempts.

== CA Certificate Overview

The SnapCenter Server installer enables the Centralized SSL Certificate Support during installation. To enhance the secured communication between the server and the plug-in, SnapCenter supports using the authorized CA certificates provided by the customer.

You should deploy CA certificates after installing the SnapCenter Server and the  respective plug-ins.
For more information, see link:../install/reference_generate_CA_certificate_CSR_file.html[Generate CA Certificate CSR file^].

You can also deploy CA certificate for SnapCenter plug-in for VMware vSphere. For more information, see https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_manage_snapcenter_plug-in_for_vmware_vsphere.html#create-and-import-certificates[Create and import certificates^].

== Multi-factor authentication (MFA)

Multi-factor authentication (MFA) uses a third-party Identity Provider (IdP) via the Security Assertion Markup Language (SAML) to manage user sessions. MFA enables administrators to configure additional factors of authentication as required, such as password and text or email message.

MFA is applicable only for SnapCenter Server UI login.  The logins are authenticated through the IdP Active Directory Federation Services (AD FS).  You can configure various authentication factors at AD FS. SnapCenter is the service provider and you should configure SnapCenter as a relying party in AD FS. To enable MFA in SnapCenter, you will require the AD FS metadata.

=== Limitations of MFA

* Workgroup user login is not supported.
* Disjoint domains are supported only if the domains are configured from ADFS.
*	SnapCenter certificate renewal data should be updated in the AD FS relying party.
* System time of AD FS server and the SnapCenter Server should be the same to login successfully. 

To configure MFA, see link:../install/configure_multifactor_authentication.html[Configuring Multi-factor authentication].
