---
permalink: concept/reference_data_security.html
sidebar: sidebar
keywords: security,authentication, CA certificates
summary: 'SnapCenter employs strict security and authentication features to enable you to keep your data secure.'
---
= Security features
:icons: font
:imagesdir: ../media/

[.lead]
SnapCenter employs strict security and authentication features to enable you to keep your data secure.

SnapCenter includes the following security features:

* All communication to SnapCenter uses HTTP over SSL (HTTPS).
* All credentials in SnapCenter are protected using Advanced Encryption Standard (AES) encryption.
* SnapCenter uses security algorithms that are compliant with the Federal Information Processing Standard (FIPS).
* SnapCenter supports using the authorized CA certificates provided by the customer.
* SnapCenter 4.1.1 or later supports Transport Layer Security (TLS) 1.2 communication with ONTAP. You can also use TLS 1.2 communication between clients and servers.
* SnapCenter is installed inside your company's firewall to enable access to the SnapCenter Server and to enable communication between the SnapCenter Server and the plug-ins.
* SnapCenter API and operation access uses tokens encrypted with AES encryption, which expire after 24 hours.
* SnapCenter integrates with Windows Active Directory for login and role-based access control (RBAC) that govern access permissions.
* SnapCenter PowerShell cmdlets are session secured.
* After a default period of 15 minutes of inactivity, SnapCenter warns you that you will be logged out in 5 minutes. After 20 minutes of inactivity, SnapCenter logs you out, and you must log in again. You can modify the log out period.
* Login is temporarily disabled after 5 or more incorrect login attempts.

== CA Certificate Overview

The SnapCenter Server installer enables the Centralized SSL Certificate Support during installation. To enhance the secured communication between the server and the plug-in, SnapCenter supports using the authorized CA certificates provided by the customer.

You should deploy CA certificates after installing the SnapCenter Server and the  respective plug-ins.
For more information, see link:../install/reference_generate_CA_certificate_CSR_file.html[Generate CA Certificate CSR file].

You can also deploy CA certificate for SnapCenter plug-in for VMware vSphere. For more information, see https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_manage_snapcenter_plug-in_for_vmware_vsphere.html#create-and-import-certificates[Create and import certificates^].

== Multi-factor authentication (MFA)

MFA uses a third-party Identity Provider (IdP) via the Security Assertion Markup Language (SAML) to manage user sessions. This functionality enhances the authentication security by having an option to use multiple factors such as TOTP, biometrics, push notifications etc. along with the existing username & password. Also, it enables the customer to use their own user identity providers to get unified user login (SSO) across their portfolio.

MFA is applicable only for SnapCenter Server UI login.  The logins are authenticated through the IdP Active Directory Federation Services (AD FS).  You can configure various authentication factors at AD FS. SnapCenter is the service provider and you should configure SnapCenter as a relying party in AD FS. To enable MFA in SnapCenter, you will require the AD FS metadata.

=== Limitations of MFA

* Workgroup user login and disjoint AD domains are not supported.
* System time of AD FS server and the SnapCenter Server should be the same to login successfully.
* CA certificate is mandatory because of the following reasons:
** If the certificates are different (in case of self-signed) at the node level the ADFS-F5 communications will break
** During the upgrade, repair, or disaster recovery (DR) on a stand-alone or high availability(HA) configurations, the self-signed certificate might get recreated resulting in the reconfiguration of MFA
** CA certificate ensures IP-FQDN resolutions
*	If the username or password error is displayed on the ADFS page, you should check the following:
** Whether the username or password is valid (whether the user account exists in Active Directory(AD)
** Whether the user exceeded the max allowed attempts (set in AD)
** Whether the AD or ADFS is up and running
* Workgroup, cross domain users cannot log in using MFA

* F5 – sc cmds need to be executed in both nodes? relying party configuration using cluster, node level access will be blocked ; Disable?
•	log out behaviour from apps; login to one app another app won’t be logged
•	timings different

* When multiple tabs are open and if you sign out from any one tab, all the pages will not be redirected back to the proper ADSF login page.
+
It is recommended to close the other tabs or close and reopen the browser.
*	IE browser is not supported for ADFS login.


For information to enable MFA, see link:../install/enable_multifactor_authentication.html[Enable Multi-factor authentication].
