---
permalink: upgrade/task_upgrade_snapcenter.html
sidebar: sidebar
keywords: upgrade, upgrade snapcenter server, windows
summary: 'You can use the SnapCenter Server installer executable file to upgrade the SnapCenter Server.'
---

= Upgrade the SnapCenter Server on Windows host
:icons: font
:imagesdir: ../media/

[.lead]
You should upgrade the SnapCenter Server to access the latest features and enhancements provided in the newest version.

.Before you begin

* Update the SnapCenter Server host with the latest Windows updates and ensure there are no pending system restarts.
* Ensure no other operations are running before you start the upgrade.
* Install ASP.NET Core Runtime 8.0.12 (and all subsequent 8.0.x patches) Hosting Bundle and PowerShell 7.4.2 or later.
* Back up the SnapCenter repository (MySQL) database after ensuring that no jobs are running. This is recommended before upgrading SnapCenter Server and the Exchange plug-in.
+
For information, see link:../admin/concept_manage_the_snapcenter_server_repository.html#back-up-the-snapcenter-repository[Back up the SnapCenter repository^].

* Back up all the modified SnapCenter configuration files that you have modified either on the SnapCenter Server host or the plug-in host.
+
Examples of SnapCenter configuration files: SnapDriveService.exe.config, SMCoreServiceHost.exe.config, and so on.

* If you have installed multiple versions of custom plug-in in SnapCenter 5.0, before upgrading to 6.0 or later, you should run the powershell cmdlets to remove all the earlier versions of the custom plug-in (except the latest one) from the SnapCenter repository (NSM database).
+
** Run `Open-SmConnection` and login using the SnapCenterAdmin role credentials
** Run `Remove-SmPluginPackage -PluginName M<plug-in name> -PluginVersion <version number>`
+
For more information, refer to https://kb.netapp.com/data-mgmt/SnapCenter/SC_KBs/SnapCenter_6.0_upgrade_fails_in_nsm_repository_upgrade_SQL_script_8[Upgrade to SnapCenter 6.0 or later fails].

.About this task

* During upgrade, SnapCenter executes a SQL script to update the Exchange data in the NSM database, converting the DAG and host shortname to FQDN. This applies only if you use SnapCenter Server with the Exchange plug-in.

* If you have manually placed the server host in maintenance mode, after the upgrade select *Hosts* > *Activate Schedule* to bring the server host out of maintenance mode.

* For the existing backup and verification schedules with prescripts and postscripts enabled in the policy, the backup operations will continue to work after upgrade.
+
In the *Job details* page, a warning message recommends that the customer should copy the scripts to the SCRIPTS_PATH and edit the policy to provide a path that is relative to the SCRIPTS_PATH. For the clone lifecycle job, the warning message appears at the sub-job level.

.Steps

. Download the SnapCenter Server installation package from the NetApp Support Site.
+
https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab

. Create a copy of the web.config located at C:\Program Files\NetApp\SnapCenter WebApp.
. Export the SnapCenter plug-in host schedules from the Windows Task Scheduler to restore them if the upgrade fails.
+
`md d:\\SCBackup``schtasks /query /xml /TN taskname >> "D:\SCBackup\taskname.xml"`
. Create the SnapCenter MySQL database dump if the repository backup is not configured.
+
`md d:\\SCBackup``mysqldump --all-databases --single-transaction --add-drop-database --triggers --routines --events -u root -p > D:\SCBackup\SCRepoBackup.dmp`
+
When prompted, enter the password.

. Double-click the downloaded .exe file to initiate the SnapCenter Server upgrade.
+
After you start the upgrade, SnapCenter runs prechecks. If the system does not meet the minimum requirements, SnapCenter shows error or warning messages. You can ignore warnings and continue with the installation, but you must fix any errors.
+
NOTE: SnapCenter continues to use the existing MySQL Server repository database password provided during installation of the earlier version of SnapCenter Server.

. Select *Upgrade*.
+
If you select *Cancel* at any stage, SnapCenter stops the upgrade. It will not rollback the SnapCenter Server to previous state.
+
*Best Practice:* Log out and log in again, or open a new browser to access the SnapCenter User Interface.

.After you finish

* If the plug-in is installed using a sudo user, you should copy the sha224 keys available at _C:\ProgramData\NetApp\SnapCenter\Package Repository\sc_unix_plugins_checksum.txt_ to update the _/etc/sudoers_ file.
* You should perform a fresh discovery of resources on the server host.
+
If SnapCenter displays the server host status as stopped, wait for some time and perform a fresh discovery. You can also change the value of *HostRefreshInterval* parameter (default value is 3600 seconds) to any value more than 10 minutes.
//Included the above statement for BURT 1399849 for 4.5
* If the upgrade fails, clean up the failed installation, reinstall the earlier version of SnapCenter, and restore the NSM database to the state it was in before.
* After upgrading the server host, you must also upgrade the plug-ins before adding any storage system.
