---
permalink: upgrade/task_configure_snapcenter_to_check_for_available_updates.html
sidebar: sidebar
keywords: configure, snapcenter server, updates, software updates
summary: 'SnapCenter periodically communicates with the NetApp Support Site to notify you of available software updates. You can also create a schedule to specify the interval in which you want to receive information about available updates.'
---
= Configure SnapCenter to check for available updates
:icons: font
:imagesdir: ../media/

[.lead]
SnapCenter periodically communicates with the NetApp Support Site to notify you of available software updates. You can also create a schedule to specify the interval in which you want to receive information about available updates.

.Steps

. In the left navigation pane, select *Settings*.
. In the *Settings* page, select *Software*.
+
The Available Software page displays the available plug-in packages, versions available, and their installation status.

. Select *Check for updates* to see if any newer versions of plug-in packages are available.
. Select *Schedule Updates* to create a schedule to specify the interval in which you want to receive information about available updates:
 .. Select the interval in *Check for updates*.
 .. Select the SnapCenter Server Admin Windows credential and click *OK*.
