---
permalink: protect-hana/concept_how_snapcenter_plug_in_for_sap_hana_database_uses_consistency_group_snapshot_copies.html
sidebar: sidebar
keywords: SnapCenter Plug-in for SAP HANA Database
summary: 'You can use the plug-in to create consistency group Snapshots for resource groups. A consistency group is a container that can house multiple volumes so that you can manage them as one entity. A consistency group is simultaneous Snapshots of multiple volumes, providing consistent copies of a group of volumes.'
---
= How SnapCenter Plug-in for SAP HANA Database uses consistency group Snapshots 
:icons: font
:imagesdir: ../media/

[.lead]
You can use the plug-in to create consistency group Snapshots for resource groups. A consistency group is a container that can house multiple volumes so that you can manage them as one entity. A consistency group is simultaneous Snapshots of multiple volumes, providing consistent copies of a group of volumes.

You can also specify the wait time for the storage controller to consistently group Snapshots. The available wait time options are *Urgent*, *Medium*, and *Relaxed*. You can also enable or disable Write Anywhere File Layout (WAFL) sync during consistent group Snapshot operation. WAFL sync improves the performance of a consistency group Snapshot.
