---
permalink: protect-hana/reference_prerequisites_to_adding_hosts_and_installing_snapcenter_plug_in_for_sap_hana_database.html
sidebar: sidebar
keywords: credentials
summary: 'Before you add a host and install the plug-in packages, you must complete all the requirements. SnapCenter Plug-in for SAP HANA Database is available in both Windows and Linux environments.'
---
= Prerequisites for adding hosts and installing SnapCenter Plug-in for SAP HANA Database
:icons: font
:imagesdir: ../media/

[.lead]
Before you add a host and install the plug-in packages, you must complete all the requirements. SnapCenter Plug-in for SAP HANA Database is available in both Windows and Linux environments.

* You must have installed Java 1.8 64-bit on your host.
* You must have installed SAP HANA database interactive terminal (HDBSQL client) on the host.
+
For Windows, the HDBSQL client must be running using the "`SYSTEM`" Windows user.

* For Windows, plug-in Creator Service should be running using the "`LocalSystem`" windows user, which is the default behavior when Plug-in for SAP HANA Database is installed as domain administrator.
* For Windows, user store keys should be created as SYSTEM user.
* When installing a plug-in on a Windows host, if you specify a credential that is not built-in or if the user belongs to a local workgroup user, you must disable UAC on the host. SnapCenter Plug-in for Microsoft Windows will be deployed by default with the SAP HANA plug-in on Windows hosts.
* For Linux host, HDB Secure User Store keys are accessed as HDBSQL OS user.
* SnapCenter Server should have access to the 8145 or custom port of Plug-in for SAP HANA Database host.

== Windows hosts

* You must have a domain user with local administrator privileges with local login permissions on the remote host.
* While installing Plug-in for SAP HANA Database on a Windows host, SnapCenter Plug-in for Microsoft Windows is installed automatically.
* You must have enabled the password-based SSH connection for the root or non-root user.
* You must have installed Java 1.8 64-bit on your Windows host.
+
If you are using Windows 2016 for the SnapCenter Server host, you must install Java 1.8, 64-bit.
+
The Interoperability Matrix Tool (IMT) contains the latest information about requirements.
+
http://www.java.com/en/download/manual.jsp[Java Downloads for All Operating Systems]
+
http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]

== Linux hosts

* You must have enabled the password-based SSH connection for the root or non-root user.
* You must have installed Java 1.8 64-bit on your Linux host.
+
The Interoperability Matrix Tool (IMT) contains the latest information about requirements.
+
http://www.java.com/en/download/manual.jsp[Java Downloads for All Operating Systems]
+
http://mysupport.netapp.com/matrix[NetApp Interoperability Matrix Tool]

* You should always have read/write permission for the "`/tmp`" folder on the plug-in host.
* For SAP HANA databases that are running on a Linux host, while installing Plug-in for SAP HANA Database, SnapCenter Plug-in for UNIX is installed automatically.
