---
permalink: protect-hana/task_add_hosts_and_install_plug_in_packages_on_remote_hosts_sap_hana.html
sidebar: sidebar
keywords: credentials
summary: 'You must use the SnapCenter Add Host page to add hosts, and then install the plug-ins packages. The plug-ins are automatically installed on the remote hosts. You can add a host and install plug-in packages either for an individual host or for a cluster.'
---
= Add hosts and install plug-in packages on remote hosts
:icons: font
:imagesdir: ../media/

[.lead]
You must use the SnapCenter Add Host page to add hosts, and then install the plug-ins packages. The plug-ins are automatically installed on the remote hosts. You can add a host and install plug-in packages either for an individual host or for a cluster.

In load balancer setup (NLB/F5), if you add a node that is partially resolved by the NLB/F5 node and if the SnapCenter node is not able to reach out to this node, then the SnapCenter host page switches between hosts down and running state frequently. To resolve this issue, you should ensure that both the SnapCenter nodes are able to resolve the host in NLB/F5 node.

*What you will need*

* You must be a user that is assigned to a role that has the plug-in install and uninstall permissions, such as the SnapCenter Admin role.
* When installing a plug-in on a Windows host, if you specify a credential that is not built-in, or if the user belongs to a local workgroup user, you must disable UAC on the host.
* You should ensure that the message queueing service is running.
* The administration documentation contains information about managing hosts.

* If you are using group Managed Service Account (gMSA), you should configure gMSA with administrative privileges.

link:protect-hana/task_configure_gMSA_on_windows_server_2012_or_later_for_plugin_for_hana.adoc[Configure group Managed Service Account on Windows Server 2012 or later for SAP HANA]


*About this task*

You cannot add a SnapCenter Server as a plug-in host to another SnapCenter Server.

In load balancer setup (NLB/F5), if you add a node that is partially resolved by the NLB/F5 node and if the SnapCenter node is not able to reach out to this node, then the SnapCenter host page switches between hosts down and running state frequently. To resolve this issue, you should ensure that both the SnapCenter nodes are able to resolve the host in NLB/F5 node.

*Steps*

. In the left navigation pane, click *Hosts*.
. Verify that the *Managed Hosts* tab is selected at the top.
. Click *Add*.
. On the *Hosts* page, perform the following actions:
+
|===
| For this field...| Do this...

a|
Host Type
a|
Select the type of host:

 ** Windows
 ** Linux
*Note:* The Plug-in for SAP HANA is installed on the HDBSQL client host, and this host can be on either a Windows system or a Linux system.

a|
Host name
a|
Enter the communication host name. Enter the fully qualified domain name (FQDN) or the IP address of the host. SnapCenter depends on the proper configuration of the DNS. Therefore, the best practice is to enter the FQDN.
+
You must configure the HDBSQL client and HDBUserStore on this host.
a|
Credentials
a|
Either select the credential name that you created or create new credentials.     The credential must have administrative rights on the remote host. For details, see the information about creating credentials.
+
You can view details about the credentials by positioning your cursor over the credential name that you provided.
+
[NOTE]
The credentials authentication mode is determined by the host type that you specify in the Add Host wizard.
+
|===

. In the Select Plug-ins to Install section, select the plug-ins to install.
. (Optional) Click *More Options*.
+
|===
| For this field...| Do this...

a|
Port
a|
Either retain the default port number or specify the port number.    The default port number is 8145. If the SnapCenter Server was installed on a custom port, that port number will be displayed as the default port.
+
NOTE: If you manually installed the plug-ins and specified a custom port, you must specify the same port. Otherwise, the operation fails.
a|
Installation Path
a|
The Plug-in for SAP HANA is installed on the HDBSQL client host, and this host can be on either a Windows system or a Linux system.

 ** For the SnapCenter Plug-ins Package for Windows, the default path is C:\Program Files\NetApp\SnapCenter. Optionally, you can customize the path.
 ** For the SnapCenter Plug-ins Package for Linux, the default path is /opt/NetApp/snapcenter. Optionally, you can customize the path.

a|
Skip preinstall checks
a|
Select this check box if you already installed the plug-ins manually and you do not want to validate whether the host meets the requirements for installing the plug-in.
a|
Use group Managed Service Account (gMSA) to run the plug-in services
a|
For Windows host, select this check box if you want to use group Managed Service Account (gMSA) to run the plug-in services.     *Note:*

Provide the gMSA name in the following format: domainName\accountName$.
*Note:* gMSA will be used as a log on service account only for SnapCenter Plug-in for Windows service.

+
|===

. Click *Submit*.
+
If you have not selected the Skip prechecks checkbox, the host is validated to verify whether the host meets the requirements for installing the plug-in. The disk space, RAM, PowerShell version, .NET version, location (for Windows plug-ins), and Java version (for Linux plug-ins) are validated against the minimum requirements. If the minimum requirements are not met, appropriate error or warning messages are displayed.
+
If the error is related to disk space or RAM, you can update the web.config file located at C:\Program Files\NetApp\SnapCenter WebApp to modify the default values. If the error is related to other parameters, you must fix the issue.
+
NOTE: In an HA setup, if you are updating web.config file, you must update the file on both nodes.

. If host type is Linux, verify the fingerprint, and then click *Confirm and Submit*.
+
In a cluster setup, you should verify the fingerprint of each of the nodes in the cluster.
+
NOTE: Fingerprint verification is mandatory even if the same host was added earlier to SnapCenter and the fingerprint was confirmed.

. Monitor the installation progress.
+
The installation-specific log files are located at /custom_location/snapcenter/logs.
