---
permalink: protect-scc/concept_snapcenter_custom_plug_ins_overview.html
sidebar: sidebar
keywords: SnapCenter Custom Plug-ins
summary: 'You can develop custom plug-ins for applications that you use and then use SnapCenter to backup, restore, or clone these applications. Like other SnapCenter plug-ins, your custom plug-ins act as host-side components of the NetAppSnap Center Software, enabling application-aware data protection and management of resources.'
---
= SnapCenter Custom Plug-ins overview
:icons: font
:imagesdir: ../media/

[.lead]
You can develop custom plug-ins for applications that you use and then use SnapCenter to backup, restore, or clone these applications. Like other SnapCenter plug-ins, your custom plug-ins act as host-side components of the NetApp SnapCenter Software, enabling application-aware data protection and management of resources.

When Custom Plug-ins are installed, you can use SnapCenter with NetApp SnapMirror technology to create mirror copies of backup sets on another volume and use NetApp SnapVault technology to perform disk-to-disk backup replication. The Custom Plug-ins can be used in both Windows and Linux environments.

NOTE: SnapCenterCLI does not support SnapCenter Custom Plug-ins commands.

NetApp provides MySQL, MAXDB, DB2, SYBASE, DPGLUE, MongoDB, ORASCPM, and PostgreSQL custom plug-ins. These plug-ins can be downloaded from the https://automationstore.netapp.com/home.shtml[NetApp Storage Automation Store^].

NOTE: SnapCenter support policy will cover support for SnapCenter custom plug-in framework, core engine, and the associated APIs. Support will not cover the plug-in source code and the associated scripts built on the custom plug-in framework.
//BURT 1389548

You can create your own custom plug-ins by referring to link:concept_develop_a_plug_in_for_your_application.html[Develop a plug-in for your application^].
