---
permalink: protect-scc/concept_snapcenter_custom_plug_ins_features.html
sidebar: sidebar
keywords: Custom Plug-ins features
summary: 'SnapCenter integrates with the plug-in application and with NetApp technologies on the storage system. To work with Custom Plug-ins, you use the SnapCenter graphical user interface.'
---
= SnapCenter Custom Plug-ins features
:icons: font
:imagesdir: ../media/

[.lead]
SnapCenter integrates with the plug-in application and with NetApp technologies on the storage system. To work with Custom Plug-ins, you use the SnapCenter graphical user interface.

* *Unified graphical user interface*
+
The SnapCenter interface provides standardization and consistency across plug-ins and environments. The SnapCenter interface enables you to complete consistent backup, restore, recovery, and clone operations across plug-ins, use centralized reporting, use at-a-glance dashboard views, set up role-based access control (RBAC), and monitor jobs across all plug-ins.

* *Automated central administration*
+
You can schedule backup operations, configure policy-based backup retention, and perform restore operations. You can also proactively monitor your environment by configuring SnapCenter to send email alerts.

* *Nondisruptive NetApp Snapshot copy technology*
+
SnapCenter uses NetApp Snapshot copy technology with the SnapCenter Custom Plug-ins to back up resources. Snapshot copies consume minimal storage space.

Using the Custom Plug-ins feature also offers the following benefits:

* Support for backup, restore, and clone workflows
* RBAC-supported security and centralized role delegation
+
You can also set the credentials so that the authorized SnapCenter users have application-level permissions.

* Creation of space-efficient and point-in-time copies of resources for testing or data extraction by using NetApp FlexClone technology
+
A FlexClone license is required on the storage system where you want to create the clone.

* Support for the consistency group (CG) Snapshot copy feature of ONTAP as part of creating backups.
* Capability to run multiple backups simultaneously across multiple resource hosts
+
In a single operation, Snapshot copies are consolidated when resources in a single host share the same volume.

* Capability to create Snapshot copy using external commands.
* Capability to create file system consistent Snapshot copies in Windows environments.
