---
permalink: protect-scc/prerequisites_for_using_custom_plugins.html
sidebar: sidebar
keywords: Credentials
summary: 'Before you use SnapCenter custom plug-ins, the SnapCenter administrator must install and configure the SnapCenter Server and perform the prerequisite tasks.'
---
= Prerequisites for using the custom plug-ins
:icons: font
:imagesdir: ../media/

[.lead]
Before you use SnapCenter custom plug-ins, the SnapCenter administrator must install and configure the SnapCenter Server and perform the prerequisite tasks.

* Install and configure SnapCenter Server.
* Log in to SnapCenter Server.
* Configure the SnapCenter environment by adding storage system connections and creating credentials, if applicable.
* Add hosts, and install and upload the plug-ins.
* If applicable, install Java 11 on the plug-in host.
* If you have multiple data paths (LIFs) or a dNFS configuration, you can perform the following using the SnapCenter CLI on the database host:
 ** By default, all the IP addresses of the database host are added to the NFS storage export policy in storage virtual machine (SVM) for the cloned volumes. If you want to have a specific IP address or restrict to a subset of the IP addresses, run the Set-PreferredHostIPsInStorageExportPolicy CLI.
 ** If you have multiple data paths (LIFs) in SVMs, SnapCenter chooses the appropriate data path (LIF) for mounting the NFS cloned volume. However, if you want to specify a specific data path (LIF), you must run the Set-SvmPreferredDataPath CLI.
The information regarding the parameters that can be used with the command and their descriptions can be obtained by running _Get-Help command_name_. Alternatively, you can also refer to the https://library.netapp.com/ecm/ecm_download_file/ECMLP3323470[SnapCenter Software Command Reference Guide^].

* Set up SnapMirror and SnapVault, if you want backup replication.
* Ensure that port 9090 is not used by any other application on the host.
+
Port 9090 must be reserved for use by the custom plug-ins in addition to the other ports required by SnapCenter.
