---
permalink: protect-scc/reference_host_requirements_for_installing_the_snapcenter_plug_in_package_for_linux_scc.html
sidebar: sidebar
keywords: SnapCenter
summary: 'You should ensure that the host meets the requirements before installing the SnapCenter Plug-ins Package for Linux.'
---
= Host requirements for installing the SnapCenter Plug-ins Package for Linux
:icons: font
:imagesdir: ../media/

[.lead]
You should ensure that the host meets the requirements before installing the SnapCenter Plug-ins Package for Linux.

|===
| Item| Requirements

a|
Operating systems
a|

* Red Hat Enterprise Linux
* Oracle Linux
* SUSE Linux Enterprise Server (SLES)

a|
Minimum RAM for the SnapCenter plug-in on host
a|
1 GB
a|
Minimum install and log space for the SnapCenter plug-in on host
a|
2 GB

NOTE: You should allocate sufficient disk space and monitor the storage consumption by the logs folder. The log space required varies depending on the number of the entities to be protected and the frequency of data protection operations. If there is no sufficient disk space, the logs will not be created for the recently run operations.

a|
Required software packages
a|
Java 1.8 (64-bit)Oracle Java or OpenJDK flavors

If you have upgraded JAVA to the latest version, you must ensure that the JAVA_HOME option located at /var/opt/snapcenter/spl/etc/spl.properties is set to the correct JAVA version and the correct path.

|===

For the latest information about supported versions, see the https://imt.netapp.com/matrix/imt.jsp?components=105308;&solution=1259&isHWU&src=IMT[NetApp Interoperability Matrix Tool]
