---
permalink: protect-scc/snapcenter_custom_plug_ins_overview.html
sidebar: sidebar
keywords: custom plug-ins
summary: 'You can develop custom plug-ins for applications that you use and then use SnapCenter to backup, restore, or clone these applications. Like other SnapCenter plug-ins, your custom plug-ins act as host-side components of the NetApp SnapCenter Software, enabling application-aware data protection and management of resources.'
---
= SnapCenter Custom Plug-ins overview
:icons: font
:imagesdir: ../media/

[.lead]
You can develop custom plug-ins for applications that you use and then use SnapCenter to backup, restore, or clone these applications. Your custom plug-ins act as host-side components of the NetApp SnapCenter Software, enabling application-aware data protection and management of resources.

When custom plug-ins are installed, you can use SnapCenter with NetApp SnapMirror technology to create mirror copies of backup sets on another volume and use NetApp SnapVault technology to perform disk-to-disk backup replication. The custom plug-ins can be used in both Windows and Linux environments.

NOTE: SnapCenterCLI does not support custom plug-ins commands.

You can install the custom plug-in from the Add Host page.

link:add_hosts_and_install_plug_in_packages_on_remote_hosts.html[Add hosts and install plug-in packages on remote hosts.^]

NOTE: SnapCenter support policy will cover support for SnapCenter custom plug-in framework, core engine, and the associated APIs. Support will not cover the plug-in source code and the associated scripts built on the custom plug-in framework.

You can create your own custom plug-ins by referring to link:develop_a_plug_in_for_your_application.html[Develop a plug-in for your application^] guide.
