---
permalink: protect-scc/task_install_the_snapcenter_custom_plug_ins_on_linux_hosts_using_the_command_line_interface.html
sidebar: sidebar
keywords:
summary: 'You should install the SnapCenter Custom Plug-ins by using the SnapCenter user interface (UI). If your environment does not allow remote installation of the plug-in from the SnapCenter UI, you can install the Custom Plug-in either in console mode or in silent mode by using the command-line interface (CLI).'
---
= Install the SnapCenter Custom Plug-ins on Linux hosts by using the command-line interface
:icons: font
:imagesdir: ../media/

[.lead]
You should install the SnapCenter Custom Plug-ins by using the SnapCenter user interface (UI). If your environment does not allow remote installation of the plug-in from the SnapCenter UI, you can install the custom plug-ins either in console mode or in silent mode by using the command-line interface (CLI).

*Steps*

. Copy the SnapCenter Plug-ins Package for Linux installation file (snapcenter_linux_host_plugin.bin) from C:\ProgramData\NetApp\SnapCenter\Package Repository to the host where you want to install the custom plug-ins.
+
You can access this path from the host where the SnapCenter Server is installed.

. From the command prompt, navigate to the directory where you copied the installation file.
. Install the plug-in: `path_to_installation_bin_file/snapcenter_linux_host_plugin.bin -i silent -DPORT=port_number_for_host -DSERVER_IP=server_name_or_ip_address -DSERVER_HTTPS_PORT=port_number_for_server`
 ** -DPORT specifies the SMCore HTTPS communication port.
 ** -DSERVER_IP specifies the SnapCenter Server IP address.
 ** -DSERVER_HTTPS_PORT specifies the SnapCenter Server HTTPS port.
 ** -DUSER_INSTALL_DIR specifies the directory where you want to install the SnapCenter Plug-ins Package for Linux.
 ** DINSTALL_LOG_NAME specifies the name of the log file.

+
----
/tmp/sc-plugin-installer/snapcenter_linux_host_plugin.bin -i silent  -DPORT=8145 -DSERVER_IP=scserver.domain.com -DSERVER_HTTPS_PORT=8146 -DUSER_INSTALL_DIR=/opt -DINSTALL_LOG_NAME=SnapCenter_Linux_Host_Plugin_Install_2.log -DCHOSEN_FEATURE_LIST=CUSTOM
----
. Add the host to the SnapCenter Server using the Add-Smhost cmdlet and the required parameters.
+
The information regarding the parameters that can be used with the command and their descriptions can be obtained by running _Get-Help command_name_. Alternatively, you can also refer to the https://library.netapp.com/ecm/ecm_download_file/ECMLP2885482[SnapCenter Software Cmdlet Reference Guide^].
. Log in to SnapCenter and upload the custom plug-in from the UI or by using PowerShell cmdlets.
+
You can upload the custom plug-in from the UI by referring to link:task_add_hosts_and_install_plug_in_packages_on_remote_hosts_scc.html[Add hosts and install plug-in packages on remote hosts] section.
+
The SnapCenter cmdlet help and the cmdlet reference information contain more information about PowerShell cmdlets.
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2885482[SnapCenter Software Cmdlet Reference Guide^].
