---
permalink: protect-scc/types_of_restore_strategies_supported_for_manually_added_custom_plugin_resources.html
sidebar: sidebar
keywords: SnapCenter
summary: 'You must define a strategy before you can successfully perform restore operations using SnapCenter. There are two types of restore strategies for manually added custom plug-in resources. You cannot recover manually added custom plug-in resources.'
---
= Types of restore strategies supported for manually added custom plug-in resources
:icons: font
:imagesdir: ../media/

[.lead]
You must define a strategy before you can successfully perform restore operations using SnapCenter. There are two types of restore strategies for manually added custom plug-in resources.

NOTE: You cannot recover manually added custom plug-in resources.

== Complete resource restore

* Restores all volumes, qtrees, and LUNs of a resource

NOTE: If the resource contains volumes or qtrees, the Snapshots taken after the Snapshot  selected for restore on such volumes or qtrees are deleted and cannot be recovered. Also, if any other resource is hosted on the same volumes or qtrees, then that resource is also deleted.

== File level restore

* Restores files from volumes, qtrees, or directories
* Restores only the selected LUNs
