---
sidebar: sidebar
permalink: sc-automation/concept_rest_web_services_foundation.html
keywords: uri endpoints, http messages, json format
summary: REST is a style for creating distributed web applications.
---

= REST web services foundation
:icons: font
:imagesdir: ./media/

[.lead]
Representational State Transfer (REST) is a style for creating distributed web applications. When applied to the design of a web services API, it establishes a set of technologies and best practices for exposing server-based resources and managing their states. It uses mainstream protocols and standards to provide a flexible foundation for managing SnapCenter.

== Resources and state representation

Resources are the basic components of a web-based system. When creating a REST web services application, early design tasks include:

* Identification of system or server-based resources
+
Every system uses and maintains resources. A resource can be a file, business transaction, process, or administrative entity. One of the first tasks in designing an application based on REST web services is to identify the resources.

* Definition of resource states and associated state operations
+
Resources are always in one of a finite number of states. The states, as well as the associated operations used to affect the state changes, should be clearly defined.

== URI endpoints

Every REST resource must be defined and made available using a well-defined addressing scheme.  The endpoints where the resources are located and identified use a Uniform Resource Identifier (URI).

The URI provides a general framework for creating a unique name for each resource in the network. The Uniform Resource Locator (URL) is a type of URI used with web services to identify and access resources. Resources are typically exposed in a hierarchical structure similar to a file directory.

== HTTP messages

Hypertext Transfer Protocol (HTTP) is the protocol used by the web services client and server to exchange request and response messages about the resources.

As part of designing a web services application, HTTP methods are mapped to the resources and corresponding state management actions. HTTP is stateless. Therefore, to associate a set of related requests and responses as part of one transaction, additional information must be included in the HTTP headers carried with the request and response data flows.

== JSON formatting

While information can be structured and transferred between a web services client and server in several ways, the most popular option is JavaScript Object Notation (JSON).

JSON is an industry standard for representing simple data structures in plain text and is used to transfer state information describing the resources. The SnapCenter REST API uses JSON to format the data carried in the body of each HTTP request and response.
