---
permalink: sc-automation/task_how to_access_rest_apis_using_the_swagger_api_web_page.html
sidebar: sidebar
keywords: REST API, Swagger
summary: 'REST APIs are exposed through the Swagger web page. You can access the Swagger web page to display the SnapCenter Server REST APIs, as well as to manually issue an API call. You can use REST APIs to help manage your SnapCenter Server or to perform data protection operations.'
---
= How to access REST APIs using the Swagger API web page
:icons: font
:imagesdir: ../media/

[.lead]
REST APIs are exposed through the Swagger web page. You can access the Swagger web page to display the SnapCenter Server REST APIs, as well as to manually issue an API call. You can use REST APIs to help manage your SnapCenter Server or to perform data protection operations.

You should know the management IP address or domain name of the SnapCenter Server on which you want to execute the REST APIs.

You do not need special permissions to run the REST API client. Any user can access the Swagger web page. The respective permissions on the objects that are accessed via the REST API are based on the user who generates the token to login to the REST API.

*Steps*

. From a browser, enter the URL to access the Swagger web page in the format _\https://<SnapCenter_IP_address_or_name>:<SnapCenter_port>/swagger/_.
+
NOTE: Ensure that the REST API URL does not have the following characters: +, ., %, and &.

. In the *Swagger Explore* field, if the Swagger API documentation does not display automatically, type:
_\https://<SnapCenter_IP_address_or_name>:<SnapCenter_port>/Content/swagger/SnapCenter.yaml_

 . Click *Explore*.
+
A list of API resource types or categories are displayed.

. Click an API resource type to display the APIs in that resource type.

If you encounter unexpected behavior when executing SnapCenter REST APIs, you can use the log files to identify the cause and resolve the problem.
You can download the log files from the SnapCenter user interface by clicking *Monitor* > *Logs* > *Download*.
