---
permalink: protect-scsql/task_configure_group_managed_service_account_on_windows_server_2012_or_later.html
sidebar: sidebar
keywords: 
summary: 'Windows Server 2012 or later enables you to create a group Managed Service Account \(gMSA\) that provides automated service account password management from a managed domain account.'
---
= Configure group Managed Service Account on Windows Server 2012 or later
:icons: font
:imagesdir: ../media/

[.lead]
Windows Server 2012 or later enables you to create a group Managed Service Account (gMSA) that provides automated service account password management from a managed domain account.

* You should have a Windows Server 2012 or later domain controller.
* You should be a Windows Server 2012 or later domain member with permissions to set up and administer the gMSA.
* The specified gMSA account will be used to run the plug-in services such as SnapCenter Plug-in for Microsoft Windows and SnapCenter Plug-in for Microsoft SQL Server services. In Windows cluster, the specified gMSA service account is used to run the plug-in services on all the cluster.
* For SnapCenter Plug-in for Exchange, SnapCenter Plug-in for SAP HANA databases, and SnapCenter Custom Plug-ins, gMSA is applicable to only on the Windows machine (local system).
* Configuring a gMSA eliminates the need for administrators to manually administer passwords for these accounts.
* SQL deployments with gMSA is supported.
* gMSA can be used to login to SQL Server instance.
* You cannot use a gMSA on storage systems configured with RPC protocol settings.

nodes.

. Create a KDS root key to generate unique passwords for each object in your gMSA.
. For each domain, run the following command from the Windows Server 2012 domain controller,: Add-KDSRootKey -EffectiveImmediately
. Create and configure your gMSA:.
 .. Create a user group account with administrator and domain administrator privileges.
 .. Add computer objects to the group.
 .. Use the user group you just created to create the gMSA.
+
For example, `New-ADServiceAccount -name <ServiceAccountName> -DNSHostName <fqdn> -PrincipalsAllowedToRetrieveManagedPassword <group> -ServicePrincipalNames <SPN1,SPN2,…>`

 .. Run Get-ADServiceAccount command to verify the service account.
. Configure the gMSA on your hosts:
 .. Enable the Active Directory module for Windows PowerShell on the host where you want to use the gMSA account.
+
To do this, run the following command from PowerShell:
+
----
PS C:\> Get-WindowsFeature AD-Domain-Services

Display Name                           Name                Install State
------------                           ----                -------------
[ ] Active Directory Domain Services   AD-Domain-Services  Available


PS C:\> Install-WindowsFeature AD-DOMAIN-SERVICES

Success Restart Needed Exit Code      Feature Result
------- -------------- ---------      --------------
True    No             Success        {Active Directory Domain Services, Active ...
WARNING: Windows automatic updating is not enabled. To ensure that your newly-installed role or feature is
automatically updated, turn on Windows Update.
----
+
NOTE:

  *** To add the gMSA account, you should be logged in as the administrator.
  *** For a cluster, all the nodes should be added or provided with admin privileges.

 .. Restart your host.
 .. Install the gMSA on your host by running the following command from the PowerShell command prompt:Install-AdServiceAccount <gMSA>
 .. Verify your gMSA account by running the following command: Test-AdServiceAccount <gMSA>
. Add the Windows host with your new gMSA account in the SnapCenter Server.
+
SnapCenter Server will install the plug-in services selected using the specified gMSA account.
