Windows Server 2012 or later enables you to create a group Managed Service Account (gMSA) that provides automated service account password management from a managed domain account.

*What you will need*

* You should have a Windows Server 2012 or later domain controller.
* You should have a Windows Server 2012 or later host, which is a member of the domain.
* The specified gMSA account will be used to run the plug-in services such as SnapCenter Plug-in for Microsoft Windows and SnapCenter Plug-in for Microsoft SQL Server services.
* For Windows cluster, the specified gMSA should have the administrative rights on all the nodes of the cluster.
* For SnapCenter Plug-in for Exchange, SnapCenter Plug-in for SAP HANA databases, and SnapCenter Custom Plug-ins, gMSA is applicable to only on the Windows machine (local system).
* Configuring a gMSA eliminates the need for administrators to manually administer passwords for these accounts.
* SQL deployments with gMSA is supported.
* gMSA can be used to login to SQL Server instance.

*Steps*

. Create a KDS root key to generate unique passwords for each object in your gMSA.
. For each domain, run the following command from the Windows domain controller: Add-KDSRootKey -EffectiveImmediately
. Create and configure your gMSA:
 .. Create a user group account.
 .. Add computer objects to the group.
 .. Use the user group you just created to create the gMSA.
+
For example, `New-ADServiceAccount -name <ServiceAccountName> -DNSHostName <fqdn> -PrincipalsAllowedToRetrieveManagedPassword <group> -ServicePrincipalNames <SPN1,SPN2,…>`

 .. Run Get-ADServiceAccount command to verify the service account.
. Configure the gMSA on your hosts:
 .. Enable the Active Directory module for Windows PowerShell on the host where you want to use the gMSA account.
+
To do this, run the following command from PowerShell:
+
----
PS C:\> Get-WindowsFeature AD-Domain-Services

Display Name                           Name                Install State
------------                           ----                -------------
[ ] Active Directory Domain Services   AD-Domain-Services  Available


PS C:\> Install-WindowsFeature AD-DOMAIN-SERVICES

Success Restart Needed Exit Code      Feature Result
------- -------------- ---------      --------------
True    No             Success        {Active Directory Domain Services, Active ...
WARNING: Windows automatic updating is not enabled. To ensure that your newly-installed role or feature is
automatically updated, turn on Windows Update.
----


 .. Restart your host.
 .. Install the gMSA on your host by running the following command from the PowerShell command prompt:Install-AdServiceAccount <gMSA>
 .. Verify your gMSA account by running the following command: Test-AdServiceAccount <gMSA>
. Assign the administrative privileges to the configured gMSA on the host.
. Add the Windows host by specifying the configured gMSA account in the SnapCenter Server.
+
SnapCenter Server will install the selected plug-ins on the host and the specified gMSA will be used as the service log on account during the plug-in installation.
