You must create a storage virtual machine (SVM) connection and a credential before using PowerShell cmdlets to perform data protection operations.

*What you will need*

* You should have prepared the PowerShell environment to execute the PowerShell cmdlets.
* You should have the required permissions in the Infrastructure Admin role to create storage connections.
* You should ensure that the plug-in installations are not in progress.
+
Host plug-in installations must not be in progress while adding a storage system connection because the host cache might not be updated and databases status might be displayed in the SnapCenter GUI as "`Not available for backup`" or "`Not on NetApp storage`".

* Storage system names should be unique.
+
SnapCenter does not support multiple storage systems with the same name on different clusters. Each storage system that is supported by SnapCenter should have a unique name and a unique management LIF IP address.

*Steps*

. Initiate a PowerShell connection session by using the Open-SmConnection cmdlet.
+
This example opens a PowerShell session:
+
----
PS C:\> Open-SmConnection
----

. Create a new connection to the storage system by using the Add-SmStorageConnection cmdlet.
+
This example creates a new storage system connection:
+
----
PS C:\> Add-SmStorageConnection -Storage test_vs1 -Protocol Https
-Timeout 60
----

. Create a new credential by using the Add-SmCredential cmdlet.
+
This example creates a new credential named FinanceAdmin with Windows credentials:
+
----
PS C:> Add-SmCredential -Name FinanceAdmin -AuthMode Windows
-Credential sddev\administrator
----

The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running _Get-Help command_name_. Alternatively, you can also refer to the https://library.netapp.com/ecm/ecm_download_file/ECMLP2877143[SnapCenter Software Cmdlet Reference Guide^].
