---
permalink: protect-azure/backup-sap-hana-resource-groups.html
sidebar: sidebar
keywords: SnapCenter Plug-in for SAP HANA Database, back up, resource groups
summary: 'A resource group is a collection of resources on a host. A backup operation on the resource group is performed on all resources defined in the resource group.'
---

= Back up SAP HANA resource groups
:icons: font
:imagesdir: ../media/

[.lead]
A resource group is a collection of resources on a host. A backup operation on the resource group is performed on all resources defined in the resource group.

.Steps

. In the left navigation pane, select *Resources*, and then select the appropriate plug-in from the list.
. In the Resources page, select *Resource Group* from the *View* list.
. In the Resource Groups page, select the resource group that you want to back up, and then select *Back up Now*.
. In the Backup page, perform the following steps:
.. If multiple policies are associated with the resource group, from the *Policy* drop-down list, select the policy that you want to use for backup.
+
If the policy selected for the on-demand backup is associated with a backup schedule, the on-demand backups will be retained based on the retention settings specified for the schedule type.

.. Select *Backup*.
. Monitor the operation progress by selecting *Monitor* > *Jobs*.
