---
permalink: protect-azure/create-azure-credential.html
sidebar: sidebar
keywords: snapcenter, azure, azure credential
summary: 'Create the Azure credential in SnapCenter to access the Azure NetApp account.'
---

= Create the Azure credential in SnapCenter
:icons: font
:imagesdir: ../media/

[.lead]
You should create the Azure credential in SnapCenter to access the Azure NetApp account. 

Before creating the Azure credential, ensure that you have created the service principal in Azure. The tenant ID, client ID, and secret key associated with the service principal will be required to create the Azure credential.
* The *Tenant ID* can be found in the Azure Portal on the Overview page for Entra ID. 
* The *Client ID* is also known as the Application ID for the Enterprise App/Service Principal. This can be found in the Azure Portal on the Overview page for the Enterprise Application you've created to act as the Service Principal for SnapCenter.
* The *Client Secret Key* is also known as the *Secret Value*. You can create this client secret in the Azure Portal by navigating to *App registrations* under Entra ID. After selecting the Enterprise App you've created, navigate to *Certificates & secrets* and then *+ New client secret*. Note: The secret value will only be accessable when initially created and can not be accessed again later. 
* The Service Principal will also need permissions granted, the role of Contributor will allow the service principal to perform required actions in Azure. This can be granted from the Access Control (IAM) page within the Subscription page.  

.Steps

. In the left navigation pane, click *Settings*.
. In the Settings page, click *Credential*.
. Click *New*.
. In the Credential page, specify the following information required to create the credential.
+
|===
| For this field...| Do this...

a|
Credential Name
a|
Enter a name for the credential.
a|
Authentication Mode
a|
Select *Azure Credential* from the drop-down list.
a|
Tenant ID
a|
Enter the tenant ID.
a|
Client ID
a|
Enter the client ID.
a|
Client Secret Key
a|
Enter the client secret key.
|===
. Click *OK*.
