---
permalink: protect-azure/create-azure-credential.html
sidebar: sidebar
keywords: snapcenter, azure, azure credential
summary: Create the Azure credential in SnapCenter to access the Azure NetApp account.

---
= Create the Azure credential in SnapCenter
:icons: font
:imagesdir: ../media/

[.lead]
You should create the Azure credential in SnapCenter to access the Azure NetApp account. 

Before creating the Azure credential, ensure that you have created the service principal in Azure. The tenant ID, client ID, and secret key associated with the service principal will be required to create the Azure credential.

.Steps

. In the left navigation pane, click *Settings*.
. In the Settings page, click *Credential*.
. Click *New*.
. In the Credential page, specify the following information required to create the credential.
+
|===
| For this field...| Do this...

a|
Credential Name
a|
Enter a name for the credential.
a|
Authentication Mode
a|
Select *Azure Credential* from the drop-down list.
a|
Tenant ID
a|
Enter the tenant ID.
a|
Client ID
a|
Enter the client ID.
a|
Client Secret Key
a|
Enter the client secret key.
|===
. Click *OK*.
