---
permalink: protect-azure/create-credential-add-plugin-host.html
sidebar: sidebar
keywords: snapcenter, azure, credential, plug-in host
summary: Create the credential to add the plug-in host.

---
= Create the credential to add the plug-in host
:icons: font
:imagesdir: ../media/

[.lead]
SnapCenter uses credentials to authenticate users for SnapCenter operations. 

You should create credentials for installing SnapCenter plug-ins and additional credentials for performing data protection operations.

.Steps

. In the left navigation pane, click *Settings*.
. In the Settings page, click *Credential*.
. Click *New*.
. In the Credential page, specify the following information required to create the credential.
+
|===
| For this field...| Do this...

a|
Credential Name
a|
Enter a name for the credential.
a|
Authentication Mode
a|
Select the authentication mode from the drop-down list.
a|
Authentication Type
a|
Select either *Password Based* or *SSH Key Based* (only for Linux host).
a|
Username
a|
Specify the username.
a|
Password
a|
If you have selected Password based authentication, specify the password.
a|
SSH Private Key
a|
If you have selected SSH Key Based authentication, specify the private key.
a|
Use sudo privileges
a|
Select the Use sudo privileges check box if you are creating credentials for a non-root user.

NOTE: This is applicable only for Linux users.
|===
. Click *OK*.