---
permalink: protect-azure/install-snapcenter-azure-virtual-machine.html
sidebar: sidebar
keywords: snapcenter server, azure virtual machine, install
summary: 'Download and install SnapCenter on Azure Virtual Machine.'
---

= Install SnapCenter on Azure Virtual Machine
:icons: font
:imagesdir: ../media/

[.lead]
You can download the SnapCenter software from the NetApp Support site and install the software on the Azure virtual machine.

.Before you begin

* Ensure that the Azure Windows virtual machine meets the requirements for SnapCenter Server installation. For information, see link:../install/requirements-to-install-snapcenter-server.html[Requirements to install SnapCenter Server].
* If you are new to Azure NetApp Files and do not have an existing NetApp account, ensure that you have registered so that you can access the SnapCenter Software. For inforamtion, see link:../install/register_enable_software_access.html[Register to access the SnapCenter software].

.Steps

. Download the SnapCenter Server installation package from https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab[NetApp Support Site].
. Initiate the SnapCenter Server installation by double-clicking the downloaded .exe file.
+
After you initiate the installation, all the pre-checks are performed and if the minimum requirements are not met appropriate error or warning messages are displayed. You can ignore the warning messages and proceed with installation; however, errors should be fixed.
. Review the pre-populated values required for the SnapCenter Server installation and modify if required.
+
You do not have to specify the password for MySQL Server repository database. During SnapCenter Server installation the password is auto generated.
+
NOTE: The special character “%” is not supported in the custom path for the repository database. If you include “%” in the path, installation fails.
. Click *Install Now*.
+
If you have specified any values that are invalid, appropriate error messages will be displayed. You should re-enter the values, and then initiate the installation.
+
NOTE: If you click the *Cancel* button, the step that is being executed will be completed, and then start the rollback operation. The SnapCenter Server will be completely removed from the host.
+
However, if you click *Cancel* when "SnapCenter Server site restart" or "Waiting for SnapCenter Server to start" operations are being performed, installation will proceed without cancelling the operation.

== Register the product to enable support

If you are new to NetApp and do not have an existing NetApp account, you should register the product to enable support.

.Steps

. After installing SnapCenter, navigate to *Help > About*.
. In the _About SnapCenter_ dialog box, make a note of the SnapCenter Instance, a 20 digit number that starts with 971.
. Click https://register.netapp.com.
. Click *I am not a registered NetApp Customer*.
. Specify your details to register yourself.
. Leave the NetApp Reference SN field blank.
. Select *SnapCenter* from the Product Line drop-down.
. Select the billing provider.
. Enter the 20-digit SnapCenter instance ID.
. Click *Submit*.

