---
permalink: tech-refresh/task_tech_refresh_storage_system.html
sidebar: sidebar
keywords: tech refresh, storage system,
summary: 'Perform tech refresh of storage system by moving the data from old storage to new storage, mounting the new storage to the respective hosts, and then bringing up the databases.'
---

= Tech refresh of storage system

:icons: font
:imagesdir: ../media/

[.lead]

When the storage is tech refreshed, the data is migrated to new storage and the application hosts are mounted with new storage. The SnapCenter backup job identifies the new storage and creates the snapshot provided the new storage is registered in SnapCenter.

You can perform restore, mount, and clone on the new backups created after storage refresh. However these operations fail when performed on the backups that were created before storage refresh because the backups has the old storage details. 

You should run the storage tech refresh API or cmdlet to update the old backups in SnapCenter with the new storage details.

Tech refresh is supported for the following SnapCenter Plug-ins:

* SnapCenter Plug-in for Microsoft SQL Server
* SnapCenter Plug-in for Windows
* SnapCenter Plug-in for Oracle Database
* SnapCenter Plug-in for SAP HANA Database
* SnapCenter Plug-in for Microsoft Exchange Server

The supported use cases are:

* Primary storage refresh
* Secondary storage refresh (fan out case as well)

The supported scenarios are:

* Cluster name change
* SVM name change
* Volume name change
* Data can be moved over a period of time, for example: few volumes in a SVM is moved or few databases are migrated to the new storage.

== Update the backups of the primary storage

When the storage is tech refreshed, you should run the storage tech refresh API or cmdlet to update the old backups in SnapCenter with the new storage details.


.Before you begin

* Add the new storage in SnapCenter.
* Mount the new storage in the respective hosts and bring up the databases.
+
The new storage needs to be mounted on the same drive or path.
* Create one backup of each resource to find the latest storage foot print.
* Unique SVM name
** If all the volumes of the SVM can be migrated before executing the server refresh, then it is recommended to delete the SVM in old cluster and rediscover the old cluster in SnapCenter which will remove the SVM from cache.
** If all the volumes of the SVM cannot be migrated before executing the server refresh in SC, then it is recommended to use different SVM name in new cluster.

.Steps

. Migrate the data from old storage to new storage.
+
For information on how to migrate the date, refer to KB: <<link to be included>>.
. Suspend all the scheduled jobs.
. Mount the new storage to the plug-in host.
. Put the host in production mode.
. In SnapCenter, create a backup of the resources whose storage is migrated.
. Run the storage refresh API: `/5.0/techrefresh/primarystorage` or the cmdlet: _Invoke-SmTechRefreshPrimaryStorage_.
+
NOTE: The dry run is enabled by default and resources are identified for which the storage is updated. You can verify the resources by running either the API: '/jobs/{jobid}' or the cmdlet _Get-SmJobSummaryReport_. 