---
permalink: tech-refresh/task_tech_refresh_server_host.html
sidebar: sidebar
keywords: tech refresh, SnapCenter Server, cmdlet, APIs, F5, rollback, decommission, disaster recovery, standalone
summary: 'Install the same version of SnapCenter Server on the new host and then run the APIs or execute cmdlets to backup the SnapCenter from old server and restore it in on the new server.'
---

= Tech refresh of SnapCenter Server host

:icons: font
:imagesdir: ../media/

[.lead]

When the SnapCenter Server host requires refresh, you can install the same version of SnapCenter Server on the new host and then run the APIs to backup the SnapCenter from old server and restore it in on the new server.

.Steps

. Deploy the new host and perform the following tasks:
.. Install the same version of the SnapCenter Server.
.. (Optional) Configure CA certificates and enable two-way SSL. For more information, refer to https://docs.netapp.com/us-en/snapcenter/install/reference_generate_CA_certificate_CSR_file.html[Configure CA Certificate] and https://docs.netapp.com/us-en/snapcenter/install/task_configure_two_way_ssl.html[Configure and enable two-way SSL].
.. (Optional) Configure multi-factor authentication. For more information, refer to https://docs.netapp.com/us-en/snapcenter/install/enable_multifactor_authentication.html[Enable multi-factor authentication].
. Log in as the SnapCenter Admin user.
. Create a backup of the SnapCenter Server on the old host using either the API: `/<snapcenter_version>/server/backup` or the cmdlet: _New-SmServerBackup_.
+
NOTE: Before taking the backup, suspend all the scheduled jobs and ensure that no jobs are running.
+
IMPORTANT: If you want to restore the backup on the SnapCenter Server that is running on a new domain, before taking a backup you should add the new domain user in the old SnapCenter host and assign the SnapCenter admin role.
. Copy the backup from the old host to new host.
. Restore the backup of the SnapCenter Server on the new host using either the API: `/<snapcenter_version>/server/restore` or the cmdlet: _Restore-SmServerBackup_.
+
Restore will update the new SnapCenter Server URL in all the hosts by default. If you want to skip the update, use the _-SkipSMSURLInHosts_ attribute and separately update the server URL by running using either the API: `/<snapcenter_version>/server/configureurl` or the cmdlet: _Set-SmServerConfig_.
+ 
NOTE: If the plug-in host is not able to resolve the server hostname, log in to each of the plug-in host and add the _etc/host_ entry for the new IP in the <New IP> SC_Server_Name format.
+
NOTE: The server _etc/host_ entries will not be restored. You can restore it manually from the old server.
+
If the backup is restored on the SnpCenter Server that is running on a new domain and if you want to continue to use the old domain users, you should register the old domain in the new SnapCenter Server.
+
NOTE: If you have manually updated the web.config file in old SnapCenter host, the updates will not be copied to the new host. You should manually make the same changes in the web.config file of the new host.
. If you have skipped updating the SnapCenter Server URL or any of the host was down during the restore process, update the new server name in all the hosts or specified hosts that are managed by the SnapCenter using either the API: `/<snapcenter_version>/server/configureurl` or the cmdlet: _Set-SmServerConfig_.
. Activate the scheduled jobs on all the hosts from the new SnapCenter Server.

== Tech refresh of a node in F5 cluster

You can do tech refresh of any node in the F5 cluster by removing the node and adding the new node. If the node that needs to be refreshed is active, make another node of the cluster as active and then remove the node.

For information on how to add a node to F5 cluster, refer to https://docs.netapp.com/us-en/snapcenter/install/concept_configure_snapcenter_servers_for_high_availabiity_using_f5.html[Configure SnapCenter Servers for High Availability using F5].

NOTE: If the url of the F5 cluster changes, the url can be updated in all the hosts using either the API: `/<snapcenter_version>/server/configureurl` or the cmdlet: _Set-SmServerConfig_.

== Decommissioning the old SnapCenter Server host

You can remove the old SnapCenter Server host after verifying that the new SnapCenter Server is up and running and all the plug-in hosts are able to communicate with the the new SnapCenter Server host.

== Rollback to the old SnapCenter Server host

In case of any issues, you can bring back the old SnapCenter Server host by updating the SnapCenter Server URL in all the hosts using either the API: `/<snapcenter_version>/server/configureurl` or the cmdlet: _Set-SmServerConfig_.

== Disaster recovery

=== Disaster recovery of standalone SnapCenter host

You can perform disaster recovery by restoring the server backup to the new host.

.Before you begin

Ensure that you have a backup of the old SnapCenter Server.

.Steps

. Deploy the new host and perform the following tasks:
.. Install the same version of the SnapCenter Server.
.. Configure CA certificates and enable two-way SSL. For more information, refer to https://docs.netapp.com/us-en/snapcenter/install/reference_generate_CA_certificate_CSR_file.html[Configure CA Certificate] and https://docs.netapp.com/us-en/snapcenter/install/task_configure_two_way_ssl.html[Configure and enable two-way SSL].
. Copy the old SnapCenter Server backup to the new host.
. Log in as the SnapCenter Admin user.
. Restore the backup of the SnapCenter Server on the new host using either the API: `/<snapcenter_version>/server/restore` or the cmdlet: _Restore-SmServerBackup_.
+
Restore will update the new SnapCenter Server URL in all the hosts by default. If you want to skip the update, use the _-SkipSMSURLInHosts_ attribute and separately update the server URL by using either the API: `/<snapcenter_version>/server/configureurl` or the cmdlet: _Set-SmServerConfig_.
+ 
NOTE: If the plug-in host is not able to resolve the server hostname, log in to each of the plug-in host and add the _etc/host_ entry for the new IP in the <New IP> SC_Server_Name format.
+
NOTE: The server _etc/host_ entries will not be restored. You can restore it manually from the old server.
. If you have skipped updating the URL or any of the host was down during the restore process, update the new server name in all the hosts or specified hosts that are managed by the SnapCenter using either the API: `/<snapcenter_version>/server/configureurl` or the cmdlet: _Set-SmServerConfig_.

=== Disaster recovery of SnapCenter F5 cluster

You can perform disaster recovery by restoring the server backup to the new host and then converting the standalone host to a cluster.

.Before you begin

Ensure that you have a backup of the old SnapCenter Server.

.Steps

. Deploy the new host and perform the following tasks:
.. Install the same version of the SnapCenter Server.
.. Configure CA certificates and enable two-way SSL. For more information, refer to https://docs.netapp.com/us-en/snapcenter/install/reference_generate_CA_certificate_CSR_file.html[Configure CA Certificate] and https://docs.netapp.com/us-en/snapcenter/install/task_configure_two_way_ssl.html[Configure and enable two-way SSL].
. Copy the old SnapCenter Server backup to the new host.
. Log in as the SnapCenter Admin user.
. Restore the backup of the SnapCenter Server on the new host using either the API: `/<snapcenter_version>/server/restore` or the cmdlet: _Restore-SmServerBackup_.
+
Restore will update the new SnapCenter Server URL in all the hosts by default. If you want to skip the update, use the _-SkipSMSURLInHosts_ attribute and separately update the server URL by using either the API: `/<snapcenter_version>/server/configureurl` or the cmdlet: _Set-SmServerConfig_.
+ 
NOTE: If the plug-in host is not able to resolve the server hostname, log in to each of the plug-in host and add the _etc/host_ entry for the new IP in the <New IP> SC_Server_Name format.
+
NOTE: The server _etc/host_ entries will not be restored. You can restore it manually from the old server.
. If you have skipped updating the URL or any of the host was down during the restore process, update the new server name in all the hosts or specified hosts that are managed by the SnapCenter using either the API: `/<snapcenter_version>/server/configureurl` or the cmdlet: _Set-SmServerConfig_.
. Convert the standalone host to F5 cluster.
+
For information on how to configure F5, refer to https://docs.netapp.com/us-en/snapcenter/install/concept_configure_snapcenter_servers_for_high_availabiity_using_f5.html[Configure SnapCenter Servers for High Availability using F5].

.Related information

For information on the APIs, you need to access the Swagger page. see link:https://docs.netapp.com/us-en/snapcenter/sc-automation/task_how%20to_access_rest_apis_using_the_swagger_api_web_page.html[How to access REST APIs using the swagger API web page].

The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running _Get-Help command_name_. Alternatively, you can also refer the https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html[SnapCenter Software Cmdlet Reference Guide^].