---
permalink: tech-refresh/task_tech_refresh_plugin_host.html
sidebar: sidebar
keywords: tech refresh, plug-in host, supported plug-ins, prerequisites to refresh plug-in hosts, application hosts, limitations for tech refresh of plug-in hosts
summary: 'Move the resources from old host to new host to perform tech refresh of the plug-in hosts.'
---

= Tech refresh of SnapCenter plug-in hosts

:icons: font
:imagesdir: ../media/

[.lead]

When the SnapCenter plug-in hosts require refresh, you should move the resources from old host to new host. When the new host is added to SnapCenter, SnapCenter will discover all the resources but will be treated as new resources.

.About this task

Tech refresh is supported for the following SnapCenter Plug-ins:

* SnapCenter Plug-in for Microsoft SQL Server
* SnapCenter Plug-in for Windows
* SnapCenter Plug-in for Oracle Database
* SnapCenter Plug-in for SAP HANA Database

The supported use cases are:

* Migrating resources from one host to another host.
* Migrating resources from multiple hosts to one or fewer hosts.
* Migrating resources from one host to multiple hosts.

NOTE: The new host can have a different name or same name. After adding the new host with same name, you can also rename the existing host. 

You should run the APIs or cmdlets which will take old host name and new host name as input, compare the resources by name, and relink the objects of matching resources from old host to new host. The matching resources will be marked as protected.

* The _IsDryRun_ parameter is set to True by default and this re-links the objects of matching resources from old host to new host.
* The _AutoMigrateManuallyAddedResources_ parameter is set to True by default and this automatically copies the manually added resources from old host to the new host.

.Before you begin

* You should bring up the required databases in the new host from the same storage.
** You should check for the compatibility if there is a change in application version.
** You should mount the storage on the same drive or path in the new host.
** If storage DR is enabled, the respective storage should be mounted in the new host.
* You should add the new host to SnapCenter.

.Steps

. Deploy the new host and install the application.
. Suspend the schedules of the old host.
. Move the required resources from the old host to the new host. 
+
For information on how to move to resources, refer to KB: <<link to be included>>.
. Add the new host to SnapCenter.
. Verify if all the resources are discovered.
. Run the host refresh API: `/5.0/hosts/TechRefresh/` or the cmdlet: _Invoke-SmHostTechRefresh_.
+
NOTE: The dry run is enabled by default and the matching resources to be relinked are identified. You can verify the resources by running either the API: '/jobs/{jobid}' or the cmdlet _Get-SmJobSummaryReport_. 
+
If you have migrated the resources from multiple hosts, you should run the API or the cmdlet for all the hosts.
+
If you want to migrate to multiple hosts, you should perform all the steps from step 1 for all the hosts. The resources can be moved one at a time. You can run the API or cmdlet on the same host multiple times, it will relink only if there is a new resource identified.
. Remove the old host or hosts from SnapCenter.

.Related information

For information on the APIs , you need to access the Swagger page. see link:https://docs.netapp.com/us-en/snapcenter/sc-automation/task_how%20to_access_rest_apis_using_the_swagger_api_web_page.html[How to access REST APIs using the swagger API web page].

The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running _Get-Help command_name_. Alternatively, you can also refer the https://library.netapp.com/ecm/ecm_download_file/ECMLP2886205[SnapCenter Software Cmdlet Reference Guide^].




   