---
permalink: tech-refresh/task_tech_refresh_storage_system.html
sidebar: sidebar
keywords: tech refresh, storage system
summary: 'Install the same version of SnapCenter Server on the new host and then run the APIs to backup the SnapCenter from old server and restore it in on the new server.'
---

= Tech refresh of storage system

:icons: font
:imagesdir: ../media/

[.lead]

When the SnapCenter Server host requires refresh, you can install the same version of SnapCenter Server on the new host and then run the APIs to backup the SnapCenter from old server and restore it in on the new server.

.About this task

* For an F5 setup, restore operation is performed as stand-alone, you should run a set of commands to create the F5 again. See, Link: https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/How_to_Migrate_SnapCenter_migrate_to_another_Server[How to migrate SnapCenter to another server^]

* Repository backup schedule will be restored only if you install the SnapCenter Plug-in for Windows and attach NetApp LUN to the server machine.

* If the DLLs are corrupt, you can attempt to repair SnapCenter Server or correct the faulty installation.

* If NSM or config files are corrupt, you can uninstall and reinstall the SnapCenter Server with the same version.

* If the VM is corrupt, bring up another VM or a machine with the same name and install SnapCenter Server with the same version.

.Before you begin

* Install CA certificates, if applicable.
* If 2-way SSL is enabled and if the new server name is different, you should push the new certificate to the hosts.

.Steps

. Deploy the new host and install the same version of the SnapCenter Server.
. If the old server is available, create a backup of the SnapCenter Server on the old host.
+
`/4.5/disasterrecovery/server/backup`
+
NOTE: Before taking the backup, ensure the no jobs are running and all the scheduled jobs are suspended.
. Restore the backup of the SnapCenter Server on the new host.
+
`/4.5/disasterrecovery/server/restore`
+ 
If the plug-in is not able to resolve the server hostname, log in to each of the plug-in host and add the etc/host entry for the new IP in the <New IP> SC_Server_Name format.
For example, `10.225.81.35 SCServer1`
+
The server etc/host entries will not be restored. You can restore it manually from the DR backup folder.
. Run the _Set-SmServerConfig_ cmdlet to update the new server name in all the hosts or specified hosts that are managed by the SnapCenter.
+
If any of the host is down during the restore process, it cannot update the server URL on those hosts.
. Activate the scheduled jobs on all the hosts.
+
|===
|Description|REST API|HTTP method

a|
Fetch existing SnapCenter Server DR backups

You should provide the target path where the DR backups are stored.
a|
`/4.5/disasterrecovery/server/backup?targetpath={path}`
a|
GET
a|
Create a new Server DR backup.
a|
`/4.5/disasterrecovery/server/backup`
a|
POST
a|
Restores a SnapCenter Server from a specified Server DR backup.
a|
`/4.5/disasterrecovery/server/restore`
a|
POST
a|
Delete the Server DR backup based on backup name.
a|
``/4.5/disasterrecovery/server/backup``
a|
DELETE
|===