---
permalink: admin/concept_manage_the_storage_system.html
sidebar: sidebar
keywords: Manage storage system
summary: 'After adding the storage system, you can modify the storage system configuration and connections, or delete the storage system.'
---
= Manage the storage system
:icons: font
:imagesdir: ../media/

[.lead]
After adding the storage system, you can modify the storage system configuration and connections, or delete the storage system.


== Modify storage system configuration

You can use SnapCenter to modify your storage system configuration if you want to change the user name, password, platform, port, protocol, timeout period, preferred IP address, or messaging options.

*About this task*

You can modify storage connections for an individual user or for a group. If you belong to one or more groups with permission to the same storage system, the storage connection name is displayed multiple times in the storage connection list, once for each group with permission to the storage system.

*Steps*

. In the left navigation pane, click *Storage Systems*.
. In the Storage Systems page, from the *Type* drop-down perform one of the following actions:
+
|===
| Select... | Steps...

a|
ONTAP SVMs
a|
To view all the storage virtual machines (SVMs) that were added, and to modify the required SVM configuration.

 . In the Storage Connections page, click the appropriate SVM name.
 . Perform one of the following actions:
  * If the SVM is not part of any cluster, in the Modify Storage System page, modify the configurations such as user name, password, EMS and AutoSupport settings, platform, protocol, port, timeout, and preferred IP.
  * If the SVM is part of a cluster, then in the Modify Storage System page, select *Manage SVM Independently* and modify the configurations such as user name, password, EMS and AutoSupport settings, platform, protocol, port, timeout, and preferred IP.
+
After modifying the SVM to be managed independently, if you decide to manage it through cluster, you should delete the SVM and then click *Rediscover*. The SVM will be added to the ONTAP cluster.
+
NOTE: When a storage system password is updated on SnapCenter GUI, you should restart the SMCore services of the respective plug-in or the server host because the updated password does not reflect in SMCore, and the backup jobs will fail with an incorrect credential error.

a|
ONTAP Clusters
a|
To view all the clusters that were added and modify the required cluster configuration.

 . In the Storage Connections page, click the cluster name.
 . In the Modify Storage System page, click the edit icon next to Username and modify the user name and password.
 . Select or clear the EMS and AutoSupport settings.
 . Click *More Options* and modify other configurations such as platform, protocol, port, timeout, and preferred IP.
|===
. Click *Submit*.

== Delete the storage system

You can use SnapCenter to delete any unused storage system.

*About this task*

You can delete storage connections for an individual user or for a group. If you belong to one or more groups with permission to the same storage system, the storage system name is displayed multiple times in the storage connection list, once for each group with permission to the storage system.

IMPORTANT: When you are deleting a storage system, all operations that are being performed on that storage system will fail.

*Steps*

. In the left navigation pane, click *Storage Systems*.
. In the Storage Systems page, from the *Type* drop-down, select either *ONTAP SVMs* or *ONTAP Clusters*.
. In the Storage Connections page, either select the check box next to the SVM, or the cluster that you want to delete.
+
NOTE: You cannot select the SVM that is part of a cluster.

. Click *Delete*.
. In the Delete Storage System Connection Settings page, click *OK*.
+
NOTE: If an SVM is deleted from ONTAP cluster using ONTAP GUI, in the SnapCenter GUI click *Rediscover* to update the SVM list.

== REST API support 

All storage connections to ONTAP and ASA.r2 storage systems will go through ZAPI by default.  REST API can be enabled for select ONTAP versions.  
+
You can modify the config keys in the following configuration files:
* IsRestEnabledForStorageConnection 
+
Default value is false.
* MinOntapVersionToUseREST
+
Default value is 9.13.1.

.Enable connection through REST API
. Set IsRestEnabledForStorageConnection to true.
. Add the key in SMCoreServiceHost.dll.config and SnapDriveService.dll.config on both the server and the Windows plug-in hosts.
+
_<add key="IsRestEnabledForStorageConnection" value="true" />_

.Limit connection through REST API to specific version of ONTAP
. Set the config parameter MinOntapVersionToUseREST to true.
. Add the key in SMCoreServiceHost.dll.config and SnapDriveService.dll.config on both the server and the Windows plug-in hosts.
+
_<add key="MinOntapVersionToUseREST" value="9.13.1" />_
. Restart the service for SmCore on the server and the plug-in and SnapDrive service on the plug-in machine.
