---
permalink: admin/concept_monitor_snapcenter_logs.html
sidebar: sidebar
keywords: 
summary: 'You can view and download SnapCenter Server logs, SnapCenter host agent logs, and plug-in logs. You might want to view the logs to help with troubleshooting.'
---
= Monitor SnapCenter logs
:icons: font
:imagesdir: ../media/

[.lead]
You can view and download SnapCenter Server logs, SnapCenter host agent logs, and plug-in logs. You might want to view the logs to help with troubleshooting.

You can filter the logs to show only a specific log severity level:

* Debug
* Info
* Warn
* Error
* Fatal

You can also obtain job level logs: for example, logs that help you troubleshoot the reason for a backup job failure. For job level logs, use the *Monitor* > *Jobs* option.

*Steps*

. In the left navigation pane, click *Monitor*.
. In the Jobs page, select a job and click Download logs.
+
The downloaded zipped folder contains the job logs and the common logs. The zipped folder name contains the job id and job type selected.

. In the Monitor page, click *Logs*.
. Select the log type, host, and instance.
+
If you select log type is *plugin*, you can select a host or SnapCenter plug-in. You cannot do this if the log type is *server*.

. To filter the logs by a specific source, message, or log level, click the filter icon at the top of the column heading.
+
To show all logs, choose *Greater than or equal to* as the "`Debug`" level.

. Click *Refresh*.
. View the list of logs.
. Click *Download* to download the logs.
+
The downloaded zipped folder contains the job logs and the common logs. The zipped folder name contains the job id and job type selected.

In large configurations for optimum performance, you should set the log settings for SnapCenter to minimal level by using the PowerShell cmdlet. `Set-SmLogSettings -LogLevel All -MaxFileSize 10MB -MaxSizeRollBackups 10 -JobLogsMaxFileSize 10MB -Server`

NOTE: To access health or configuration information after a failover job finishes, run the cmdlet Get-SmRepositoryConfig.

The information regarding the parameters that can be used with the command and their descriptions can be obtained by running helpcommand_name. Alternatively, you can also refer to the _Command Reference Guide_.

https://library.netapp.com/ecm/ecm_download_file/ECMLP2874310[SnapCenter Software 4.4 Cmdlet Reference Guide]
