---
permalink: admin/concept_monitor_jobs_schedules_events_and_logs.html
sidebar: sidebar
keywords: Monitor jobs, schedules, events, logs
summary: 'You can monitor the progress of your jobs, get information about scheduled jobs, and review events and logs from the Monitor page.'
---
= Monitor jobs, schedules, events, and logs
:icons: font
:imagesdir: ../media/

[.lead]
You can monitor the progress of your jobs, get information about scheduled jobs, and review events and logs from the Monitor page.

== Monitor jobs

You can view information about SnapCenter backup, clone, restore, and verification jobs. You can filter this view based on start and end date, type of job, resource group, policy, or SnapCenter plug-in. You can also get additional details and log files for specified jobs.

You can also monitor jobs related to SnapMirror and SnapVault operations.

NOTE: You can monitor only the jobs that you created and that are relevant to you unless you are assigned SnapCenter Admin or another super user role.

You can perform the following tasks related to monitoring jobs:

* Monitor backup, clone, restore, and verification operations.
* View job details and reports.
* Stop a scheduled job.

=== Manage scheduled backup jobs

Beginning with SnapCenter 6.0.1 release, a new parameter *JobConcurrencyThreshold* has been introduced that sets a threshold to the number of scheduled jobs that can run at any given time. This allows you to control the number of backups you want to run based on your systems hardware configuration.

The default value assigned to *JobConcurrencyThreshold* is 0 and is disabled. You can enable by assigning a value, if you observe performance degradation during the scheduled backup window.

NOTE: If you enable *JobConcurrencyThreshold* to manage concurrent jobs, SnapCenter will not allow you to control the order of the backups and the backups might not be triggered at the same time specified in the schedule.

.Steps

. Set the value of _JobConcurrencyThreshold_ parameter located at _C:\Program Files\NetApp\SnapCenter WebApp\SnapManager.Web.UI.dll.config_.
. Recycle the SnapCenter application pool by clicking IIS > Application Pools > SnapCenter > Restart.
. Restart the SnapCenter Web service by clicking IIS > Sites > SnapCenter > Restart.

=== Manage stale jobs

Stale jobs are created from interruptions in SnapCenter or from improper job updates. Beginning with SnapCenter 6.0.1 release, a predefined schedule is introduced to clean up these stale jobs that are stuck for more than 72 hours. You can change the schedule frequency by editing the configurable parameter *CleanUpStaleJobsIntervalHours*.

You can trigger the clean up on demand by running the schedule from *Monitor* > *Schedules* > *SnapCenter_StaleJobCleanUp*.

.Steps

. Set the value of _CleanUpStaleJobsIntervalHours_ parameter located at _C:\Program Files\NetApp\SnapCenter WebApp\SnapManager.Web.UI.dll.config_.
. Recycle the SnapCenter application pool by clicking IIS > Application Pools > SnapCenter > Restart.
. Restart the SnapCenter Web service by clicking IIS > Sites > SnapCenter > Restart.

== Monitor schedules

You might want to view current schedules to determine when the operation starts, when it was last run, and when it runs next. You can also determine the host on which the operation runs, along with the operation's resource group and policy information.

*Steps*

. In the left navigation pane, click *Monitor*.
. In the Monitor page, click *Schedules*.
. Select the resource group and the schedule type.
. View the list of scheduled operations.

== Monitor events

You can view a list of SnapCenter events in the system, such as when a user creates a resource group or when the system initiates activities, such as creating a scheduled backup. You might want to view events to determine if an operation such as a backup or a restore operation is currently in progress.

*About this task*

All job information appears in the Events page. For example, when a backup job starts, a "`backup start`" event appears. When the backup completes, a "`backup complete`" event appears.

*Steps*

. In the left navigation pane, click *Monitor*.
. In the Monitor page, click *Events*.
. (Optional) In the Filter box, enter the start or end date, category of event (such as backup, resource group, or policy) and severity level, and click *Apply*. Alternatively, enter characters in the Search box.
. View the list of events.

== Monitor logs

You can view and download SnapCenter Server logs, SnapCenter host agent logs, and plug-in logs. You might want to view the logs to help with troubleshooting.

*About this task*

You can filter the logs to show only a specific log severity level:

* Debug
* Info
* Warn
* Error
* Fatal

You can also obtain job level logs, for example, logs that help you troubleshoot the reason for a backup job failure. For job level logs, use the *Monitor* > *Jobs* option.

*Steps*

. In the left navigation pane, click *Monitor*.
. In the Jobs page, select a job and click Download logs.
+
The downloaded zipped folder contains the job logs and the common logs. The zipped folder name contains the job id and job type selected.

. In the Monitor page, click *Logs*.
. Select the log type, host, and instance.
+
If you select log type as *plugin*, you can select a host or SnapCenter plug-in. You cannot do this if the log type is *server*.

. To filter the logs by a specific source, message, or log level, click the filter icon at the top of the column heading.
+
To show all logs, choose *Greater than or equal to* as the `Debug` level.

. Click *Refresh*.
. View the list of logs.
. Click *Download* to download the logs.
+
The downloaded zipped folder contains the job logs and the common logs. The zipped folder name contains the job id and job type selected.

In large configurations for optimum performance, you should set the log settings for SnapCenter to minimal level by using the PowerShell cmdlet.

`Set-SmLogSettings -LogLevel All -MaxFileSize 10MB -MaxSizeRollBackups 10 -JobLogsMaxFileSize 10MB -Server`

NOTE: To access health or configuration information after a failover job finishes, run the cmdlet `Get-SmRepositoryConfig`.

== Remove jobs and logs from SnapCenter

You can remove backup, restore, clone, and verification jobs and logs from SnapCenter. SnapCenter stores successful and failed job logs indefinitely unless you remove them. You might want to remove them to replenish storage.

*About this task*

There must be no jobs currently in operation.
You can remove a specific job by providing a Job ID or you can remove jobs within a specified period.

You do not need to place the host in maintenance mode to remove jobs.

*Steps*

. Launch PowerShell.
. From the command prompt, enter: `Open-SMConnection`
. From the command prompt, enter: `Remove-SmJobs`
. In the left navigation pane, click *Monitor*.
. In the Monitor page, click *Jobs*.
. In the Jobs page, review the status of the job.

.Related information

The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running _Get-Help command_name_. Alternatively, you can also refer to the https://docs.netapp.com/us-en/snapcenter-cmdlets/index.html[SnapCenter Software Cmdlet Reference Guide^].
