---
permalink: admin/concept_manage_ems_data_collection.html
sidebar: sidebar
keywords:
summary: 'You can schedule and manage Event Management System (EMS) data collection using PowerShell cmdlets. EMS data collection involves gathering details about the SnapCenter Server, the installed SnapCenter plug-in packages, the hosts, and similar information, and then sending it to a specified ONTAP storage virtual machine \(SVM\).'
---
= Manage EMS data collection
:icons: font
:imagesdir: ../media/

[.lead]
You can schedule and manage Event Management System (EMS) data collection using PowerShell cmdlets. EMS data collection involves gathering details about the SnapCenter Server, the installed SnapCenter plug-in packages, the hosts, and similar information, and then sending it to a specified ONTAP storage virtual machine (SVM).

NOTE: System CPU utilization is high when data-collection task is in progress. CPU utilization remains high as long as the operation is progress irrespective of the data size.

== Stop EMS data collection

EMS data collection is enabled by default and runs every seven days after your installation date. You can disable data collection at any time by using the PowerShell cmdlet `Disable-SmDataCollectionEMS`.

*Steps*

. From a PowerShell command line, establish a session with SnapCenter by entering `Open-SmConnection`.
. Disable EMS data collection by entering `Disable-SmDataCollectionEms`.

== Start EMS data collection

EMS data collection is enabled by default and is scheduled to run every seven days from the installation date. If you have disabled it, you can start EMS data collection again by using the `Enable-SmDataCollectionEMS` cmdlet.

The Data ONTAP event generate-autosupport-log permission has been granted to the storage virtual machine (SVM) user.

*Steps*

. From a PowerShell command line, establish a session with SnapCenter by entering `Open-SmConnection`.
. Enable EMS data collection by entering `Enable-SmDataCollectionEMS`.

== Change EMS data collection schedule and target SVM

You can use PowerShell cmdlets to change the EMS data collection schedule or the target storage virtual machine (SVM).

*Steps*

. From a PowerShell command line, to establish a session with SnapCenter, enter the `Open-SmConnection` cmdlet.
. To change the EMS data collection target, enter the `Set-SmDataCollectionEmsTarget` cmdlet.
. To change the EMS data collection schedule, enter the `Set-SmDataCollectionEmsSchedule` cmdlet.

== Monitor EMS data collection status

You can monitor the status of your EMS data collection using several PowerShell cmdlets. You can get information about the schedule, storage virtual machine (SVM) target, and status.

*Steps*

. From a PowerShell command line, establish a session with SnapCenter by entering `Open-SmConnection`.
. Retrieve information about the EMS data collection schedule by entering `Get-SmDataCollectionEmsSchedule`.
. Retrieve information about the EMS data collection status by entering `Get-SmDataCollectionEmsStatus`.
. Retrieve information about the EMS data collection target by entering `Get-SmDataCollectionEmsTarget`.

*Find more infromation*

The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running _Get-Help command_name_. Alternatively, you can also refer to the https://library.netapp.com/ecm/ecm_download_file/ECMLP2877143[SnapCenter Software Cmdlet Reference Guide^].
