---
permalink: admin/concept_manage_hosts.html
sidebar: sidebar
keywords: 
summary: 'You can add hosts and install SnapCenter plug-in packages, add a verification server, remove hosts, migrate backup jobs, and update host to upgrade plug-in packages or add new plug-in packages. Depending on the plug-in you are using, you can also provision disks, manage SMB shares, manage initiator groups \(igroups\), manage iSCSI sessions, and migrate data.'
---
= Manage hosts
:icons: font
:imagesdir: ../media/

[.lead]
You can add hosts and install SnapCenter plug-in packages, add a verification server, remove hosts, migrate backup jobs, and update host to upgrade plug-in packages or add new plug-in packages. Depending on the plug-in you are using, you can also provision disks, manage SMB shares, manage initiator groups (igroups), manage iSCSI sessions, and migrate data.

|===
| You can perform these tasks...| For Microsoft Exchange Server| For Microsoft SQL Server| For Microsoft Windows| For Oracle Database| For SAP HANA Database| For Custom Plug-ins
a|
Add hosts and install plug-in package
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Update ESXi information for a host
a|
 
a|
Yes
a|
 
a|
 
a|
 
a|
 
a|
Suspend schedules and place hosts in maintenance mode
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Modify hosts by adding, upgrading, or removing plug-ins
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Remove hosts from SnapCenter
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Start plug-in services
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Yes
a|
Provision disks: create, resize, connect to, and delete disks
a|
 
a|
 
a|
Yes
a|
 
a|
 
a|
 
a|
Manage SMB shares: create, delete, and get information about
a|
 
a|
 
a|
Yes
a|
 
a|
 
a|
 
a|
Manage iGroups: create, rename, delete, and get information about
a|
 
a|
 
a|
Yes
a|
 
a|
 
a|
 
a|
Manage iSCSI sessions: establish and disconnect from an iSCSI session, and get information about
a|
 
a|
 
a|
Yes
a|
 
a|
 
a|
 
|===
For SnapCenter 4.1.1 users, the SnapCenter Plug-in for VMware vSphere 4.1.1 documentation has information on protecting virtualized databases and file systems. For SnapCenter 4.2.x users, the NetApp Data Broker 1.0 and 1.0.1, documentation has information on protecting virtualized databases and file systems using the SnapCenter Plug-in for VMware vSphere that is provided by the Linux-based NetApp Data Broker virtual appliance (Open Virtual Appliance format). For SnapCenter 4.3.x users, the SnapCenter Plug-in for VMware vSphere 4.3 documentation has information on protecting virtualized databases and file systems using the Linux-based SnapCenter Plug-in for VMware vSphere virtual appliance (Open Virtual Appliance format).

https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_register_snapcenter_plugin_vmware_vsphere_with_snapcenter_server.html[SnapCenter Plug-in for VMware vSphere Data Protection Guide]

*Related information*

http://docs.netapp.com/ocsc-44/topic/com.netapp.doc.ocsc-isg/home.html[Installing and setting up SnapCenter]
