---
permalink: admin/concept_monitor_snapcenter_events.html
sidebar: sidebar
keywords: 
summary: 'You can view a list of SnapCenter events in the system, such as when a user creates a resource group or when the system initiates activities, such as creating a scheduled backup. You might want to view events to determine if an operation such as a backup or a restore operation is currently in progress.'
---
= Monitor SnapCenter events
:icons: font
:imagesdir: ../media/

[.lead]
You can view a list of SnapCenter events in the system, such as when a user creates a resource group or when the system initiates activities, such as creating a scheduled backup. You might want to view events to determine if an operation such as a backup or a restore operation is currently in progress.

*About this task*

All job information appears in the Events page. For example, when a backup job starts, a "`backup start`" event appears. When the backup completes, a "`backup complete`" event appears.

*Steps*

. In the left navigation pane, click *Monitor*.
. In the Monitor page, click *Events*.
. Optional. In the Filter box, enter the start or end date, category of event (such as backup, resource group, or policy) and severity level, and click *Apply*. Alternatively, enter characters in the Search box.
. View the list of events.
