---
permalink: admin/concept_manage_configuration_checker.html
sidebar: sidebar
keywords: 
summary: 'You can create a new schedule, view, modify, delete, disable, or run the schedules for multiple hosts simultaneously.'
---
= Manage Configuration Checker
:icons: font
:imagesdir: ../media/

[.lead]
You can create a new schedule, view, modify, delete, disable, or run the schedules for multiple hosts simultaneously.

After installing SnapCenter Server when you log in for the first time, a default configuration checker schedule is created with the following characteristics:

* You cannot create additional schedules for SnapCenter Server.
* You cannot delete the default schedule.
* Only a SnapCenter administrator can modify or disable the default schedule.

When a plug-in host is added to the SnapCenter Server, Configuration Checker is triggered and alerts are generated. You can create only one schedule for the plug-in host, which you can modify, delete, or disable.

NOTE: Configuration Checker is not supported for AIX hosts.
