---
permalink: admin/task_configure_the_option_to_email_reports.html
sidebar: sidebar
keywords: 
summary: 'If you want to have regular SnapCenter data protection job updates sent to yourself or to others so that you can monitor the status of those updates, you can configure the option to email the SnapCenter reports when you are creating a resource group.'
---
= Configure the option to email reports
:icons: font
:imagesdir: ../media/

[.lead]
If you want to have regular SnapCenter data protection job updates sent to yourself or to others so that you can monitor the status of those updates, you can configure the option to email the SnapCenter reports when you are creating a resource group.

You must have configured your SMTP server on the Global Settings page under Settings.

. In the left navigation pane, click *Resources*, and then select the appropriate plug-in from the list.
. Select the type of resource you want to view and click *New Resource Group*, or select an existing resource group and click *Modify* to configure email reports for an existing resource group.
. In the Notification panel of the New Resource Group wizard, select from the pull-down menu whether you want to receive reports always, on failure, or on failure or warning.
. Enter the address the email is sent from, the address the email is sent to, and the subject of the email.
