---
permalink: admin/task_uninstalling_the_snapcenter_server.html
sidebar: sidebar
keywords: uninstall
summary: 'If you no longer wish to use the SnapCenter Server to manage data protection jobs, you can uninstall SnapCenter Server using the Programs and Features Control Panel on the SnapCenter Server host. Uninstalling the SnapCenter Server removes all its components.'
---
= Uninstall the SnapCenter Server
:icons: font
:imagesdir: ../media/

[.lead]
If you no longer wish to use the SnapCenter Server to manage data protection jobs, you can uninstall SnapCenter Server using the Programs and Features Control Panel on the SnapCenter Server host. Uninstalling the SnapCenter Server removes all its components.

* Ensure that you have at least 2 GB of free space on the drive where the SnapCenter Server is installed.
* Ensure that the domain in which the SnapCenter Server is installed is not removed.
+
If you remove the domain where the SnapCenter Server was installed and then try to uinstall, the operation fails.

* You should have backed up the repository database because the repository database will be cleaned up and uninstalled.

. On the SnapCenter Server host, navigate to the Control Panel.
. Make sure you are in the *Category* view.
. Under Programs, click *Uninstall a program*.
+
Programs and Features window opens.

. Select NetApp SnapCenter Server, and then click *Uninstall*.
+
From SnapCenter 4.2, when you uninstall the SnapCenter Server, all it's components including the MySQL Server repository database is uninstalled.

* Removing the NLB node from an NLB cluster requires that you restart the SnapCenter Server host. If you do not restart the host, you might experience a failure if you attempt to reinstall the SnapCenter Server.
* You should manually uninstall .NET Framework which is not removed during uninstallation.
