---
permalink: admin/task_delete_resource_groups.html
sidebar: sidebar
keywords: 
summary: 'You can delete a resource group if you no longer need to protect the resources in the resource group. You must ensure that resource groups are deleted before you remove plug-ins from SnapCenter.'
---
= Delete resource groups
:icons: font
:imagesdir: ../media/

[.lead]
You can delete a resource group if you no longer need to protect the resources in the resource group. You must ensure that resource groups are deleted before you remove plug-ins from SnapCenter.

If you are managing SQL or Windows file system resources, you must have manually deleted all clones created for any of the resources in the resource group.

You can optionally force the deletion of all backups, metadata, policies, and Snapshot copies associated with the resource group.

NOTE: In a SnapVault relationship, the last Snapshot copy cannot be deleted; therefore, the resource group cannot be deleted. Before deleting a resource group that is part of a SnapVault relationship, you must remove the SnapVault relationship and then delete the last Snapshot copy.

. In the left navigation pane, click *Resources*, and then select the appropriate plug-in from the list.
. In the Resources page, select *Resource Group* from the *View* list.
. Select the resource group, and then click *Delete*.
. Optional: Select the *Delete backups and detach policies associated with this Resource Group* check box to remove all backups, metadata, policies, and Snapshot copies associated with the resource group.
. Click *OK*.
