---
permalink: admin/task_restore_a_snapcenter_database_repository_backup.html
sidebar: sidebar
keywords: 
summary: 'You can restore the SnapCenter repository by running the Restore-SmRepositoryBackup cmdlet.'
---
= Restore the SnapCenter database repository
:icons: font
:imagesdir: ../media/

[.lead]
You can restore the SnapCenter repository by running the Restore-SmRepositoryBackup cmdlet.

When you are restoring the SnapCenter repository, other SnapCenter operations that are running will be impacted because during the restore operation the repository database is not accessible.

. Launch PowerShell.
. From the command prompt, enter the following cmdlet, and then provide credentials to connect to the SnapCenter Server: `Open-SMConnection`
. Restore the respository backup using the Restore-SmRepositoryBackup cmdlet.
+
The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running Get-Helpcommand_name. Alternatively, you can also refer to the _Cmdlet Reference Guide_.
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2874310[SnapCenter Software 4.4 Cmdlet Reference Guide]

The following cmdlet restores the SnapCenter MySQL database repository from the backups existing on either iSCSI LUN or VMDK:

----
C:\PS>Restore-SmRepositoryBackup -BackupName MYSQL_DS_SC_Repository_mva-x3550-s09_09-15-2016_10.32.00.4445
----

The following cmdlet restores the SnapCenter MySQL database when backup files are deleted accidentally in the iSCSI LUN. For VMDK manually restore the backup from ONTAP Snapshot copies.

----
C:\PS>Restore-SmRepositoryBackup -BackupName MYSQL_DS_SC_Repository_mva-x3550-s09_09-15-2016_10.32.00.4445 -RestoreFileSystem
----
