---
permalink: admin/task_refresh_virutal_machine_information.html
sidebar: sidebar
keywords: 
summary: 'You must refresh your virtual machine information when VMware vCenter credentials change or the database or file system host restarts.'
---
= Refresh virtual machine information
:icons: font
:imagesdir: ../media/

[.lead]
You must refresh your virtual machine information when VMware vCenter credentials change or the database or file system host restarts.

Refreshing your virtual machine information in SnapCenter initiates communication with the VMware vSphere vCenter and obtains vCenter credentials.

RDM-based disks are managed by the SnapCenter Plug-in for Microsoft Windows, which is installed on the database host. To manage RDMs, the SnapCenter Plug-in for Microsoft Windows communicates with the vCenter server that manages the database host.

. In the SnapCenter left navigation pane, click *Hosts*.
. In the Hosts page, click *Managed Hosts*.
. In the Managed Hosts page, select the host you want to update.
. Click *Refresh VM*.
