---
permalink: admin/task_access_rest_apis_using_the_swagger_api_web_page.html
sidebar: sidebar
keywords: 
summary: 'REST APIs are exposed through the Swagger web page. You can access the Swagger web page to display the SnapCenter Server REST APIs, as well as to manually issue an API call. You can use REST APIs to help manage your SnapCenter Server or to perform data protection operations.'
---
= Access REST APIs using the Swagger API web page
:icons: font
:imagesdir: ../media/

[.lead]
REST APIs are exposed through the Swagger web page. You can access the Swagger web page to display the SnapCenter Server REST APIs, as well as to manually issue an API call. You can use REST APIs to help manage your SnapCenter Server or to perform data protection operations.

You must know the management IP address or domain name of the SnapCenter Server on which you want to execute the REST APIs.

You do not need special permissions to run the REST API client. Any user can access the Swagger web page. The respective permissions on the objects that are accessed via the REST API are based on the user who generates the token to login to the REST API.

. From a browser, enter the URL to access the Swagger web page in the format https://<SnapCenter_IP_address_or_name>:8146/swagger/.
+
NOTE: Ensure that the REST API URL does not have the following characters: +, ., %, and &.
+
Access SnapCenter Server REST APIs:
+
----
https://192.0.2.85:8146/swagger/
----
+
----
https://netapp_host_domain:8146/swagger/
----

. If the Swagger API documentation does not display automatically, in the Swagger Explore field, type the URL to the location of the Swagger documentation: https://<SnapCenter_IP_address_or_name>:8146/Content/swagger/SnapCenter.yaml or https://<vCenter_host_IP_address>:8146/Content/swagger/SnapCenter.yaml, and click *Explore*.
+
A list of API resource types, or categories, is displayed.

. Click an API resource type to display the APIs in that resource type.
