---
permalink: admin/task_monitor_ems_data_collection_status.html
sidebar: sidebar
keywords: 
summary: 'You can monitor the status of your EMS data collection using several PowerShell cmdlets. You can get information about the schedule, storage virtual machine \(SVM\) target, and status.'
---
= Monitor EMS data collection status
:icons: font
:imagesdir: ../media/

[.lead]
You can monitor the status of your EMS data collection using several PowerShell cmdlets. You can get information about the schedule, storage virtual machine (SVM) target, and status.

. From a PowerShell command line, establish a session with SnapCenter by entering Open-SmConnection.
. Retrieve information about the EMS data collection schedule by entering Get-SmDataCollectionEmsSchedule.
. Retrieve information about the EMS data collection status by entering Get-SmDataCollectionEmsStatus.
. Retrieve information about the EMS data collection target by entering Get-SmDataCollectionEmsTarget.
+
The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running Get-Helpcommand_name. Alternatively, you can also refer to the _Cmdlet Reference Guide_.
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2874310[SnapCenter Software 4.4 Cmdlet Reference Guide]
