---
permalink: admin/task_remove_jobs_and_logs_from_snapcenter.html
sidebar: sidebar
keywords: 
summary: 'You can remove backup, restore, clone, and verification jobs and logs from SnapCenter. SnapCenter stores successful and failed job logs indefinitely unless you remove them. You might want to remove them to replenish storage.'
---
= Remove jobs and logs from SnapCenter
:icons: font
:imagesdir: ../media/

[.lead]
You can remove backup, restore, clone, and verification jobs and logs from SnapCenter. SnapCenter stores successful and failed job logs indefinitely unless you remove them. You might want to remove them to replenish storage.

There must be no jobs currently in operation.

You can remove a specific job by providing a Job ID or you can remove jobs within a specified period.

You do not need to place the host in maintenance mode to remove jobs.

The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running Get-Helpcommand_name. Alternatively, you can also refer to the _Cmdlet Reference Guide_.

https://library.netapp.com/ecm/ecm_download_file/ECMLP2874310[SnapCenter Software 4.4 Cmdlet Reference Guide]

. Launch PowerShell.
. From the command prompt, enter:
+
----
Open-SMConnection
----

. From the command prompt, enter:
+
----
Remove-SmJobs
----

. In the left navigation pane, click *Monitor*.
. In the Monitor page, click *Jobs*.
. In the Jobs page, review the status of the job.
