---
permalink: admin/task_set_the_smtp_server_for_email_notifications.html
sidebar: sidebar
keywords: SnapCenter
summary: 'You can specify the SMTP server to use for sending data protection job reports to yourself or to others. You can also send a test email to verify the configuration. The settings are applied globally for any SnapCenter job for which you configure email notification.'
---
= Set the SMTP server for email notifications
:icons: font
:imagesdir: ../media/

[.lead]
You can specify the SMTP server to use for sending data protection job reports to yourself or to others. You can also send a test email to verify the configuration. The settings are applied globally for any SnapCenter job for which you configure email notification.

This option configures the SMTP server for sending all data protection job reports. However, if you want to have regular SnapCenter data protection job updates for a particular resource sent to yourself or to others so that you can monitor the status of those updates, you can configure the option to email the SnapCenter reports when you are creating a resource group.

. In the left navigation pane, click *Settings*.
. In the Settings page, click *Global Settings*.
. Enter the SMTP server and click *Save*.
. To send a test email, enter the email address from and to which you will send the email, enter the subject, and click *Send*.
