---
permalink: admin/task_start_ems_data_collection.html
sidebar: sidebar
keywords: 
summary: 'EMS data collection is enabled by default and is scheduled to run every seven days from the installation date. If you have disabled it, you can start EMS data collection again by using the Enable-SmDataCollectionEMS cmdlet.'
---
= Start EMS data collection
:icons: font
:imagesdir: ../media/

[.lead]
EMS data collection is enabled by default and is scheduled to run every seven days from the installation date. If you have disabled it, you can start EMS data collection again by using the Enable-SmDataCollectionEMS cmdlet.

The Data ONTAP event generate-autosupport-log permission has been granted to the storage virtual machine (SVM) user.

. From a PowerShell command line, establish a session with SnapCenter by entering Open-SmConnection.
. Enable EMS data collection by entering Enable-SmDataCollectionEMS.
+
The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running Get-Helpcommand_name. Alternatively, you can also refer to the _Cmdlet Reference Guide_.
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2874310[SnapCenter Software 4.4 Cmdlet Reference Guide]
