---
permalink: admin/task_view_backups_of_the_snapcenter_repository.html
sidebar: sidebar
keywords: 
summary: 'You can display a list of SnapCenter Server database repository backups by running the Get-SmRepositoryBackups cmdlet.'
---
= View backups of the SnapCenter repository
:icons: font
:imagesdir: ../media/

[.lead]
You can display a list of SnapCenter Server database repository backups by running the Get-SmRepositoryBackups cmdlet.

The repository backups are created according to the schedule specified in the Protect-SmRepository cmdlet.

. Launch PowerShell.
. From the command prompt, enter the following cmdlet, and then provide credentials to connect to the SnapCenter Server: `Open-SMConnection`
. List all available SnapCenter database backups using the Get-SmRepositoryBackups cmdlet.
+
The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running Get-Helpcommand_name. Alternatively, you can also refer to the _Cmdlet Reference Guide_.
+
https://library.netapp.com/ecm/ecm_download_file/ECMLP2874310[SnapCenter Software 4.4 Cmdlet Reference Guide]
