---
permalink: protect-postgresql/storage-types-supported-by-snapcenter-plug-in-for-postgresql.html
sidebar: sidebar
keywords: storage types, 
summary: 'SnapCenter supports a wide range of storage types on both physical machines and virtual machines (VMs). You must verify the support for your storage type before installing SnapCenter Plug-in for PostgreSQL.'
---
= Storage types supported by SnapCenter Plug-in for PostgreSQL
:icons: font
:imagesdir: ../media/

[.lead]
SnapCenter supports a wide range of storage types on both physical machines and virtual machines (VMs). You must verify the support for your storage type before installing SnapCenter Plug-in for PostgreSQL.

|===
| Machine | Storage type

a|
Physical server
a|
* FC-connected LUNs
* iSCSI-connected LUNs
* NFS-connected volumes
* NVMe-FC
* NVMe-TCP
a|
VMware ESXi
a|
* RDM LUNs connected by an FC or iSCSI ESXi HBAScanning of host bus adapters (HBAs) might take long time to complete because SnapCenter scans all the host bus adaptors present in the host.
+
You can edit the *LinuxConfig.pm* file located at _/opt/NetApp/snapcenter/spl/plugins/scu/scucore/modules/SCU/Config_ to set the value of the *SCSI_HOSTS_OPTIMIZED_RESCAN* parameter to 1 to rescan only those HBAs that are listed in HBA_DRIVER_NAMES.
* iSCSI LUNs connected directly to the guest system by the iSCSI initiator
* VMDKs on NFS datastores
* VMDKs on VMFS created over NVMe-TCP
* NFS volumes connected directly to the guest system
* vVol datastores on both NFS and SAN
+
vVol datastore can only be provisioned with ONTAP Tools for VMware vSphere.
|===
