---
permalink: install/concept_snapcenter_licenses.html
sidebar: sidebar
keywords: licenses, FAS, AFF, ASA, SnapMirror, SnapVault, SnapRestore, FlexClone, SMBR, Single Mailbox Recovery
summary: 'SnapCenter requires several licenses to enable data protection operations. The type of SnapCenter licenses you install depends on your storage environment and the features that you want to use.'
---
= SnapCenter licenses
:icons: font
:imagesdir: ../media/

[.lead]
SnapCenter requires several licenses to enable data protection of applications, databases, file systems, and virtual machines. The type of SnapCenter licenses you install depends on your storage environment and the features that you want to use.

|===
| License | Where required

a|
SnapCenter Standard controller-based
a|
Required for FAS, AFF, All SAN Array (ASA)

SnapCenter Standard license is a controller-based license and is included as part of the ONTAP One. If you have the SnapManager Suite license, you also get the SnapCenter Standard license entitlement. If you want to install SnapCenter on a trial basis with FAS, AFF, or ASA storage, you can obtain a ONTAP One evaluation license by contacting the sales representative.

For information on licenses included with ONTAP One, refer to https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one[Licenses included with ONTAP One].

NOTE: SnapCenter is also offered as part of data protection bundle. If you have purchased A400 or later, you should purchase the data protection bundle.

a|
SnapMirror or SnapVault
a|
ONTAP

Either SnapMirror or SnapVault license is required if replication is enabled in SnapCenter.

a|
SnapRestore
a|
Required to restore and verify backups.

On primary storage systems

* Required on SnapVault destination systems to perform remote verification and to restore from a backup.
* Required on SnapMirror destination systems to perform remote verification.

a|
FlexClone
a|
Required to clone databases and verification operations.

On primary and secondary storage systems

* Required on SnapVault destination systems to create clones from secondary vault backup.
* Required on SnapMirror destination systems to create clones from secondary SnapMirror backup.

a|
Protocols
a|

* iSCSI or FC license for LUNs
* CIFS license for SMB shares
* NFS license for NFS type VMDKs
* iSCSI or FC license for VMFS type VMDKs

Required on SnapMirror destination systems to serve data if a source volume is unavailable.

a|
SnapCenter Standard licenses (optional)
a|
Secondary destinations

NOTE: It is recommended, but not required, that you add SnapCenter Standard licenses to secondary destinations. If SnapCenter Standard licenses are not enabled on secondary destinations, you cannot use SnapCenter to backup resources on the secondary destination after performing a failover operation. However, a FlexClone license is required on secondary destinations to perform clone and verification operations.
|===

NOTE: SnapCenter Advanced and SnapCenter NAS File Services licenses are deprecated, and are no longer available. The capacity-based license is no longer required for Amazon FSx for NetApp ONTAP, ONTAP Select, and Cloud Volumes ONTAP. The standard licenses and capacity-based license is not required for Azure NetApp Files.

You should install one or more SnapCenter licenses. For information on how to add licenses, see link:../install/concept_snapcenter_standard_controller_based_licenses.html[Add SnapCenter Standard controller-based licenses].

== Single Mailbox Recovery (SMBR) licenses
If you are using SnapCenter Plug-in for Exchange to manage Microsoft Exchange Server databases and Single Mailbox Recovery (SMBR), you would need additional license for SMBR which needs to be purchased separately based on user mailbox.

NetApp® Single Mailbox Recovery has come to the end of availability (EOA) on May 12, 2023. For more information, refer link:https://mysupport.netapp.com/info/communications/ECMLP2885729.html[CPC-00507]. NetApp will continue to support customers that have purchased mailbox capacity, maintenance, and support through marketing part numbers introduced on June 24, 2020, for the duration of the support entitlement.

NetApp Single Mailbox Recovery is a partner product provided by Ontrack. Ontrack PowerControls offers capabilities that are similar to those of NetApp Single Mailbox Recovery. Customers can procure new Ontrack PowerControls software licenses and Ontrack PowerControls maintenance and support renewals from Ontrack (through licensingteam@ontrack.com) for granular mailbox recovery after the May 12, 2023, EOA date.
