---
permalink: install/concept_svm_connections_and_credentials.html
sidebar: sidebar
keywords: SVM, storage virtual machine, credentials
summary: 'Before performing data protection operations, you should set up the storage virtual machine (SVM) connections and add the credentials that the SnapCenter Server and the SnapCenter plug-ins will use.'
---
= Storage Virtual Machine connections and credentials
:icons: font
:imagesdir: ../media/

[.lead]
Before performing data protection operations, you should set up the storage virtual machine (SVM) connections and add the credentials that the SnapCenter Server and the SnapCenter plug-ins will use.

* SVM connections
+
SVM connections give the SnapCenter Server and SnapCenter plug-ins access to the ONTAP storage. Setting up these connections also involves configuring AutoSupport and Event Management System (EMS) features.

* Credentials
 ** Domain administrator or any member of the administrator group
+
Specify the domain administrator or any member of the administrator group on the system on which you are installing the SnapCenter plug-in. Valid formats for the Username field are:

  *** `NetBIOS\UserName`
  *** `Domain FQDN\UserName`
  *** `UserName@upn`

 ** Local administrator (for workgroups only)
+
For systems that belong to a workgroup, specify the built-in local administrator on the system on which you are installing the SnapCenter plug-in. You can specify a local user account that belongs to the local administrators group if the user account has elevated privileges or the User Access control feature is disabled on the host system.

The valid format for the Username field is: `UserName`

 ** Credentials for individual resource groups
+
If you set up credentials for individual resource groups and the username does not have full admin privileges, you must assign at least the resource group and backup privileges to the username.
