---
permalink: install/concept_snapcenter_licenses.html
sidebar: sidebar
keywords: 
summary: 'SnapCenter requires several licenses to enable data protection operations. The type of SnapCenter licenses you install depends on your storage environment and the features that you want to use.'
---
= SnapCenter licenses
:icons: font
:imagesdir: ../media/

[.lead]
SnapCenter requires several licenses to enable data protection operations. The type of SnapCenter licenses you install depends on your storage environment and the features that you want to use.

* SnapCenter Standard controller-based licenses
+
Required if you are using FAS or AFF storage controllers

* SnapCenter Standard capacity-based licenses
+
Required to protect data on ONTAP Select and ONTAP Cloud platforms

* ONTAP licenses, one of the following:
 ** SnapMirror license
 ** SnapVault license
* Additional licenses
+
Some additional licenses might be required, depending on your platform. Examples of additional licenses are SnapRestore, FlexClone, vSphere Standard, and various protocol-based licenses. The _Release Notes_ contain a complete list of required licenses.
+
https://library.netapp.com/ecmdocs/ECMLP2874308/html/frameset.html[SnapCenter Software Release Notes]

*Best Practice:* It is recommended, but not required, that you also add SnapCenter Standard licenses to secondary destinations. If SnapCenter Standard licenses are not enabled on secondary destinations, you cannot use SnapCenter after performing a failover operation. However, a FlexClone license is required on secondary destinations to perform clone and verification operations.
