---
permalink: install/concept_vmware_esxi_server_related_limitations.html
sidebar: sidebar
keywords: 
summary: 'The SnapCenter Plug-in for Microsoft Windows is supported on VMware Windows guest. Before you use the Plug-in for Windows to perform provisioning and Snapshot copy management operations, you should be aware of some limitations.'
---
= VMware ESXi server-related limitations
:icons: font
:imagesdir: ../media/

[.lead]
The SnapCenter Plug-in for Microsoft Windows is supported on VMware Windows guest. Before you use the Plug-in for Windows to perform provisioning and Snapshot copy management operations, you should be aware of some limitations.

* Installing the Plug-in for Windows on a Microsoft cluster on virtual machines using ESXi credentials is not supported.
+
You should use your vCenter credentials when installing the Plug-in for Windows on clustered virtual machines.

* All clustered nodes must use the same target ID (on the virtual SCSI adapter) for the same clustered disk.
* When you create an RDM LUN outside of the Plug-in for Windows, you must restart the plug-in service to enable it to recognize the newly created disk.
* You cannot use iSCSI and FC initiators at the same time on a VMware guest OS.
