---
permalink: install/concept_how_snapcenter_calculates_capacity_usage.html
sidebar: sidebar
keywords: SnapCenter
summary: 'If you have a SnapCenter capacity-based license installed, SnapCenter automatically calculates capacity usage once a day at midnight on the ONTAP Select and Cloud Volumes ONTAP storage it manages. To ensure you have configured SnapCenter correctly, you should be aware of how SnapCenter calculates capacity.'
---
= How SnapCenter calculates capacity usage
:icons: font
:imagesdir: ../media/

[.lead]
If you have a SnapCenter capacity-based license installed, SnapCenter automatically calculates capacity usage once a day at midnight on the ONTAP Select and Cloud Volumes ONTAP storage it manages. To ensure you have configured SnapCenter correctly, you should be aware of how SnapCenter calculates capacity.

If you are using ONTAP Select or Cloud Volumes ONTAP as your storage platform, you must have a SnapCenter Standard capacity-based license installed to enable SnapCenter features such backup and restore. When you are using a Standard Capacity license, SnapCenter calculates the unused capacity by deducting the used capacity on all volumes from the total licensed capacity. If used capacity exceeds the licensed capacity, an overuse warning is displayed on the SnapCenter Dashboard. If you configured capacity thresholds and notifications in SnapCenter, an email is sent when the used capacity reaches the threshold you specify.
