---
permalink: install/concept_requirements_for_using_fc_rdm_luns_in_a_microsoft_cluster.html
sidebar: sidebar
keywords: 
summary: 'The Plug-in for Windows provides support for Microsoft clusters using FC RDM LUNs on two different virtual machines that belong to two different ESX or ESXi servers, also known as cluster across boxes, when you meet specific configuration requirements.'
---
= Requirements for using FC RDM LUNs in a Microsoft cluster
:icons: font
:imagesdir: ../media/

[.lead]
The Plug-in for Windows provides support for Microsoft clusters using FC RDM LUNs on two different virtual machines that belong to two different ESX or ESXi servers, also known as cluster across boxes, when you meet specific configuration requirements.

* The virtual machines (VMs) must be running the same Windows Server version.
* ESX or ESXi server versions must be the same for each VMware parent host.
* Each parent host must have at least two network adapters.
* There must be at least one VMware Virtual Machine File System (VMFS) datastore shared between the two ESX or ESXi servers.
* VMware recommends that the shared datastore be created on an FC SAN.
+
If necessary, the shared datastore can also be created over iSCSI.

* The shared RDM LUN must be in physical compatibility mode.
* The shared RDM LUN must be created manually outside of the Plug-in for Windows.
+
You cannot use virtual disks for shared storage.

* A SCSI controller must be configured on each virtual machine in the cluster in physical compatibility mode:
+
Windows Server 2008 R2 requires you to configure the LSI Logic SAS SCSI controller on each virtual machine. Shared LUNs cannot use the existing LSI Logic SAS controller if only one of its type exists and it is already attached to the C: drive.
+
SCSI controllers of type paravirtual are not supported on VMware Microsoft clusters.
+
NOTE: When you add a SCSI controller to a shared LUN on a virtual machine in physical compatibility mode, you must select the *Raw Device Mappings* (RDM) option and not the *Create a new disk* option in the VMware Infrastructure Client.

* Microsoft virtual machine clusters cannot be part of a VMware cluster.
* You must use vCenter credentials and not ESX or ESXi credentials when you install the Plug-in for Windows on virtual machines that belongs to a Microsoft cluster.
* The Plug-in for Windows cannot create a single igroup with initiators from multiple hosts.
+
The igroup containing the initiators from all ESXi hosts must be created on the storage controller prior to creating the RDM LUNs that will be used as shared cluster disks.

* Ensure that you create an RDM LUN on ESXi 5.0 using an FC initiator.
+
When you create an RDM LUN, an initiator group is created with ALUA.
