---
permalink: install/enable_multifactor_authentication.html
sidebar: sidebar
keywords: mfa, authentication, multifactor authentication
summary: 'SnapCenter employs strict security and authentication features to enable you to keep your data secure.'
---
= Enable Multi-factor authentication (MFA)
:icons: font
:imagesdir: ../media/

[.lead]

To enable MFA functionality, you should perform some steps in the Active Directory Federation Service (ADFS) and SnapCenter Server.

*What you will need*

* Windows Active Directory Federation Service (ADFS) should be up and running in the respective domain.
* You should have any ADFS supported Multi-factor authentication services such as Azure MFA, Cisco Duo, and so on.
* Procure and configure the authorized CA certificate for SnapCenter server.
+
For information on CA certificate, see link:../install/reference_generate_CA_certificate_CSR_file.html[Generate CA Certificate CSR file^].

*About this task*

* The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running Get-Help command_name. Alternatively, you can also refer to the https://library.netapp.com/ecm/ecm_download_file/ECMLP2880726[SnapCenter Software Cmdlet Reference Guide^].

*Steps*

. Connect to the Active Directory Federation Services (AD FS) host.
. Download AD FS federation metadata file from _https://<host FQDN>/FederationMetadata/2007-06/FederationMetadata.xml_
. Copy the downloaded file to SnapCenter Server to enable MFA feature.
. Log in as the SnapCenter Administrator user through PowerShell.
. Generate the SnapCenter MFA metadata file by using the _New-SmMultifactorAuthenticationMetadata -path_ cmdlet.
+
The path parameter specifies the path to save the MFA metadata file in the SnapCenter Server host.
. Copy the generated file to the AD FS host to configure SnapCenter as the client entity.
. Enable MFA for SnapCenter Server using the _Set-SmMultiFactorAuthentication -Enable -Path_ cmdlet.
+
The path parameter specifies the location of the AD FS MFA metadata xml file.
. (Optional) Check the MFA configuration status and settings by using _Get-SmMultiFactorAuthentication_ cmdlet.
. Go to the Microsoft management console (MMC) and perform the following steps:
.. Click *File* > *Add/Remove Snapin*.
.. In the Add or Remove Snap-ins window, select *Certificates* and then click *Add*.
.. In the Certificates snap-in window, select the *Computer account* option, and then click *Finish*.
.. Click *Console Root* > *Certificates – Local Computer* > *Personal* > *Certificates*.
.. Right-click on the CA certificate bound to SnapCenter and then select *All Tasks* > *Manage Private Keys*.
.. On the permissions wizard perform the following steps:
... Click *Add*
... Click *Locations* and select the concerned host (top of hierarchy)
... Click *OK* in the *Locations* pop-up window.
... In the object name field, enter ‘IIS_IUSRS’ and click *Check Names* and click *OK*.
+
If the check is successful, click *OK*.
. In the AD FS host, open AD FS management wizard and perform the following steps:
.. Right click on *Relying Party Trusts* > *Add Relying Party Trust* > *Start*.
.. Select the second option and browse the SnapCenter MFA Metadata file and click *Next*.
.. Specify a display name and click *Next*.
.. Choose and access control policy as required and click *Next*.
.. Set the settings in the next tab to default.
.. Click *Finish*.
+
SnapCenter is now reflected as a relying party with the provided display name.

. Select the name and perform the following steps:
.. Click *Edit Claim Issuance Policy*.
.. Click *Add Rule* and click *Next*.
.. Specify a name for the claim rule
.. Select *Active Directory* as the attribute store.
.. Select the attribute as *User-Principal-Name* and the outgoing claim type as *Name-ID*.
.. Click *Finish*.

SnapCenter MFA functionality can also be enabled using REST APIs.

== Disable Multi-factor authentication (MFA)

Disable MFA and clean up the configuration files that were created when MFA was enabled by using _Set-SmMultiFactorAuthentication -Disable_ cmdlet.

== Update ADFS MFA metadata

You should update the ADFS MFA metadata in SnapCenter whenever there is any modification in ADFS server such as upgrade, CA certificate renewal, DR, and so on.

*Steps*

. Download AD FS federation metadata file from _https://<host FQDN>/FederationMetadata/2007-06/FederationMetadata.xml_
. Copy the downloaded file to SnapCenter Server to update the MFA configuration.
. Update the ADFS metadata in SnapCenter by using the following cmdlet.
+
_Set-SmMultiFactorAuthentication -Path <location of ADFS MFA metadata xml file>_

== Update SnapCenter MFA Metadata

You should update the SnapCenter MFA metadata in ADFS whenever there is any modification in the SnapCenter Server, such as repair, CA certificate renewal, DR, and so on.
