---
permalink: install/install_snapcenter_server_linux.html
sidebar: sidebar
keywords: install, snapcenter software, install, linux host
summary: 'You can install the SnapCenter Server on the Linux host.'
---
= Install the SnapCenter Server on Linux host
:icons: font
:imagesdir: ../media/

[.lead]
You can run the SnapCenter Server installer executable to install the SnapCenter Server.

.Before you begin

* You should install the Microsoft-prod package.
* Check the secure Linux status by running the command `sestatus`. If the _SELinux status_ is "enabled" and the _Current mode_ is "enforcing", perform the following:
** Run the command: `sudo semanage port -a -t http_port_t -p tcp <port_number>`
** If the firewall blocks the port, run `sudo firewall-cmd --add-port 8146/tcp`
** Run the command from the directory where you have read and write permission: `sudo ausearch -c 'nginx' --raw | audit2allow -M my-nginx`
** Run the command to make the policy package active: `sudo semodule -i my-nginx.pp`

.About this task

The SnapCenter Server installed on the Linux host does not support:
* High availability
* Windows plug-ins  
* Active Directory (Supports only the local users, both root and non-root user with creds)
* Key based authentication to log into SnapCenter

*Steps*

. Download the SnapCenter Server installation package *snapcenter_linux_server_(el8/el9/sles15).bin* from https://mysupport.netapp.com/site/products/all/details/snapcenter/downloads-tab[NetApp Support Site^] to _/home directory_.
. For non-root users' installation, add the visudo content specified in _snapcenter_server_checksum_(el8/el9/sles15).txt_ available along with the .bin installer.
. Assign the execute permission for the .bin installer.
`chmod +x snapcenter_linux_server.bin`
. Perform one of the actions to install SnapCenter Server.
+
|===
| If you want to perform... | Do this...

a|
Non interactive installation
a|
`sudo ./snapcenter_linux_server_(el8/el9/sles15).bin -i silent -DWEBAPP_EXTERNAL_PORT=<port> -DWEBAPP_INTERNAL_PORT=<port> -DSMCORE_PORT=<port> -DSCHEDULER_PORT=<port>  -DSNAPCENTER_SERVER_USER=<user> -DUSER_INSTALL_DIR=<dir> -DINSTALL_LOG_NAME=<filename>`

Example: sudo ./snapcenter_linux_server.bin -i silent -DWEBAPP_EXTERNAL_PORT=8146  -DSNAPCENTER_SERVER_USER=root -DUSER_INSTALL_DIR=/opt -DINSTALL_LOG_NAME=InstallerLog.log

Logs will be stored at _/var/opt/snapcenter/logs_.

Parameters to be passed for installing SnapCenter Server:

* DWEBAPP_EXTERNAL_PORT: Webapp external port that is used to access SnapCenter Server outside the Linux host. The default value is 8146.
* DWEBAPP_INTERNAL_PORT: Webapp internal port that is used to access SnapCenter Server within the Linux host. The default value is 8147.
* DSMCORE_PORT: SMCore port on which the smcore services are running. The default value is 8145.
* DSCHEDULER_PORT: Scheduler port on which the scheduler services are running. The default value is 8154.
* DSNAPCENTER_SERVER_USER:  SnapCenter Server user who will install SnapCenter Server.
* DUSER_INSTALL_DIR: Installation directory where packages will be installed.
* DINSTALL_LOG_NAME: Log file name where installation logs will be stored.
* DUPGRADE: The default value is 0. Specify this parameter and it's value as any integer other than 0 to upgrade the SnapCenter Server.

a|
Interactive installation
a|
`./snapcenter_linux_server_(el8/el9/sles15).bin`

You will be prompted to enter the following details:

* The webapp external port that is used to access SnapCenter Server outside the Linux host. The default value is 8146.
* The SnapCenter Server user who will install SnapCenter Server.
* The installation directory where packages will be installed.
|===




