---
permalink: install/reference_ontap_cli_commands_for_creating_svm_roles.html
sidebar: sidebar
keywords: 
summary: 'There are several ONTAP CLI commands you should run to create a role and assign permissions.'
---
= ONTAP CLI commands for creating roles and assigning permissions
:icons: font
:imagesdir: ../media/

[.lead]
There are several ONTAP CLI commands you should run to create a role and assign permissions.

== ONTAP CLI command list

|===
| Command to run
a|
security login role create -role Role_Name -cmddirname "cluster identity modify" -vserver SVM_name or Cluster_name or cluster_name -access all
a|
security login role create -role Role_Name -cmddirname "cluster identity show" -vserver SVM_name or Cluster_name -access all
a|
security login role create -role Role_Name -cmddirname "cluster modify" -vserver SVM_name or Cluster_name -access all
a|
security login role create -role Role_Name -cmddirname "cluster peer show" -vserver SVM_name or Cluster_name -access all
a|
security login role create -role Role_Name -cmddirname "cluster show" -vserver SVM_name or Cluster_name -access all
a|
security login role create -role Role_Name -cmddirname "event generate-autosupport-log" -vserver SVM_name or Cluster_name -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "job history show" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "job stop" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "lun" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "lun create" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "lun delete" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "lun igroup add" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "lun igroup create" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "lun igroup delete" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "lun igroup modify" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "lun igroup rename" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "lun igroup show" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "lun mapping add-reporting-nodes" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "lun mapping create" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "lun mapping delete" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "lun mapping remove-reporting-nodes" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "lun mapping show" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "lun modify" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "lun move-in-volume" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "lun offline" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "lun online" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "lun persistent-reservation clear" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "lun resize" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "lun serial" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "lun show" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "network interface create" -access readonly
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "network interface delete" -access readonly
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "network interface modify" -access readonly
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "network interface show" -access readonly
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "security login" -access readonly
a|
security login role create -role Role_Name -cmddirname "snapmirror create" -vserver SVM_name or Cluster_name -access all
a|
security login role create -role Role_Name -cmddirname "snapmirror list-destinations" -vserver SVM_name or Cluster_name -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "snapmirror policy add-rule" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "snapmirror policy create" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "snapmirror policy delete" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "snapmirror policy modify" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "snapmirror policy modify-rule" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "snapmirror policy remove-rule" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "snapmirror policy show" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "snapmirror restore" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "snapmirror show" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "snapmirror show-history" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "snapmirror update" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "snapmirror update-ls-set" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "version" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume clone create" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume clone show" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume clone split start" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume clone split stop" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume clone split status" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume create" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume destroy" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume file clone create" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume file show-disk-usage" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume modify" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume offline" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume online" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume qtree create" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume qtree delete" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume qtree modify" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume qtree show" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume restrict" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume show" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume snapshot create" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume snapshot delete" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume snapshot modify" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume snapshot promote" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume snapshot rename" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume snapshot restore" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume snapshot restore-file" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume snapshot show" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "volume unmount" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver cifs create" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver cifs delete" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver cifs share modify" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver cifs share create" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver cifs share delete" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver cifs share modify" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver cifs share show" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver cifs show" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver create" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver export-policy create" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver export-policy delete" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver export-policy rule create" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver export-policy rule delete" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver export-policy rule modify" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver export-policy rule show" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver export-policy show" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver iscsi connection show" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver" -access readonly
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver modify" -access readonly
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver show" -access readonly
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver export-policy" -access all
a|
security login role create -vserver SVM_name or Cluster_name -role Role_Name -cmddirname "vserver iscsi" -access all
|===
