---
permalink: install/reference_type_of_licenses_required.html
sidebar: sidebar
keywords:
summary: 'SnapCenter requires several licenses to enable data protection operations.'
---
= Type of licenses required
:icons: font
:imagesdir: ./media/

[.lead]
SnapCenter requires several licenses to enable data protection operations.

|===
| License | Where required

a|
SnapCenter Standard controller-based
a|
Required for FAS or AFF storage controllers SnapCenter Standard license is a controller-based license and is included as part of the premium bundle. If you have the SnapManager Suite license, you also get the SnapCenter Standard license entitlement. If you want to install SnapCenter on a trial basis with FAS or AFF storage, you can obtain a Premium Bundle evaluation license by contacting the sales representative.

a|
SnapCenter Standard capacity-based
a|
Required with ONTAP Select and Cloud Volumes ONTAP If you are a Cloud Volumes ONTAP or ONTAP Select customer, you need to procure a per TB capacity-based license based on the data managed by SnapCenter. By default, SnapCenter ships a built-in 90-day 100 TB SnapCenter Standard capacity-based trial license. For other details, contact the sales representative.

a|
SnapMirror or SnapVault
a|
ONTAPEither SnapMirror or SnapVault license is required if replication is enabled in SnapCenter.

a|
SnapRestore
a|
Required to restore and verify backups.Primary storage systems

* Required on SnapVault destination systems to perform remote verification and to restore from a backup.
* Required on SnapMirror destination systems to perform remote verification.

a|
FlexClone
a|
Required to clone databases and verification operations.Primary and secondary storage systems

* Required on SnapVault destination systems to create clones from secondary vault backup.
* Required on SnapMirror destination systems to create clones from secondary SnapMirror backup.

a|
Protocols
a|

* iSCSI or FC license for LUNs
* CIFS license for SMB shares
* NFS license for NFS type VMDKs
* iSCSI or FC license for VMFS type VMDKs

Required on SnapMirror destination systems to serve data if a source volume is unavailable.

a|
SnapCenter Standard licenses (optional)
a|
Secondary destinations

NOTE: It is recommended, but not required, that you add SnapCenter Standard licenses to secondary destinations. If SnapCenter Standard licenses are not enabled on secondary destinations, you cannot use SnapCenter to backup resources on the secondary destination after performing a failover operation. However, a FlexClone license is required on secondary destinations to perform clone and verification operations

|===

== Single Mailbox Recovery (SMBR) licenses

If you are using SnapCenter Plug-in for Exchange to manage Microsoft Exchange Server databases, you would need the Single Mailbox Recovery (SMBR) licenses. SMBR SKU is available in NetApp quote tool and can be purchased as per your mailbox. After purchasing the SKU, you can obtain the license by following the instructions in https://library.netapp.com/ecm/ecm_download_file/ECMLP2863893[SMBR Release Notes^].

|===
| Product | Part Number

a|
Single Mailbox Recovery Software,1000PK
a|
SW-SMBR-1000PK
a|
Single Mailbox Recovery Software,5000PK
a|
SW-SMBR-5000PK
a|
Single Mailbox Recovery Software,10000PK
a|
SW-SMBR-10000PK
a|
Single Mailbox Recovery Software,25000PK
a|
SW-SMBR-25000PK
|===
|===
| Maintenance and Support | Part Number

a|
Vendor SW Sub SMBR, 1000PK
a|
SW-SSPVN-SMBR-1000PK
a|
Vendor SW Sub SMBR, 5000PK
a|
SW-SSPVN-SMBR-5000PK
a|
Vendor SW Sub SMBR, 10000PK
a|
SW-SSPVN-SMBR-10000PK
a|
Vendor SW Sub SMBR, 25000PK
a|
SW-SSPVN-SMBR-25000PK
|===

When you submit the request for license key, Kroll Ontrack will issue 50 mailbox license keys. Based on your entitlement, the Kroll Ontrack will upgrade the licenses for mailbox after verification.

NOTE: For any SMBR licensing related query you can mail the KO Licensing Team: licensingteam@ontrack.com
