---
permalink: install/reference_space_and_sizing_requirements.html
sidebar: sidebar
keywords: SnapCenter
summary: 'Before you install the SnapCenter Server, you should be familiar with the space and sizing requirements. You should also apply the available system and security updates.'
---

= Space and sizing requirements
:icons: font
:imagesdir: ../media/

[.lead]
Before you install the SnapCenter Server, you should be familiar with the space and sizing requirements. You should also apply the available system and security updates.

|===
| Item | Windows host requirements | Linux host requirements

a|
Operating Systems
a|
Microsoft Windows

Only English, German, Japanese, and simplified Chinese version of the operating systems are supported.

For the latest information about supported versions, see
https://imt.netapp.com/matrix/imt.jsp?components=121033;&solution=1258&isHWU&src=IMT[NetApp Interoperability Matrix Tool^].
a|
* Red Hat Enterprise Linux (RHEL) 8 and 9
* SUSE Linux Enterprise Server (SLES) 15

For the latest information about supported versions, see
https://imt.netapp.com/matrix/imt.jsp?components=121032;&solution=1258&isHWU&src=IMT[NetApp Interoperability Matrix Tool^].

a|
Minimum CPU count
a|
4 cores
a|
4 cores

a|
Minimum RAM
a|
8 GB

NOTE: The MySQL Server buffer pool uses 20 percent of the total RAM.
a|
8 GB

a|
Minimum hard drive space for the SnapCenter Server software and logs
a|
7 GB

NOTE: If you have the SnapCenter repository in the same drive where SnapCenter Server is installed, then it is recommended to have 15 GB.
a|
15 GB

a|
Minimum hard drive space for the SnapCenter repository
a|
8 GB

NOTE: NOTE: If you have the SnapCenter Server in the same drive where SnapCenter repository is installed, then it is recommended to have 15 GB.
a|
Not applicable

a|
Required software packages
a|

* .NET Framework 8.0.12 (and all subsequent 8.0.x patches)
* ASP.NET Core Runtime 8.0.12 (and all subsequent 8.0.x patches) Hosting Bundle
* PowerShell 7.4.2 or later

For .NET specific troubleshooting information, see https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_upgrade_or_install_fails_with_%22This_KB_is_not_related_to_the_OS%22[SnapCenter upgrade or install fails for legacy systems that do not have internet connectivity^].

a|
* ASP.NET Core Runtime 8.0.12 (and all subsequent 8.0.x patches) Hosting Bundle
* PowerShell 7.4.2 or later
* Nginx is a web server that can be used as a reverse proxy
* Pam-devel
+
PAM (Pluggable Authentication Modules) is a system security tool which allows system administrators to set authentication policy without having to recompile programs which do authentication. 
|===
