---
permalink: install/reference_space_and_sizing_requirements.html
sidebar: sidebar
keywords: SnapCenter
summary: 'Before you install the SnapCenter Server, you should be familiar with the space and sizing requirements. You should also apply the available system and security updates.'
---
= Space and sizing requirements
:icons: font
:imagesdir: ../media/

[.lead]
Before you install the SnapCenter Server, you should be familiar with the space and sizing requirements. You should also apply the available system and security updates.

|===
| Item | Requirements

a|
Operating Systems
a|
Microsoft Windows

Only English, German, Japanese, and simplified Chinese version of the operating systems are supported.

For the latest information about supported versions, see https://imt.netapp.com/matrix/imt.jsp?components=103047;&solution=1257&isHWU&src=IMT[NetApp Interoperability Matrix Tool^].

a|
Minimum CPU count
a|
4 cores
a|
Minimum RAM
a|
8 GB

NOTE: The MySQL Server buffer pool uses 20 percent of the total RAM.

a|
Minimum hard drive space for the SnapCenter Server software and logs
a|
4 GB

NOTE: If you have the SnapCenter repository in the same drive where SnapCenter Server is installed, then it is recommended to have 10 GB.

a|
Minimum hard drive space for the SnapCenter repository
a|
6 GB

NOTE: NOTE: If you have the SnapCenter Server in the same drive where SnapCenter repository is installed, then it is recommended to have 10 GB.

a|
Required software packages
a|

* Microsoft .NET Framework 4.7.2 or later
* Windows Management Framework (WMF) 4.0 or later
* PowerShell 4.0 or later

For .NET troubleshooting information see, link:..https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_upgrade_or_install_fails_with_%22This_KB_is_not_related_to_the_OS%22[SnapCenter upgrade or install fails for legacy systems that do not have internet connectivity.]

For the latest information about supported versions, see https://imt.netapp.com/matrix/imt.jsp?components=103047;&solution=1257&isHWU&src=IMT[NetApp Interoperability Matrix Tool^].
|===
