---
permalink: install/reference_issues_while_creating_rdm_lun.html
sidebar: sidebar
keywords: 
summary: 'If you experience errors creating RDM LUNs, you should be aware of some of the common errors and workarounds.'
---
= Issues while creating RDM LUN
:icons: font
:imagesdir: ../media/

[.lead]
If you experience errors creating RDM LUNs, you should be aware of some of the common errors and workarounds.

== Error message

Failed to create disk in virtual machine, Failed to Map virtual disk: File [datastore] path_name was not found.

== Problem

You might encounter this error when you attempt to create an RDM LUN with ESX or ESXi Software Initiator on a VM with a name with more than 33 characters.

You have several options to work around this issue.

== Workaround 1

Manually create the same directory inside the datastore.

== Workaround 2

Rather than selecting your datastore with the Store with Virtual machine option, select the datastore in which you intend to create the RDM LUN. When you create the RDM LUN, use the same datastore you just selected.

== Workaround 3

Configure the Plug-in for Windows VirtualCenter or ESXi Server login settings with the VirtualCenter credentials.
