---
permalink: install/reference_san_host_requirements.html
sidebar: sidebar
keywords: host utilities, Microsoft DSM, Windows MPIO
summary: 'If your SnapCenter host is part of a FC/iSCSI environment, you might need to install additional software on the system to enable access to ONTAP storage.'
---
= SAN host requirements
:icons: font
:imagesdir: ../media/

[.lead]
If your SnapCenter host is part of a FC/iSCSI environment, you might need to install additional software on the system to enable access to ONTAP storage.

SnapCenter does not include Host Utilities or a DSM. If your SnapCenter host is part of a SAN environment, you might need to install and configure the following software:

* Host Utilities
+
The Host Utilities support FC and iSCSI, and it enables you to use MPIO on your Windows Servers.
For information see https://docs.netapp.com/us-en/ontap-sanhost/[Host Utilities documentation^].

* Microsoft DSM for Windows MPIO
+
This software works with Windows MPIO drivers to manage multiple paths between NetApp and Windows host computers.
+
A DSM is required for high availability configurations.
+
NOTE: If you were using ONTAP DSM, you should migrate to Microsoft DSM. For information, see https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/Data_ONTAP_DSM_for_Windows_MPIO/How_to_migrate_from_Data_ONTAP_DSM_4.1p1_to_Microsoft_native_DSM[How to migrate from ONTAP DSM to Microsoft DSM^].
