---
permalink: install/reference_supported_storage_systems_and_applications.html
sidebar: sidebar
keywords: storage system, ONTAP version, ASA r2 systems
summary: 'You should know the supported storage system, applications and databases.'
---
= Supported storage systems and applications
:icons: font
:imagesdir: ../media/

[.lead]
You should know the supported storage system, applications, and databases.

* SnapCenter supports ONTAP 9.12.1 and later to protect your data.

* SnapCenter 6.1 supports NetApp ASA r2 systems (ASA A1K, ASA A70, and ASA A90) that are running ONTAP 9.16.1.
+
ASA r2 systems offer a unified hardware and software solution for SAN-only environments built on all flash platforms. ASA r2 systems vary from other ONTAP systems (ASA, AFF, and FAS) in the implementation of its storage layer, supported protocols, and ONTAP personality.
+
For information on ASA r2 systems, see https://docs.netapp.com/us-en/asa-r2/index.html[ASA r2 documentation^].

* SnapCenter supports Amazon FSx for NetApp ONTAP to protect your data from SnapCenter Software 4.5 P1 patch release.
+
If you are using Amazon FSx for NetApp ONTAP, ensure that the SnapCenter Server host plug-ins are upgraded to 4.5 P1 or later to perform data protection operations. 
+
Supports non-volatile memory express (NVMe) over Transport Control Protocol (TCP).
+
For information about Amazon FSx for NetApp ONTAP, see https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html[Amazon FSx for NetApp ONTAP documentation^].

* SnapCenter supports protection of different applications and databases.
+
For detailed information about the supported applications and databases, see https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1257&isHWU&src=IMT[NetApp Interoperability Matrix Tool^].

* SnapCenter 4.9 P1 and later supports protection of Oracle and Microsoft SQL workloads in VMware Cloud on Amazon Web Services (AWS) Software-Defined Data Center (SDDC) environments.  
+
For more information, see https://community.netapp.com/t5/Tech-ONTAP-Blogs/Protect-Oracle-MS-SQL-workloads-using-NetApp-SnapCenter-in-VMware-Cloud-on-AWS/ba-p/449168[Protect Oracle, MS SQL workloads using NetApp SnapCenter in VMware Cloud on AWS SDDC environments].