---
permalink: install/reference_provision_storage_using_powershell_cmdlets.html
sidebar: sidebar
keywords: Provision storage, snapcenter
summary: 'If you do not want to use the SnapCenter GUI to perform host provisioning and space reclamation jobs, you can use the PowerShell cmdlets that are provided by SnapCenter Plug-in for Microsoft Windows. You can use cmdlets directly or add them to scripts.'
---
= Provision storage using PowerShell cmdlets
:icons: font
:imagesdir: ../media/

[.lead]
If you do not want to use the SnapCenter GUI to perform host provisioning and space reclamation jobs, you can use the PowerShell cmdlets that are provided by SnapCenter Plug-in for Microsoft Windows. You can use cmdlets directly or add them to scripts.

If you are running the cmdlets on a remote plug-in host, you must run the SnapCenter Open-SMConnection cmdlet to open a connection to the SnapCenter Server.

The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running _Get-Help command_name_. Alternatively, you can also refer to the https://library.netapp.com/ecm/ecm_download_file/ECMLP2886205[SnapCenter Software Cmdlet Reference Guide^].

If SnapCenter PowerShell cmdlets are broken due to removal of SnapDrive for Windows from the server, refer to https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapCenter/SnapCenter_cmdlets_broken_when_SnapDrive_for_Windows_is_uninstalled[SnapCenter cmdlets broken when SnapDrive for Windows is uninstalled^].
// Updated for BURT 1424488, Nov 18, 2021
