---
permalink: install/task_view_the_licenses_installed_on_the_controller.html
sidebar: sidebar
keywords: view licenses, controller
summary: 'You can use the ONTAP command line to view all the licenses installed on your controller to determine whether you have the SnapManagerSuite license already installed.'
---
= View the licenses installed on the controller
:icons: font
:imagesdir: ../media/

[.lead]
You can use the ONTAP command line to view all the licenses installed on your controller to determine whether you have the SnapManagerSuite license already installed.

You must be a cluster administrator on the FAS or AFF system.

NOTE: The SnapCenter Standard controller-based license displays as SnapManagerSuite license on the controller.

*Steps*

. Log in to the NetApp controller using the ONTAP command line.
. Enter the license show command, and then view the output to determine whether the SnapManagerSuite license is installed.
+
----
cluster1::> license show
(system license show)

Serial Number: 1-80-0000xx
Owner: cluster1
Package           Type     Description              Expiration
----------------- -------- ---------------------    ---------------
Base              site     Cluster Base License     -

Serial Number: 1-81-000000000000000000000000xx
Owner: cluster1-01
Package           Type     Description              Expiration
----------------- -------- ---------------------    ---------------
NFS               license  NFS License              -
CIFS              license  CIFS License             -
iSCSI             license  iSCSI License            -
FCP               license  FCP License              -
SnapRestore       license  SnapRestore License      -
SnapMirror        license  SnapMirror License       -
FlexClone         license  FlexClone License        -
SnapVault         license  SnapVault License        -
SnapManagerSuite  license  SnapManagerSuite License -
----
+
In the example, the SnapManagerSuite license is installed, therefore, no additional SnapCenter licensing action is required.
+
If no SnapManagerSuite license is displayed, you must obtain your controller serial number, and then retrieve your license from the https://mysupport.netapp.com/site/[NetApp Support Site^].
