---
permalink: install/task_disconnecting_a_disk.html
sidebar: sidebar
keywords: 
summary: 'You can disconnect a LUN from a host without affecting the contents of the LUN, with one exception: If you disconnect a clone before it has been split off, you lose the contents of the clone.'
---
= Disconnecting a disk
:icons: font
:imagesdir: ../media/

[.lead]
You can disconnect a LUN from a host without affecting the contents of the LUN, with one exception: If you disconnect a clone before it has been split off, you lose the contents of the clone.

* Make sure that the LUN is not in use by any application.
* Make sure that the LUN is not being monitored with monitoring software.
* If the LUN is shared, make sure to remove the cluster resource dependencies from the LUN and verify that all nodes in the cluster are powered on, functioning properly, and available to SnapCenter.

If you disconnect a LUN in a FlexClone volume that SnapCenter has created and no other LUNs on the volume are connected, SnapCenter deletes the volume. Before disconnecting the LUN, SnapCenter displays a message warning you that the FlexClone volume might be deleted.

To avoid automatic deletion of the FlexClone volume, you should rename the volume before disconnecting the last LUN. When you rename the volume, make sure that you change multiple characters than just the last character in the name.

. In the left navigation pane, click *Hosts*.
. In the Hosts page, click *Disks*.
. Select the host from the *Host* drop-down list.
+
The disks are listed.

. Select the disk you want to disconnect, and then click *Disconnect*.
. In the Disconnect Disk dialog box, click *OK*.
+
SnapCenter disconnects the disk.
