---
permalink: install/task_resizing_a_disk.html
sidebar: sidebar
keywords: 
summary: 'You can increase or decrease the size of a disk as your storage system needs change.'
---
= Resizing a disk
:icons: font
:imagesdir: ../media/

[.lead]
You can increase or decrease the size of a disk as your storage system needs change.

* For thin provisioned LUN, the ONTAP lun geometry size is shown as the maximum size.
* For thick provisioned LUN, the expandable size (available size in the volume) is shown as the maximum size.
* LUNs with MBR-style partitions have a size limit of 2 TB.
+
LUNs with GPT-style partitions have a storage system size limit of 16 TB.

* It is a good idea to make a Snapshot copy before resizing a LUN.
* If you need to restore a LUN from a Snapshot copy made before the LUN was resized, SnapCenter automatically resizes the LUN to the size of the Snapshot copy.
+
After the restore operation, data added to the LUN after it was resized must be restored from a Snapshot copy made after it was resized.

. In the left navigation pane, click *Hosts*.
. In the Hosts page, click *Disks*.
. Select the host from the *Host* drop-down list.
+
The disks are listed.

. Select the disk you want to resize and then click *Resize*.
. In the Resize Disk dialog box, use the slider tool to specify the new size of the disk, or enter the new size in the *Size* field.
+
NOTE: If you enter the size manually, you need to click outside the *Size* field before the *Shrink* or *Expand* button is enabled appropriately. Also, you must click *MB*, *GB*, or *TB* to specify the unit of measurement.

. When you are satisfied with your entries, click *Shrink* or *Expand*, as appropriate.
+
SnapCenter resizes the disk.
