---
permalink: install/task_configure_CA_certificate_with_SPL_on_Linux_host.html
sidebar: sidebar
keywords: SnapCenter
summary: 'Configure CA certificate with SnapCenter Plug-in Loader service on Linux host'
---
= Configure CA certificate with SnapCenter Plug-in Loader service on Linux host
:icons: font
:imagesdir: ../media/

[.lead]

You should configure the CA certificate with SnapCenter Plug-in Loader service to activate the installed digital certificate.

*Steps*

. List the added certificates in the keystore:
+
`keytool -list -v -keystore keystore.jks`

. Add the CA certificate having both private and public key.
+
`keytool -importkeystore -srckeystore /root/snapcenter.ssl.test.netapp.com.pfx -srcstoretype pkcs12 -destkeystore keystore.jks -deststoretype JKS`

. List the added certificatess in the keystore and confirm that both certificates are added.

. Remove the self-signed certificate with alias from the keystore.
+
`keytool -delete -alias splkeystore -keystore keystore-name -storepass password`

. List added certificates in the keystore and confirm that you are left with only the CA certificate.

. Change the added key password to "snapcenter”, to match the SnapCenter Plug-in Loader service keystore password.
+
`keytool -keypasswd  -alias "alias_name_in_CA_cert" -keystore keystore.jks`
