---
permalink: install/task_enable_ca_certificates_for_snapcenter.html
sidebar: sidebar
keywords: SnapCenter
summary: 'Configure the CA certificate with Windows host plug-in services'
---
= Configure CA certificate with Windows host plug-in services
:icons: font
:imagesdir: ../media/

[.lead]
You should configure the CA certificates and enable the CA certificate validation for the SnapCenter Server.

*Before you begin*

* You can enable or disable the CA certificates using the run Set-SmCertificateSettings cmdlet.

* You can display the certificate status for the SnapCenter Server using the Get-SmCertificateSettings cmdlet.

The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running Get-Help command_name. Alternatively, you can also refer to the Cmdlet Reference Guide.

*Steps*

. In the Settings page, navigate to *Settings* > *Global Settings* > *CA Certificate Settings*.

. Select *Enable Certificate Validation*.

. Click *Apply*.
