---
permalink: install/task_establish_an_iscsi_session.html
sidebar: sidebar
keywords: 
summary: 'If you are using iSCSI to connect to a LUN, you must establish an iSCSI session before you create the LUN to enable communication.'
---
= Establish an iSCSI session
:icons: font
:imagesdir: ../media/

[.lead]
If you are using iSCSI to connect to a LUN, you must establish an iSCSI session before you create the LUN to enable communication.

* You must have defined the storage system node as an iSCSI target.
* You must have started the iSCSI service on the storage system.
+
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/home.html[ONTAP 9 SAN Administration Guide]

You can establish an iSCSI session only between the same IP versions: either from IPv6 to IPv6, or from IPv4 to IPv4.

You can use a link-local IPv6 address for iSCSI session management and for communication between a host and a target only when both are in the same subnet.

If you change the name of an iSCSI initiator, access to iSCSI targets is affected. After changing the name, you might require to reconfigure the targets accessed by the initiator so that they can recognize the new name. You must ensure to restart the host after changing the name of an iSCSI initiator.

If your host has more than one iSCSI interface, once you have established an iSCSI session to SnapCenter using an IP address on the first interface, you cannot establish an iSCSI session from another interface with a different IP address.

. In the left navigation pane, click *Hosts*.
. In the Hosts page, click *iSCSI Session*.
. From the *Storage Virtual Machine* drop-down list, select the storage virtual machine (SVM) for the iSCSI target.
. From the *Host* drop-down list, select the host for the session.
. Click *Establish Session*.
+
The Establish Session wizard is displayed.

. In the Establish Session wizard, identify the target:
+
|===
| In this field...| Enter...
a|
Target node name
a|
The node name of the iSCSI target    If there is an existing target node name, the name is displayed in read-only format.
a|
Target portal address
a|
The IP address of the target network portal
a|
Target portal port
a|
The TCP port of the target network portal
a|
Initiator portal address
a|
The IP address of the initiator network portal
|===

. When you are satisfied with your entries, click *Connect*.
+
SnapCenter establishes the iSCSI session.

. Repeat this procedure to establish a session for each target.
