---
permalink: install/task_configure_audit_log_settings.html
sidebar: sidebar
keywords: audit, log, configure
summary: 'You can configure to log the security events of software platforms and all the software running on those platforms.'
---
= Configure audit log settings
:icons: font
:imagesdir: ../media/

[.lead]
Audit logs are generated for each and every activity of the SnapCenter Server. By default, audit logs are secured in the default installed location _C:\Program Files\NetApp\SnapCenter WebApp\audit\_. 

Audit logs are secured by means of generating digitally signed digest for each and every audit events to protect it from the unauthorized modification. The generated digest's are maintained in the separate audit checksum file and it under goes periodic integrity checks to ensure the integrity of the content.

You should have logged in as the "SnapCenterAdmin" role.

*About this task*

* Alerts are sent when the audit log integrity check schedule is enabled or disabled, when the audit fails, or if the forwarding fails due to network delay.
* Email is sent only when integrity check fails.
* When either the audit log directory or audit checksum log directory paths are modified, audit integrity check job sends an alert.
* When both the audit log directory or audit checksum log directory paths are modified, the job cannot track or perform integrity check on the audit logs present in the earlier location.
* You should modify both audit log directory and audit checksum log directory paths together. You cannot modify only one of them.
* Audit log directory and Audit checksum log directory paths should be on the local drive of SnapCenter Server.  Shared or network mounted drives are not supported.

*Steps*

. In the *Settings* page, navigate to *Settings* > *Global Settings* > *Audit log Settings*.
. In the Audit log section, enter the details.
. Enter the *Audit log directory*
. Enter the *Audit checksum log directory*
.. Enter the Maximum file size
.. Enter the Maximum log files
.. Enter the percentage of disk space usage to send an alert 
. (Optional) Enable *Log UTC time*.  
. (Optional) Enable *Audit Log Integrity Check Schedule*.
+
You can also run *Start-SmAuditIntegrityCheck* command to start integrity check on demand. 
+
The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running Get-Help command_name. Alternatively, you can also refer the https://library.netapp.com/ecm/ecm_download_file/ECMLP2885482[SnapCenter Software Cmdlet Reference Guide^].
. (Optional) Enable Forwarded audit logs to remote syslog server and enter the Syslog Server details.
+
You should import the certificate from the Syslog server into the 'Trusted Root' for TLS 1.2 protocol.
+
.. Enter Syslog Server Host
.. Enter Syslog Server Port
.. Enter Syslog Server Protocol
.. Enter RFC Format
. Click *Save*.
. Verify whether the Audit log is enabled or not by clicking *Monitor* > *Jobs*.

