---
permalink: install/task_create_and_manage_disks.html
sidebar: sidebar
keywords: disks, create, manage, clustered disks, view
summary: 'The Windows host sees LUNs on your storage system as virtual disks. You can use SnapCenter to create and configure an FC-connected or iSCSI-connected LUN.'
---
= Create and manage disks
:icons: font
:imagesdir: ../media/

[.lead]
The Windows host sees LUNs on your storage system as virtual disks. You can use SnapCenter to create and configure an FC-connected or iSCSI-connected LUN.

* SnapCenter supports only basic disks. The dynamic disks are not supported.
* For GPT only one data partition and for MBR one primary partition is allowed that has one volume formatted with NTFS or CSVFS and has one mount path.
* Supported partition styles: GPT, MBR; in a VMware UEFI VM, only iSCSI disks are supported

//included the above 3 bullets in 4.6 for BURT 1366391

NOTE: SnapCenter does not support renaming a disk. If a disk that is managed by SnapCenter is renamed, SnapCenter operations will not succeed.

== View the disks on a host

You can view the disks on each Windows host you manage with SnapCenter.

*Steps*

. In the left navigation pane, click *Hosts*.
. In the Hosts page, click *Disks*.
. Select the host from the *Host* drop-down list.
+
The disks are listed.

== View clustered disks

//Included this section for BURT 1436454

You can view clustered disks on the cluster that you manage with SnapCenter. The clustered disks are displayed only when you select the cluster from the Hosts drop-down.

*Steps*

. In the left navigation pane, click *Hosts*.
. In the Hosts page, click *Disks*.
. Select the cluster from the *Host* drop-down list.
+
The disks are listed.

== Create FC-connected or iSCSI-connected LUNs or disks

The Windows host sees the LUNs on your storage system as virtual disks. You can use SnapCenter to create and configure an FC-connected or iSCSI-connected LUN.

If you want to create and format disks outside of SnapCenter, only NTFS and CSVFS file systems are supported.
//included the above statement in 4.6 for BURT 1366391

*What you will need*

* You must have created a volume for the LUN on your storage system.
+
The volume should hold LUNs only, and only LUNs created with SnapCenter.
+
NOTE: You cannot create a LUN on a SnapCenter-created clone volume unless the clone has already been split.

* You must have started the FC or iSCSI service on the storage system.

* If you are using iSCSI, you must have established an iSCSI session with the storage system.
* The SnapCenter Plug-ins Package for Windows must be installed only on the host on which you are creating the disk.

*About this task*

* You cannot connect a LUN to more than one host unless the LUN is shared by hosts in a Windows Server failover cluster.
* If a LUN is shared by hosts in a Windows Server failover cluster that uses CSV (Cluster Shared Volumes), you must create the disk on the host that owns the cluster group.

*Steps*

. In the left navigation pane, click *Hosts*.
. In the Hosts page, click *Disks*.
. Select the host from the *Host* drop-down list.
. Click *New*.
+
The Create Disk wizard opens.

. On the LUN Name page, identify the LUN:
+
|===
| In this field... | Do this...

a|
Storage System
a|
Select the SVM for the LUN.
a|
LUN path
a|
Click *Browse* to select the full path of the folder containing the LUN.
a|
LUN name
a|
Enter the name of the LUN.
a|
Cluster size
a|
Select the LUN block allocation size for the cluster.

Cluster size depends upon the operating system and applications.
a|
LUN label
a|
Optionally, enter descriptive text for the LUN.
|===

. On the Disk Type page, select the disk type:
+
|===
| Select... | If...

a|
Dedicated disk
a|
The LUN can be accessed by only one host.

Ignore the *Resource Group* field.
a|
Shared disk
a|
The LUN is shared by hosts in a Windows Server failover cluster.

Enter the name of the cluster resource group in the *Resource Group* field. You need to create the disk on only one host in the failover cluster.
a|
Cluster Shared Volume (CSV)
a|
The LUN is shared by hosts in a Windows Server failover cluster that uses CSV.

Enter the name of the cluster resource group in the *Resource Group* field. Make sure that the host on which you are creating the disk is the owner of the cluster group.
|===

. On the Drive Properties page, specify the drive properties:
+
|===
| Property | Description

a|
Auto assign mount point
a|
SnapCenter automatically assigns a volume mount point based on the system drive.

For example, if your system drive is C:, auto assign creates a volume mount point under your C: drive (C:\scmnpt\).     Auto assign is not supported for shared disks.
a|
Assign drive letter
a|
Mount the disk to the drive you select in the adjacent drop-down list.
a|
Use volume mount point
a|
Mount the disk to the drive path you specify in the adjacent field.

The root of the volume mount point must be owned by the host on which you are creating the disk.
a|
Do not assign drive letter or volume mount point
a|
Choose this option if you prefer to mount the disk manually in Windows.
a|
LUN size
a|
Specify the LUN size; 150 MB minimum.

Select MB, GB, or TB in the adjoining drop-down list.
a|
Use thin provisioning for the volume hosting this LUN
a|
Thin provision the LUN.

Thin provisioning allocates only as much storage space as is needed at one time, allowing the LUN to grow efficiently to the maximum available capacity.

Make sure there is enough space available on the volume to accommodate all the LUN storage you think you will need.
a|
Choose partition type
a|
Select GPT partition for a GUID Partition Table, or MBR partition for a Master Boot Record.

MBR partitions might cause misalignment issues in Windows Server failover clusters.

NOTE: Unified extensible firmware interface (UEFI) partition disks are not supported.
|===

. On the Map LUN page, select the iSCSI or FC initiator on the host:
+
|===
| In this field... | Do this...

a|
Host
a|
Double-click the cluster group name to display a drop-down list that shows the hosts that belong to the cluster, and then select the host for the initiator.

This field is displayed only if the LUN is shared by hosts in a Windows Server failover cluster.
a|
Choose host initiator
a|
Select *Fibre Channel* or *iSCSI*, and then select the initiator on the host.

You can select multiple FC initiators if you are using FC with multipath I/O (MPIO).
|===

. On the Group Type page, specify whether you want to map an existing igroup to the LUN, or create a new igroup:
+
|===
| Select... | If...

a|
Create new igroup for selected initiators
a|
You want to create a new igroup for the selected initiators.
a|
Choose an existing igroup or specify a new igroup for selected initiators
a|
You want to specify an existing igroup for the selected initiators, or create a new igroup with the name you specify.

Type the igroup name in the *igroup name* field. Type the first few letters of the existing igroup name to autocomplete the field.
|===

. On the Summary page, review your selections and then click *Finish*.
+
SnapCenter creates the LUN and connects it to the specified drive or drive path on the host.

== Resize a disk

You can increase or decrease the size of a disk as your storage system needs change.

*About this task*

* For thin provisioned LUN, the ONTAP lun geometry size is shown as the maximum size.

* For thick provisioned LUN, the expandable size (available size in the volume) is shown as the maximum size.

* LUNs with MBR-style partitions have a size limit of 2 TB.

* LUNs with GPT-style partitions have a storage system size limit of 16 TB.

* It is a good idea to make a Snapshot copy before resizing a LUN.

* If you need to restore a LUN from a Snapshot copy made before the LUN was resized, SnapCenter automatically resizes the LUN to the size of the Snapshot copy.
+
After the restore operation, data added to the LUN after it was resized must be restored from a Snapshot copy made after it was resized.

*Steps*

. In the left navigation pane, click *Hosts*.
. In the Hosts page, click *Disks*.
. Select the host from the Host drop-down list.
+
The disks are listed.
. Select the disk you want to resize and then click *Resize*.
. In the Resize Disk dialog box, use the slider tool to specify the new size of the disk, or enter the new size in the Size field.
+
NOTE: If you enter the size manually, you need to click outside the Size field before the Shrink or Expand button is enabled appropriately. Also, you must click MB, GB, or TB to specify the unit of measurement.

. When you are satisfied with your entries, click *Shrink* or *Expand*, as appropriate.
+
SnapCenter resizes the disk.

== Connect a disk

You can use the Connect Disk wizard to connect an existing LUN to a host, or to reconnect a LUN that has been disconnected.

*What you will need*

* You must have started the FC or iSCSI service on the storage system.
* If you are using iSCSI, you must have established an iSCSI session with the storage system.
* You cannot connect a LUN to more than one host unless the LUN is shared by hosts in a Windows Server failover cluster.
* If the LUN is shared by hosts in a Windows Server failover cluster that uses CSV (Cluster Shared Volumes), then you must connect the disk on the host that owns the cluster group.
* The Plug-in for Windows needs to be installed only on the host on which you are connecting the disk.

*Steps*

. In the left navigation pane, click *Hosts*.
. In the Hosts page, click *Disks*.
. Select the host from the *Host* drop-down list.
. Click *Connect*.
+
The Connect Disk wizard opens.

. On the LUN Name page, identify the LUN to connect to:
+
|===
| In this field...| Do this...

a|
Storage System
a|
Select the SVM for the LUN.
a|
LUN path
a|
Click *Browse* to select the full path of the volume containing the LUN.
a|
LUN name
a|
Enter the name of the LUN.
a|
Cluster size
a|
Select the LUN block allocation size for the cluster.

Cluster size depends upon the operating system and applications.
a|
LUN label
a|
Optionally, enter descriptive text for the LUN.
|===

. On the Disk Type page, select the disk type:
+
|===
| Select...| If...

a|
Dedicated disk
a|
The LUN can be accessed by only one host.
a|
Shared disk
a|
The LUN is shared by hosts in a Windows Server failover cluster.

You need only connect the disk to one host in the failover cluster.
a|
Cluster Shared Volume (CSV)
a|
The LUN is shared by hosts in a Windows Server failover cluster that uses CSV.

Make sure that the host on which you are connecting to the disk is the owner of the cluster group.
|===

. On the Drive Properties page, specify the drive properties:
+
|===
| Property| Description

a|
Auto assign
a|
Let SnapCenter automatically assign a volume mount point based on the system drive.

For example, if your system drive is C:, the auto assign property creates a volume mount point under your C: drive (C:\scmnpt\).     The auto assign property is not supported for shared disks.
a|
Assign drive letter
a|
Mount the disk to the drive you select in the adjoining drop-down list.
a|
Use volume mount point
a|
Mount the disk to the drive path you specify in the adjoining field.

The root of the volume mount point must be owned by the host on which you are creating the disk.
a|
Do not assign drive letter or volume mount point
a|
Choose this option if you prefer to mount the disk manually in Windows.
|===

. On the Map LUN page, select the iSCSI or FC initiator on the host:
+
|===
| In this field...| Do this...

a|
Host
a|
Double-click the cluster group name to display a drop-down list that shows the hosts that belong to the cluster, then select the host for the initiator.

This field is displayed only if the LUN is shared by hosts in a Windows Server failover cluster.
a|
Choose host initiator
a|
Select *Fibre Channel* or *iSCSI*, and then select the initiator on the host.

You can select multiple FC initiators if you are using FC with MPIO.
|===

. On the Group Type page, specify whether you want to map an existing igroup to the LUN or create a new igroup:
+
|===
| Select...| If...

a|
Create new igroup for selected initiators
a|
You want to create a new igroup for the selected initiators.
a|
Choose an existing igroup or specify a new igroup for selected initiators
a|
You want to specify an existing igroup for the selected initiators, or create a new igroup with the name you specify.

Type the igroup name in the *igroup name* field. Type the first few letters of the existing igroup name to automatically complete the field.
|===

. On the Summary page, review your selections and click *Finish*.
+
SnapCenter connects the LUN to the specified drive or drive path on the host.

== Disconnect a disk

You can disconnect a LUN from a host without affecting the contents of the LUN, with one exception: If you disconnect a clone before it has been split off, you lose the contents of the clone.

*What you will need*

* Make sure that the LUN is not in use by any application.
* Make sure that the LUN is not being monitored with monitoring software.
* If the LUN is shared, make sure to remove the cluster resource dependencies from the LUN and verify that all nodes in the cluster are powered on, functioning properly, and available to SnapCenter.

*About this task*

If you disconnect a LUN in a FlexClone volume that SnapCenter has created and no other LUNs on the volume are connected, SnapCenter deletes the volume. Before disconnecting the LUN, SnapCenter displays a message warning you that the FlexClone volume might be deleted.

To avoid automatic deletion of the FlexClone volume, you should rename the volume before disconnecting the last LUN. When you rename the volume, make sure that you change multiple characters than just the last character in the name.

*Steps*

. In the left navigation pane, click *Hosts*.
. In the Hosts page, click *Disks*.
. Select the host from the *Host* drop-down list.
+
The disks are listed.

. Select the disk you want to disconnect, and then click *Disconnect*.
. In the Disconnect Disk dialog box, click *OK*.
+
SnapCenter disconnects the disk.

== Delete a disk

You can delete a disk when you no longer need it. After you delete a disk, you cannot undelete it.

*Steps*

. In the left navigation pane, click *Hosts*.
. In the Hosts page, click *Disks*.
. Select the host from the *Host* drop-down list.
+
The disks are listed.

. Select the disk you want to delete, and then click *Delete*.
. In the Delete Disk dialog box, click *OK*.
+
SnapCenter deletes the disk.
