---
permalink: install/task_configure_CA_certificate_with_snapcenter_site.html
sidebar: sidebar
keywords: SnapCenter, configure, CA certificate
summary: 'You should configure the CA certificate with SnapCenter site on Windows host.'
---
= Configure CA certificate with SnapCenter site
:icons: font
:imagesdir: ../media/

[.lead]
You should configure the CA certificate with SnapCenter site on Windows host.

*Steps*

. Open IIS Manager on the Windows Server where SnapCenter is installed.
. In the left navigation pane, click *Connections*.
. Expand the name of the server and *Sites*.
. Select the SnapCenter website on which you want to install the SSL Certificate.
. Navigate to  *Actions* > *Edit Site*, click *Bindings*.
. In the Bindings page, select *binding for https*.
. Click *Edit*.
. From the SSL certificate drop-down list, select the recently imported SSL Certificate.
. Click *OK*.
+
NOTE: The SnapCenter Scheduler site (default port: 8154, HTTPS) is configured with self-signed certificate. This port is communicating within the SnapCenter Server host and it is not mandatory to configure with a CA certificate. However, if your environment mandates you to use a CA Certificate, repeat steps 5 to 9 using the SnapCenter Scheduler site.

NOTE: If the recently deployed CA certificate is not listed in the drop-down menu, check if the CA certificate is associated with the private key.

IMPORTANT: Ensure that the certificate is added using the following path: *Console Root > Certificates – Local Computer > Trusted Root Certification Authorities > Certificates*.
