---
permalink: install/task_calculate_capacity_requirements_for_a_snapcenter_capacity_based_license.html
sidebar: sidebar
keywords:
summary: 'Before you obtain a SnapCenter capacity-based license, you should calculate the amount of capacity on a host that is to be managed by SnapCenter.'
---
= Calculate capacity requirements for a SnapCenter capacity-based license
:icons: font
:imagesdir: ../media/

[.lead]
Before you obtain a SnapCenter capacity-based license, you should calculate the amount of capacity on a host that is to be managed by SnapCenter.

*What you will need*

You must be a cluster administrator on the Cloud Volumes ONTAP or ONTAP Select system.

*About this task*

SnapCenter calculates the actual capacity used. If the size of the file system or database is 1 TB, but only 500 GB of space is used, SnapCenter calculates 500 GB of used capacity. The volume capacity is calculated after dedupe and compression, and it is based on the entire volume's used capacity.

*Steps*

. Log in to the NetApp controller using the ONTAP command line.
. To view the volume capacity used, enter the vol show -field used -volume <volume1>,<volume2> command.
+
----
select::> vol show -fields used -volume Engineering,Marketing
vserver volume       used
------- ------       ------
VS1     Engineering  2.13TB
VS1     Marketing    2.62TB

2	entries were displayed.
----
+
The combined used capacity for the two volumes is less than 5 TB; therefore, if you want to protect all 5 TB of data, the minimum SnapCenter capacity-based license requirement is 5 TB.
+
However, if you want to protect only 2 TB of the 5 TB of total used capacity, you can acquire a 2 TB capacity-based license.
