---
permalink: install/task_creating_an_igroup.html
sidebar: sidebar
keywords: 
summary: 'You can use SnapCenter to create an igroup on a Windows host. The igroup will be available in the Create Disk or Connect Disk wizard when you map the igroup to a LUN.'
---
= Creating an igroup
:icons: font
:imagesdir: ../media/

[.lead]
You can use SnapCenter to create an igroup on a Windows host. The igroup will be available in the Create Disk or Connect Disk wizard when you map the igroup to a LUN.

. In the left navigation pane, click *Hosts*.
. In the Hosts page, click *Igroup*.
. In the Initiator Groups page, click *New*.
. In the Create Igroup dialog box, define the igroup:
+
|===
| In this field...| Do this...
a|
Storage System
a|
Select the SVM for the LUN you will map to the igroup.
a|
Host
a|
Select the host on which you want to create the igroup.
a|
Igroup Name
a|
Enter the name of the igroup.
a|
Initiators
a|
Select the initiator.
a|
Type
a|
Select the initiator type, iSCSI, FCP, or mixed (FCP and iSCSI).
|===

. When you are satisfied with your entries, click *OK*.
+
SnapCenter creates the igroup on the storage system.
