---
permalink: install/task_add_a_snapcenter_controller_based_license.html
sidebar: sidebar
keywords: add, controller-based license
summary: 'You can use the ONTAP command line to add a SnapCenter controller-based license when you are using FAS or AFF systems, and you have a SnapCenter Standard or SnapManagerSuite license.'
---
= Add a SnapCenter Standard controller-based license
:icons: font
:imagesdir: ../media/

[.lead]
You can use the ONTAP command line to add a SnapCenter controller-based license when you are using FAS or AFF systems, and you have a SnapCenter Standard or SnapManagerSuite license.

*What you will need*

* You must be a cluster administrator on the FAS or AFF system.
* You must have the SnapCenter Standard or SnapManagerSuite license.

*About this task*

If you want to install SnapCenter on a trial basis with FAS or AFF storage, you can obtain a Premium Bundle evaluation license to install on your controller.

If you want to install SnapCenter on a trial basis, you should contact your sales representative to obtain a Premium Bundle evaluation license to install on your controller.

*Steps*

. Log in to the NetApp cluster using the ONTAP command line.
. Add the SnapManagerSuite license key:
+
`system license add -license-code license_key`
+
This command is available at the admin privilege level.
. Verify that the SnapManagerSuite license is installed:
+
`license show`
