---
permalink: install/task_add_a_snapcenter_controller_based_license.html
sidebar: sidebar
keywords: 
summary: 'You can use the ONTAP command line to add a SnapCenter controller-based license when you are using FAS or AFF systems, and you have a SnapCenter Standard or SnapManagerSuite license.'
---
= Add a SnapCenter Standard controller-based license
:icons: font
:imagesdir: ../media/

[.lead]
You can use the ONTAP command line to add a SnapCenter controller-based license when you are using FAS or AFF systems, and you have a SnapCenter Standard or SnapManagerSuite license.

* You must be a cluster administrator on the FAS or AFF system.
* You must have the SnapCenter Standard or SnapManagerSuite license.
* If you want to install SnapCenter on a trial basis with FAS or AFF storage, you can obtain a Premium Bundle evaluation license to install on your controller.
* If you want to install SnapCenter on a trial basis, you should contact your sales representative to obtain a Premium Bundle evaluation license to install on your controller.

This command is available at the admin privilege level.

. Log in to the NetApp cluster using the ONTAP command line.
. Add the SnapManagerSuite license key: `system license add -license-code license_key`
. Verify that the SnapManagerSuite license is installed: `license show`
