---
permalink: protect-scu/reference_prerequisites_for_adding_hosts_and_installing_snapcenter_plug_ins_package_for_linux.html
sidebar: sidebar
keywords: prerequisites, iSCSI, host requirement for Linux, sudo privileges, non-root user, credentials, authenticate, domain administrator, local administrator, workgroup, sudo, root user
summary: 'Before you add a host and install the plug-ins packages, you must complete all the requirements.'
---
= Prerequisites for adding hosts and installing Plug-ins Package for Linux
:icons: font
:imagesdir: ../media/

[.lead]
Before you add a host and install the plug-ins package for Linux, you must complete all the requirements.

* If you are using iSCSI, the iSCSI service must be running.
* You can either use the password-based authentication for the root or non-root user or SSH key based authentication.
+

NOTE: The RSA key is the only SSH supported key format for SnapCenter. Refer to the Knowledge Base article link:https://kb.netapp.com/data-mgmt/SnapCenter/SC_KBs/How_to_create_an_RSA_key_for_SnapCenter_SSH_Key_Based_credential[How to create an RSA key for SnapCenter SSH Key Based credential^] for details on how to create the SSH key.

+
SnapCenter Plug-in for Unix File Systems can be installed by a non-root user. However, you should configure the sudo privileges for the non-root user to install and start the plug-in process. After installing the plug-in, the processes will be running as an effective non-root user.

* Create credentials with authentication mode as Linux for the install user.
* You must have installed Java 17 for SnapCenter 6.2.1 and later or 
* Java 11 for SnapCenter 6.2 and earlier on your Linux host.
+
NOTE: Ensure that you have installed only the certified edition of Java 17 for SnapCenter 6.2.1 and later or Java 11 for SnapCenter 6.2 and earlier on the Linux host.
+
For information on Java downloads, refer to link:https://www.oracle.com/java/technologies/downloads/#java17[Download Java for all operating systems^].

* You should have *bash* as the default shell for plug-in installation.

== Linux Host requirements

You should ensure that the host meets the requirements before installing the SnapCenter Plug-ins Package for Linux.

|===
| Item| Requirements

a|
Operating systems
a|

* Red Hat Enterprise Linux
* Oracle Linux
* SUSE Linux Enterprise Server (SLES)

a|
Minimum RAM for the SnapCenter plug-in on host
a|
2 GB
a|
Minimum install and log space for the SnapCenter plug-in on host
a|
2 GB

NOTE: You should allocate sufficient disk space and monitor the storage consumption by the logs folder. The log space required varies depending on the number of the entities to be protected and the frequency of data protection operations. If there is no sufficient disk space, the logs will not be created for the recently run operations.

a|
Required software packages
a|
* Java 17 (Oracle Java, OpenJDK, or SAP JDK) for SnapCenter 6.2.1 and later or
* Java 11 for SnapCenter 6.2 and earlier

NOTE: Ensure that you have installed only the certified edition of Java 17 for SnapCenter 6.2.1 and later or Java 11 for SnapCenter 6.2 and earlier on the Linux host.

If you have upgraded Java to the latest version, you must ensure that the JAVA_HOME option located at /var/opt/snapcenter/spl/etc/spl.properties is set to the correct Java version and the correct path.

|===

For the latest information about supported versions, see the https://imt.netapp.com/imt/imt.jsp?components=180320;180338;&solution=1257&isHWU&src=IMT[NetApp Interoperability Matrix Tool^].

// GH ISSUE #239, 2026-JUN-02
// SNAPCDOC-402, 2026-JUN-02