---
permalink: protect-scu/task_create_backup_policies_for_unix_file_systems.html
sidebar: sidebar
keywords: backup policies, policies, unix file systems, file systems
summary: 'Create a backup policy for the Unix file systems that you want to back up.'
---
= Create backup policies for Unix file systems
:icons: font
:imagesdir: ../media/

[.lead]
Before you use SnapCenter to back up Unix file systems, you must create a backup policy for the resource or the resource group that you want to back up. A backup policy is a set of rules that governs how you manage, schedule, and retain backups. You can also specify the replication, script, and backup type settings. Creating a policy saves time when you want to reuse the policy on another resource or resource group.

.Before you begin

* You must have prepared for data protection by completing tasks such as installing SnapCenter, adding hosts, discovering the file systems, and creating storage system connections.
* If you are replicating Snapshot copies to a mirror or vault secondary storage, the SnapCenter administrator must have assigned the SVMs to you for both the source and destination volumes.

.Steps

. In the left navigation pane, click *Settings*.
. In the Settings page, click *Policies*.
. Select *Unix File Systems* from the drop-down list.
. Click *New*.
. In the Name page, enter the policy name and description.
. Specify the schedule frequency by selecting *On demand*, *Hourly*, *Daily*, *Weekly*, or *Monthly*.
. In the Retention page, specify the retention settings for the backup type and the schedule type selected in the Backup Type page:
+
|===
| If you want to...| Then...
a|
Keep a certain number of Snapshot copies
a|
Select *Total Snapshot copies to keep*, and then specify the number of Snapshot copies that you want to keep.

If the number of Snapshot copies exceeds the specified number, the Snapshot copies are deleted with the oldest copies deleted first.

NOTE: The maximum retention value is 1018 for resources on ONTAP 9.4 or later, and 254 for resources on ONTAP 9.3 or earlier. Backups will fail if retention is set to a value higher than what the underlying ONTAP version supports.

IMPORTANT: You must set the retention count to 2 or higher if you plan to enable SnapVault replication. If you set the retention count to 1, the retention operation might fail because the first Snapshot copy is the reference Snapshot copy for the SnapVault relationship until a newer Snapshot copy is replicated to the target.

a|
Keep the Snapshot copies for a certain number of days
a|
Select *Keep Snapshot copies for*, and then specify the number of days for which you want to keep the Snapshot copies before deleting them.
|===
+
NOTE:  You can retain archive log backups only if you have selected the archive log files as part of your backup.

. In the Replication page, specify the replication settings:
+
|===
| For this field... | Do this...

a|
Update SnapMirror after creating a local Snapshot copy
a|
Select this field to create mirror copies of the backup sets on another volume (SnapMirror replication).
a|
Update SnapVault after creating a local Snapshot copy
a|
Select this option to perform disk-to-disk backup replication (SnapVault backups).
a|
Secondary policy label
a|
Select a Snapshot label.

Depending on the Snapshot copy label that you select, ONTAP applies the secondary Snapshot copy retention policy that matches the label.

NOTE: If you have selected *Update SnapMirror after creating a local Snapshot copy*, you can optionally specify the secondary policy label. However, if you have selected *Update SnapVault after creating a local Snapshot copy*, you should specify the secondary policy label.

a|
Error retry count
a|
Enter the maximum number of replication attempts that can be allowed before the operation stops.
|===
+
NOTE: You should configure SnapMirror retention policy in ONTAP for the secondary storage to avoid reaching the maximum limit of Snapshot copies on the secondary storage.

. In the Script page, enter the path and the arguments of the prescript or postscript that you want to run before or after the backup operation, respectively.
+
NOTE: For pre and post commands for quiesce, Snapshot copy, and unquiesce operations, you should check if the commands exist in the command list available on the plug-in host from the _/opt/snapcenter/snapenter/scc/allowed_commands.config_ path.
+
You can also specify the script timeout value. The default value is 60 seconds.
. Review the summary, and then click *Finish*.
