---
permalink: protect-scu/task_create_backup_policies_for_unix_file_systems.html
sidebar: sidebar
keywords: backup policies, policies, unix file systems, file systems
summary: 'Create a backup policy for the Unix file systems that you want to back up.'
---
= Create backup policies for Unix file systems
:icons: font
:imagesdir: ../media/

[.lead]
Before you use SnapCenter to back up Unix file systems, you must create a backup policy for the resource or the resource group that you want to back up. A backup policy is a set of rules that governs how you manage, schedule, and retain backups. You can also specify the replication, script, and backup type settings. Creating a policy saves time when you want to reuse the policy on another resource or resource group.

.Before you begin

* You must have prepared for data protection by completing tasks such as installing SnapCenter, adding hosts, discovering the file systems, and creating storage system connections.
* If you are replicating Snapshots to a mirror or vault secondary storage, the SnapCenter administrator must have assigned the SVMs to you for both the source and destination volumes.
* Review the SnapMirror active sync specific prerequisites and limitations. For information, refer https://docs.netapp.com/us-en/ontap/smbc/considerations-limits.html#volumes[Object limits for SnapMirror active sync].

.About this task

* SnapLock

** If 'Retain the backup copies for a specific number of days' option is selected, then the SnapLock retention period must be lesser than or equal to the mentioned retention days.
+
Specifying a Snapshot locking period prevents deletion of the Snapshots until the retention period expires.  This could lead to retaining a larger number of Snapshots than the count specified in the policy.
+
For ONTAP 9.12.1 and below version, the clones created from the SnapLock Vault Snapshots as part of restore will inherit the SnapLock Vault expiry time. Storage admin should manually cleanup the clones post the SnapLock expiry time.

.Steps

. In the left navigation pane, click *Settings*.
. In the Settings page, click *Policies*.
. Select *Unix File Systems* from the drop-down list.
. Click *New*.
. In the Name page, enter the policy name and details.

. In the Backup and Replication page, perform the following actions:

.. Specify the backup settings. 

.. Specify the schedule frequency by selecting *On demand*, *Hourly*, *Daily*, *Weekly*, or *Monthly*.

.. Select a Snapshot label.
+
Depending on the Snapshot label that you select, ONTAP applies the secondary Snapshot retention policy that matches the label.
+
NOTE: If you have selected *Update SnapMirror after creating a local Snapshot copy*, you can optionally specify the secondary policy label. However, if you have selected *Update SnapVault after creating a local Snapshot copy*, you should specify the secondary policy label.

.. In the Select secondary replication options section, select one or both of the following secondary replication options:
+
NOTE: You must select the secondary replication options for *Secondary snapshot copy locking period* to be effective. The *Secondary snapshot copy locking period* option is available in the Retention page.
+
|===
| For this field... | Do this...

a|
Update SnapMirror after creating a local Snapshot copy
a|
Select this field to create mirror copies of the backup sets on another volume (SnapMirror replication).

This option should be enabled for SnapMirror active sync.
a|
Update SnapVault after creating a local Snapshot copy
a|
Select this option to perform disk-to-disk backup replication (SnapVault backups).
a|
Error retry count
a|
Enter the maximum number of replication attempts that can be allowed before the operation stops.
|===
+
NOTE: You should configure SnapMirror retention policy in ONTAP for the secondary storage to avoid reaching the maximum limit of Snapshots on the secondary storage.

. In the Retention page, specify the retention settings for the backup type and the schedule type selected in the Backup and Replication page:
+
|===
| If you want to...| Then...
a|
Keep a certain number of Snapshots 
a|
Select *Total Snapshot copies to keep*, and then specify the number of Snapshots that you want to keep.

If the number of Snapshots exceeds the specified number, the Snapshots are deleted with the oldest copies deleted first.

NOTE: The maximum retention value is 1018. Backups will fail if retention is set to a value higher than what the underlying ONTAP version supports.

IMPORTANT: You must set the retention count to 2 or higher if you plan to enable SnapVault replication. If you set the retention count to 1, the retention operation might fail because the first Snapshot is the reference Snapshot for the SnapVault relationship until a newer Snapshot is replicated to the target.
a|
Keep the Snapshots for a certain number of days
a|
Select *Keep Snapshot copies for*, and then specify the number of days for which you want to keep the Snapshots before deleting them.
a|
Primary snapshot copy locking period
a|
If you want to specify the snapshot locking period for the primary, select *Primary snapshot copy locking period*, and select days, months, or years.

Snaplock retention period should be less than 100 years.
a|
Secondary snapshot locking period
a|
Select *Secondary snapshot copy locking period*, and select days, months, or years.

For this option to be effective you must do the following tasks:

* Select the *Primary snapshot copy locking period*.
* Select one or both of the secondary replication options.
|===
+
NOTE:  You can retain archive log backups only if you have selected the archive log files as part of your backup.

. In the Script page, enter the path and the arguments of the prescript or postscript that you want to run before or after the backup operation, respectively.
+
NOTE: You should check if the commands exist in the command list available on the plug-in host from the _ /opt/NetApp/snapcenter/scc/etc/allowed_commands.config_ path.
+
You can also specify the script timeout value. The default value is 60 seconds.
. Review the summary, and then click *Finish*.
