---
permalink: protect-scu/task_determine_whether_unix_file_systems_are_available_for_backup.html
sidebar: sidebar
keywords: SnapCenter Plug-in for UNIX file systems, discovery,file systems, UNIX, Unix file systems
summary: 'After installing the plug-in for Unix file systems, the file systems on the host are automatically discovered and displayed in the Resources page.'
---

= Discover the UNIX file systems available for backup
:icons: font
:imagesdir: ../media/

[.lead]
After installing the plug-in, all the file systems on that host are automatically discovered and displayed in the Resources page. You can add these file systems to resource groups to perform data protection operations.

.Before you begin

* You must have completed tasks such as installing the SnapCenter Server, adding hosts, and creating storage system connections.
* If the file systems reside on a Virtual Machine Disk (VMDK) or raw device mapping (RDM), you must deploy the SnapCenter Plug-in for VMware vSphere and register the plug-in with SnapCenter.
+
For more information, see https://docs.netapp.com/us-en/sc-plugin-vmware-vsphere/scpivs44_deploy_snapcenter_plug-in_for_vmware_vsphere.html[Deploy SnapCenter Plug-in for VMware vSphere^].

.Steps

. In the left navigation pane, click *Resources*, and then select the appropriate plug-in from the list.
. In the Resources page, select *Path* from the View list.
. Click *Refresh Resources*.
+
The file systems are displayed along with information such as type, host name, associated resource groups and policies, and status.



