---
permalink: protect-db2/create-backup-policies-for-ibm-db2.html
sidebar: sidebar
keywords: SnapCenter Plug-in for IBM Db2
summary: 'Before you use SnapCenter to back up IBM Db2 database resources, you must create a backup policy for the resource or resource group that you want to back up. A backup policy is a set of rules that governs how you manage, schedule, and retain backups.'
---
= Create backup policies for IBM Db2
:icons: font
:imagesdir: ../media/

[.lead]
Before you use SnapCenter to back up IBM Db2 resources, you must create a backup policy for the resource or resource group that you want to back up. A backup policy is a set of rules that governs how you manage, schedule, and retain backups.

.Before you begin

* You must have defined your backup strategy.
+
For details, see the information about defining a data protection strategy for IBM Db2 databases.
* You must have prepared for data protection by completing tasks such as installing SnapCenter, adding hosts, setting up storage system connections, and adding resources.
* The SnapCenter administrator must have assigned the SVMs for both the source and destination volumes to you if you are replicating snapshots to a mirror or vault.
+
Additionally, you can specify replication, script, and application settings in the policy. These options saves time when you want to reuse the policy for another resource group.

.About this task

* SnapLock 

** If 'Retain the backup copies for a specific number of days' option is selected, then the SnapLock retention period must be lesser than or equal to the mentioned retention days.

** Specifying a snapshot locking period prevents deletion of the snapshots until the retention period expires. This could lead to retaining a larger number of snapshots than the count specified in the policy.

** For ONTAP 9.12.1 and below version, the clones created from the SnapLock Vault snapshots as part of restore will inherit the SnapLock Vault expiry time. Storage admin should manually cleanup the clones post the SnapLock expiry time.

.Steps

. In the left navigation pane, click *Settings*.
. In the Settings page, click *Policies*.
. Click *New*.
. In the Name page, enter the policy name and description.
. In the Policy type page, perform the following:
.. Select storage type.
.. In the *Custom backup settings* section, provide any specific backup settings that have to be passed to the plug-in in key-value format.
+
You can provide multiple key-values to be passed to the plug-in.
. In the Snapshot and Replication page, perform the following actions.
.. Specify the schedule frequency by selecting *On demand*, *Hourly*, *Daily*, *Weekly*, or *Monthly*.
+
NOTE: You can specify the schedule (start date, end date, and frequency) for the backup operation while creating a resource group. This enables you to create resource groups that share the same policy and backup frequency, but also enables you to assign different backup schedules to each policy.
+
NOTE: If you have scheduled for 2:00 a.m., the schedule will not be triggered during daylight saving time (DST).
.. In the Snapshot settings section, perform the following actions:
+
|===
| If you want to...| Then...

a|
Keep a certain number of snapshots
a|
Select *Copies to keep*, and then specify the number of snapshots that you want to keep.

If the number of snapshots exceeds the specified number, the snapshots are deleted with the oldest copies deleted first.
a|
Keep the Snapshots for a certain number of days
a|
Select *Retain copies for*, and then specify the number of days for which you want to keep the Snapshots before deleting them.
a|
Primary snapshot copy locking period
a|
If you want to specify the snapshot locking period for the primary, select Snapshot copy locking period and select days, months, or years.

Snaplock retention period should be less than 100 years.
a|
Secondary snapshot locking period
a|
Select *Secondary snapshot copy locking period*, and select days, months, or years.

For this option to be effective you must do the following tasks:

* Select the *Primary snapshot copy locking period*.
* Select one or both of the secondary replication options.
|===
+
IMPORTANT: For Snapshot copy-based backups, you must set the retention count to 2 or higher if you plan to enable SnapVault replication. If you set the retention count to 1, the retention operation might fail because the first snapshot is the reference snapshot for the SnapVault relationship until a newer snapshot is replicated to the target.
.. Select a Snapshot label.
+
Depending on the Snapshot label that you select, ONTAP applies the secondary Snapshot retention policy that matches the label.
+
NOTE: If you have selected *Update SnapMirror after creating a local Snapshot copy*, you can optionally specify the secondary policy label. However, if you have selected *Update SnapVault after creating a local Snapshot copy*, you should specify the secondary policy label.
. In the Select secondary replication options section, select one or both of the following secondary replication options:
+
NOTE: You must select the secondary replication options for *Secondary snapshot copy locking period* to be effective. 
+
|===
| For this field... | Do this...

a|
Update SnapMirror after creating a local Snapshot copy
a|
Select this field to create mirror copies of the backup sets on another volume (SnapMirror replication).

This option should be enabled for SnapMirror active sync.
a|
Update SnapVault after creating a local Snapshot copy
a|
Select this option to perform disk-to-disk backup replication (SnapVault backups).
a|
Secondary policy label
a|
Select a Snapshot label.
+
Depending on the Snapshot label that you select, ONTAP applies the secondary Snapshot retention policy that matches the label.
+
NOTE: If you have selected *Update SnapMirror after creating a local Snapshot copy*, you can optionally specify the secondary policy label. However, if you have selected *Update SnapVault after creating a local Snapshot copy*, you should specify the secondary policy label.
a|
Error retry count
a|
Enter the maximum number of replication attempts that can be allowed before the operation stops.
|===
+
NOTE: You should configure SnapMirror retention policy in ONTAP for the secondary storage to avoid reaching the maximum limit of Snapshots on the secondary storage.

. Review the summary, and then click *Finish*.
