---
permalink: protect-db2/host-requirements-to-install-snapcenter-plug-in-package-for-windows-db2.html
sidebar: sidebar
keywords: IBM Db2
summary: 'Before you install the SnapCenter Plug-ins Package for Windows, you should be familiar with some basic host system space requirements and sizing requirements.'
---

= Host requirements to install SnapCenter Plug-ins Package for Windows
:icons: font
:imagesdir: ../media/

[.lead]
Before you install the SnapCenter Plug-ins Package for Windows, you should be familiar with some basic host system space requirements and sizing requirements.

|===
| Item| Requirements

a|
Operating Systems
a|
Microsoft Windows

For the latest information about supported versions, see the https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1258&isHWU&src=IMT[NetApp Interoperability Matrix Tool^].

a|
Minimum RAM for the SnapCenter plug-in on host
a|
1 GB
a|
Minimum install and log space for the SnapCenter plug-in on host
a|
5 GB

NOTE: You should allocate sufficient disk space and monitor the storage consumption by the logs folder. The log space required varies depending on the number of the entities to be protected and the frequency of data protection operations. If there is no sufficient disk space, the logs will not be created for the recently run operations.

a|
Required software packages
a|

* .NET Core beginning with version 8.0.5 and including all subsequent .NET 8 patches
* PowerShell Core 7.4.2 
* Java 11 Oracle Java and OpenJDK

For the latest information about supported versions, see the https://imt.netapp.com/matrix/imt.jsp?components=121074;&solution=1258&isHWU&src=IMT[NetApp Interoperability Matrix Tool^].

For .NET specific troubleshooting information, see https://kb.netapp.com/mgmt/SnapCenter/SnapCenter_upgrade_or_install_fails_with_This_KB_is_not_related_to_the_OS[SnapCenter upgrade or install fails for legacy systems that do not have internet connectivity.]
|===
