---
permalink: protect-db2/how-resources-resource-groups-and-policies-are-used-for-protecting-ibm-db2.html
sidebar: sidebar
keywords: IBM DB2
summary: 'Before you use SnapCenter, it is helpful to understand basic concepts related to the backup, clone, and restore operations you want to perform. You interact with resources, resource groups, and policies for different operations.'
---
= How resources, resource groups, and policies are used for protecting IBM Db2
:icons: font
:imagesdir: ../media/

[.lead]
Before you use SnapCenter, it is helpful to understand basic concepts related to the backup, clone, and restore operations you want to perform. You interact with resources, resource groups, and policies for different operations.

* Resources are typically IBM Db2 databases that you back up or clone with SnapCenter.
* A SnapCenter resource group, is a collection of resources on a host.
+
When you perform an operation on a resource group, you perform that operation on the resources defined in the resource group according to the schedule you specify for the resource group.
+
You can back up on demand a single resource or a resource group. You also can perform scheduled backups for single resources and resource groups.

* The policies specify the backup frequency, replication, scripts, and other characteristics of data protection operations.
+
When you create a resource group, you select one or more policies for that group. You can also select a policy when you perform a backup on demand for a single resource.

Think of a resource group as defining what you want to protect and when you want to protect it in terms of day and time. Think of a policy as defining how you want to protect it. If you are backing up all databases, for example, you might create a resource group that includes all of the databases in the host. You could then attach two policies to the resource group: a daily policy and an hourly policy. When you create the resource group and attach the policies, you might configure the resource group to perform a full backup daily.
