---
permalink: protect-db2/reference_types_of_restore_performed_for_auto_discovered_ibm_db2.html
sidebar: sidebar
keywords: SnapCenter Plug-in for IBM Db2
summary: 'SnapCenter supports volume-based SnapRestore \(VBSR\), Single File SnapRestore, and connect-and-copy restore types for automatically discovered IBM Db2 databases.'
---
= Types of restore operations for auto discovered IBM Db2
:icons: font
:imagesdir: ../media/

[.lead]
SnapCenter Plug-in for IBM Db2 supports Single File SnapRestore, and connect-and-copy restore types for automatically discovered IBM Db2 databases.

== Single File SnapRestore is performed in NFS environments for the following scenarios:

* If only the *Complete Resource* option is selected
* When the backup selected is from a SnapMirror or SnapVault secondary location, and the *Complete Resource* option is selected

== Single File SnapRestore is performed in SAN environments for the following scenarios:

* If only the *Complete Resource* option is selected
* When the backup is selected from a SnapMirror or SnapVault secondary location, and the *Complete Resource* option is selected


