---
permalink: protect-db2/reference_considerations_for_determining_backup_schedules_for_sap_hana_database.html
sidebar: sidebar
keywords: SnapCenter Plug-in for IBM Db2
summary: 'The most critical factor in determining a backup schedule is the rate of change for the resource. You might back up a heavily used resource every hour, while you might back up a rarely used resource once a day. Other factors include the importance of the resource to your organization, your service-level agreement \(SLA\) and your recovery point objective \(RPO\).'
---
= Considerations for determining backup schedules for IBM Db2
:icons: font
:imagesdir: ../media/

[.lead]
The most critical factor in determining a backup schedule is the rate of change for the resource. You might back up a heavily used resource every hour, while you might back up a rarely used resource once a day. Other factors include the importance of the resource to your organization, your service-level agreement (SLA) and your recovery point objective (RPO).

Backup schedules have two parts, as follows:

* Backup frequency (how often backups are to be performed)
+
Backup frequency, also called schedule type for some plug-ins, is part of a policy configuration. For example, you might configure the backup frequency as hourly, daily, weekly, or monthly.

* Backup schedules (exactly when backups are to be performed
+
Backup schedules are part of a resource or resource group configuration. For example, if you have a resource group that has a policy configured for weekly backups, you might configure the schedule to back up every Thursday at 10:00 p.m.
