---
permalink: protect-db2/reference_types_of_restore_strategies_supported_for_auto_discovered_ibm_db2.html
sidebar: sidebar
keywords: SnapCenter Plug-in for IBM Db2
summary: 'You must define a strategy before you can successfully perform restore operations using SnapCenter. There are two types of restore strategies for automatically discovered IBM Db2 databases.'
---
= Types of restore strategies supported for automatically discovered IBM Db2
:icons: font
:imagesdir: ../media/

[.lead]
You must define a strategy before you can successfully perform restore operations using SnapCenter. There are two types of restore strategies for automatically discovered IBM Db2 databases.

== Complete resource restore

* Restores all volumes, qtrees, and LUNs of a resource
 ** The *Volume Revert* option should be selected to restore the entire volume.
+
NOTE: If the resource contains volumes or qtrees, the snapshots taken after the snapshot selected for restore on such volumes or qtrees are deleted and cannot be recovered. Also, if any other resource is hosted on the same volumes or qtrees, then that resource is also deleted.

== Tenant Database

* Restores the tenant database

If *Tenant Database* option is selected, then HANA studio or HANA recovery scripts external to SnapCenter must be used to perform the recovery operation.
