---
permalink: protect-db2/snapcenter-plug-in-for-ibm-db2-overview.html
sidebar: sidebar
keywords: SnapCenter Plug-in for IBM Db2
summary: 'The SnapCenter Plug-in for IBM Db2 is a host-side component of the NetApp SnapCenter software that enables application-aware data protection management of IBM Db2 databases. The Plug-in for IBM Db2 Database automates the backup, restore, and cloning of IBM Db2 databases in your SnapCenter environment.'
---

= SnapCenter Plug-in for IBM Db2 overview
:icons: font
:imagesdir: ../media/

[.lead]
The SnapCenter Plug-in for IBM Db2 Database is a host-side component of the NetApp SnapCenter software that enables application-aware data protection management of IBM Db2 databases. The Plug-in for IBM Db2 Database automates the backup, restore, and cloning of IBM Db2 databases in your SnapCenter environment.

* SnapCenter 6.0 supports IBM Db2 10.5 and later. 
* SnapCenter 6.0.1 supports IBM Db2 9.7.x and later. Also, beginning with SnapCenter 6.0.1, IBM Db2 on AIX is supported.

SnapCenter supports single instance and multi instance Db2 setups. You can use the Plug-in for IBM Db2 Database in both Linux and Windows environments. In Windows environments, Db2 will be supported as manual resource.

When the Plug-in for IBM Db2 Database is installed, you can use SnapCenter with NetApp SnapMirror technology to create mirror copies of backup sets on another volume. You can also use the plug-in with NetApp SnapVault technology to perform disk-to-disk backup replication for standards compliance.

SnapCenter Plug-in for Db2 supports NFS and SAN on ONTAP and Azure NetApp File storage layouts.

VMDK or virtual storage layout is not supported.

