---
permalink: protect-nsp/prerequisites_to_adding_hosts_and_installing_netapp_supported_plugins.html
sidebar: sidebar
keywords: credentials
summary: 'Before you add a host and install the plug-ins packages, you must complete all the requirements. The NetApp supported plug-ins can be used in both Windows, Linux, or AIX environments.'
---
= Prerequisites for adding hosts and installing Plug-ins package for Windows, Linux, or AIX
:icons: font
:imagesdir: ../media/

[.lead]
Before you add a host and install the plug-ins packages, you must complete all the requirements. The NetApp supported plug-ins are supported on Windows, Linux, and AIX environments.

NOTE: Storage and Oracle applications are supported on AIX. 

* You must have installed Java 11 on your Linux, Windows, or AIX host.
* When installing a plug-in on a Windows host, if you specify a credential that is not built-in, or if the user belongs to a local workgroup user, you must disable UAC on the host.
* The NetApp supported plug-ins like MongoDB, ORASCPM, Oracle Applications, SAP ASE, SAP MaxDB, and Storage plug-in must be available on the client host from where the add host operation is performed.

== General

If you are using iSCSI, the iSCSI service should be running.

== Windows hosts

* You must have a domain user with local administrator privileges with local login permissions on the remote host.
* If you manage cluster nodes in SnapCenter, you must have a user with administrative privileges to all the nodes in the cluster.
* You must manually choose SnapCenter Plug-in for Microsoft Windows.

== Linux and AIX hosts

NOTE: Storage and Oracle applications are supported on AIX. 

* You must have enabled the password-based SSH connection for the root or non-root user.
* You must have installed Java 11 on your Linux host.
+
If you are using Windows Server 2019 or Windows Server 2016 for the SnapCenter Server host, you must install Java 11. The Interoperability Matrix Tool (IMT) contains the latest information about requirements.
+
http://www.java.com/en/download/manual.jsp[Java Downloads for All Operating Systems]
+
https://imt.netapp.com/matrix/imt.jsp?components=117018;&solution=1259&isHWU&src=IMT[NetApp Interoperability Matrix Tool]

* You must configure sudo privileges for the non-root user to provide access to several paths. Add the following lines to the /etc/sudoers file by using the visudo Linux utility. 
+
NOTE: Ensure that you are using Sudo version 1.8.7 or later.
+
[subs=+quotes]
----
Cmnd_Alias HPPLCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/snapcenter_linux_host_plugin.bin, /opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl, /opt/NetApp/snapcenter/scc/bin/scc
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/Linux_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
Cmnd_Alias SCCCMDEXECUTOR =checksum_value== /opt/NetApp/snapcenter/scc/bin/sccCommandExecutor
_LINUX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPLCMD, PRECHECKCMD, CONFIGCHECKCMD, SCCCMDEXECUTOR, SCCMD
Defaults: _LINUX_USER_ !visiblepw
Defaults: _LINUX_USER_ !requiretty
----
+
_LINUX_USER_ is the name of the non-root user that you created.
+
You can obtain the _checksum_value_ from the *sc_unix_plugins_checksum.txt* file, which is located at:

** _C:\ProgramData\NetApp\SnapCenter\Package Repository\sc_unix_plugins_checksum.txt_ if SnapCenter Server is installed on Windows host.
** _/opt/NetApp/snapcenter/SnapManagerWeb/Repository/sc_unix_plugins_checksum.txt_ if SnapCenter Server in installed on Linux host.
+
IMPORTANT: The example should be used only as a reference for creating your own data.

== AIX Host requirements

You should ensure that the host meets the requirements before installing the SnapCenter Plug-ins Package for AIX.

NOTE: Storage and Oracle applications are supported on AIX. 

NOTE: SnapCenter Plug-in for UNIX which is part of the SnapCenter Plug-ins Package for AIX, does not support concurrent volume groups.

|===
| Item| Requirements

a|
Operating systems
a|
AIX 7.1 or later
a|
Minimum RAM for the SnapCenter plug-in on host
a|
4 GB
a|
Minimum install and log space for the SnapCenter plug-in on host
a|
2 GB

NOTE: You should allocate sufficient disk space and monitor the storage consumption by the logs folder. The log space required varies depending on the number of the entities to be protected and the frequency of data protection operations. If there is no sufficient disk space, the logs will not be created for the recently run operations.

a|
Required software packages
a|
Java 11 IBM Java

If you have upgraded JAVA to the latest version, you must ensure that the JAVA_HOME option located at /var/opt/snapcenter/spl/etc/spl.properties is set to the correct JAVA version and the correct path.

|===

For the latest information about supported versions, see the https://imt.netapp.com/matrix/imt.jsp?components=121073;&solution=1257&isHWU&src=IMT[NetApp Interoperability Matrix Tool^].

=== Configure sudo privileges for non-root users for AIX host

SnapCenter 4.4 and later allows a non-root user to install the SnapCenter Plug-ins Package for AIX and to start the plug-in process. The plug-in processes will be running as an effective non-root user. You should configure sudo privileges for the non-root user to provide access to several paths.

*What you will need*

* Sudo version 1.8.7 or later.
* Edit the _/etc/ssh/sshd_config_ file to configure the message authentication code algorithms: MACs hmac-sha2-256 and MACs hmac-sha2-512.
+
Restart the sshd service after updating the configuration file.
+
Example:
+
----
#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::
#Legacy changes
#KexAlgorithms diffie-hellman-group1-sha1
#Ciphers aes128-cbc
#The default requires explicit activation of protocol
Protocol 2
HostKey/etc/ssh/ssh_host_rsa_key
MACs hmac-sha2-256
----

*About this task*

You should configure sudo privileges for the non-root user to provide access to the following paths:

* /home/_AIX_USER_/.sc_netapp/snapcenter_aix_host_plugin.bsx
* /custom_location/NetApp/snapcenter/spl/installation/plugins/uninstall
* /custom_location/NetApp/snapcenter/spl/bin/spl

*Steps*

. Log in to the AIX host on which you want to install the SnapCenter Plug-ins Package for AIX.
. Add the following lines to the /etc/sudoers file by using the visudo Linux utility.
+
[subs=+quotes]
----
Cmnd_Alias HPPACMD = sha224:checksum_value== /home/_AIX_USER_/.sc_netapp/snapcenter_aix_host_plugin.bsx,
/opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_AIX_USER_/.sc_netapp/AIX_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
_AIX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPACMD, PRECHECKCMD, CONFIGCHECKCMD, SCCMD
Defaults: _AIX_USER_ !visiblepw
Defaults: _AIX_USER_ !requiretty
----
+
NOTE: If you are having a RAC setup, along with the other allowed commands, you should add the following to the /etc/sudoers file: '/<crs_home>/bin/olsnodes'

You can obtain the value of _crs_home_ from the _/etc/oracle/olr.loc_ file. 

_AIX_USER_ is the name of the non-root user that you created.

You can obtain the _checksum_value_ from the *sc_unix_plugins_checksum.txt* file, which is located at:

* _C:\ProgramData\NetApp\SnapCenter\Package Repository\sc_unix_plugins_checksum.txt_ if SnapCenter Server is installed on Windows host.
* _/opt/NetApp/snapcenter/SnapManagerWeb/Repository/sc_unix_plugins_checksum.txt_ if SnapCenter Server in installed on Linux host.

IMPORTANT: The example should be used only as a reference for creating your own data.
