---
permalink: protect-nsp/prerequisites_to_adding_hosts_and_installing_netapp_supported_plugins.html
sidebar: sidebar
keywords: credentials
summary: 'Before you add a host and install the plug-ins packages, you must complete all the requirements. The NetApp supported plug-ins can be used in both Windows and Linux environments.'
---
= Prerequisites for adding hosts and installing NetApp supported plug-ins
:icons: font
:imagesdir: ../media/

[.lead]
Before you add a host and install the plug-ins packages, you must complete all the requirements. The NetApp supported plug-ins can be used in both Windows and Linux environments.

* You must have created a custom plug-in. For details, see the developer information.
+
link:develop_a_plug_in_for_your_application.html[Develop a plug-in for your application]
* You must have installed Java 11 on your Linux or Windows host.
* When installing a plug-in on a Windows host, if you specify a credential that is not built-in, or if the user belongs to a local workgroup user, you must disable UAC on the host.
* The NetApp supported plug-ins must be available on the client host from where the add host operation is performed.

== General

If you are using iSCSI, the iSCSI service should be running.

== SHA512 hash

* For NetApp supported plug-ins, you should ensure that you have added the SHA512 hash of the NetApp supported plug-in file to the _custom_plugin_checksum_list_ file.
** For Linux host, the SHA512 hash is located at _/var/opt/snapcenter/scc/custom_plugin_checksum_list.txt_
** For Windows host, the SHA512 hash is located at
_C:\Program Files\NetApp\SnapCenter Plug-in Creator\etc\custom_plugin_checksum_list.txt_
+
For custom installation path, the SHA512 hash is located at _<custom path>\NetApp\SnapCenter\Snapcenter Plug-in Creator\etc\custom_plugin_checksum_list.txt_

+
The custom_plugin_checksum_list is part of the NetApp supported plug-in installation on the host by SnapCenter.

* For NetApp supported plug-ins created for your application, you should have performed the following steps:

. Generated the SHA512 hash of the plug-in zip file.
+
You can use online tools like https://emn178.github.io/online-tools/sha512_file_hash.html[SHA512 hash^].

. Added the generated SHA512 hash to the custom_plugin_checksum_list file in a new line.
+
The comments start with # symbol to identify the plug-in to which the hash belongs.
+
Following is an example of an entry of SHA512 hash in the checksum file:

  #ORASCPM
  03721f567a1e4a1cb5569066b9a58af619ee12b1f8713108f81b696cfbdb81c25232fa63d6e6777a2b2a1ec068bb0a93a59a8ade71587182f8bccbe81f7e0ba6

== Windows hosts

* You must have a domain user with local administrator privileges with local login permissions on the remote host.
* If you manage cluster nodes in SnapCenter, you must have a user with administrative privileges to all the nodes in the cluster.

== Linux hosts

* You must have enabled the password-based SSH connection for the root or non-root user.
* You must have installed Java 11 on your Linux host.
+
If you are using Windows Server 2019 or Windows Server 2016 for the SnapCenter Server host, you must install Java 11. The Interoperability Matrix Tool (IMT) contains the latest information about requirements.
+
http://www.java.com/en/download/manual.jsp[Java Downloads for All Operating Systems]
+
https://imt.netapp.com/matrix/imt.jsp?components=117018;&solution=1259&isHWU&src=IMT[NetApp Interoperability Matrix Tool]

* You must configure sudo privileges for the non-root user to provide access to several paths. Add the following lines to the /etc/sudoers file by using the visudo Linux utility. 
+
NOTE: Ensure that you are using Sudo version 1.8.7 or later.
+
[subs=+quotes]
----
Cmnd_Alias HPPLCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/snapcenter_linux_host_plugin.bin, /opt/NetApp/snapcenter/spl/installation/plugins/uninstall, /opt/NetApp/snapcenter/spl/bin/spl, /opt/NetApp/snapcenter/scc/bin/scc
Cmnd_Alias PRECHECKCMD = sha224:checksum_value== /home/_LINUX_USER_/.sc_netapp/Linux_Prechecks.sh
Cmnd_Alias CONFIGCHECKCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/plugins/scu/scucore/configurationcheck/Config_Check.sh
Cmnd_Alias SCCMD = sha224:checksum_value== /opt/NetApp/snapcenter/spl/bin/sc_command_executor
Cmnd_Alias SCCCMDEXECUTOR =checksum_value== /opt/NetApp/snapcenter/scc/bin/sccCommandExecutor
_LINUX_USER_ ALL=(ALL) NOPASSWD:SETENV: HPPLCMD, PRECHECKCMD, CONFIGCHECKCMD, SCCCMDEXECUTOR, SCCMD
Defaults: _LINUX_USER_ !visiblepw
Defaults: _LINUX_USER_ !requiretty
----
+
_LINUX_USER_ is the name of the non-root user that you created.
+
You can obtain the _checksum_value_ from the *sc_unix_plugins_checksum.txt* file, which is located at:

** _C:\ProgramData\NetApp\SnapCenter\Package Repository\sc_unix_plugins_checksum.txt_ if SnapCenter Server is installed on Windows host.
** _/opt/NetApp/snapcenter/SnapManagerWeb/Repository/sc_unix_plugins_checksum.txt_ if SnapCenter Server in installed on Linux host.
+
IMPORTANT: The example should be used only as a reference for creating your own data.
