---
permalink: protect-nsp/what_you_can_do_with_the_netapp_supported_plugins.html
sidebar: sidebar
keywords: NetApp supported plug-ins
summary: 'You can use the NetApp supported plug-ins for data protection operations.'
---
= What you can do with the NetApp supported plug-ins 
:icons: font
:imagesdir: ../media/

[.lead]
You can use the NetApp supported plug-ins like MongoDB, ORASCPM, Oracle Applications, SAP ASE, SAP MaxDB, and Storage plug-in for data protection operations.

* Add resources such as databases, instances, documents, or tablespaces.
* Create backups.
* Restore from backups.
* Clone backups.
* Schedule backup operations.
* Monitor backup, restore, and clone operations.
* View reports for backup, restore, and clone operations.

You can use the NetApp supported plug-ins for data protection operations.

* Take consistency group Snapshots of the storage volumes across ONTAP clusters.
* Backup custom applications using the built in pre and post scripting framework
+
You can backup ONTAP volume, LUN, or a Qtree.
* Update Snapshots taken on the primary to an ONTAP secondary, leveraging the existing replication relationship (SnapVault/SnapMirror/unified replication) using SnapCenter policy
+
ONTAP primary and secondary can be ONTAP FAS, AFF, All SAN Array (ASA), Select, or Cloud ONTAP.
* Recover complete ONTAP volume, LUN, or files.
+
You should provide the respective file path manually as the browse or indexing features are not built into the product.
+
Qtree or directory restore is not supported but you can clone and export only the Qtree if the backup scope is defined at a Qtree level.
