---
permalink: get-started/concept_resources_resource_groups_and_policies.html
sidebar: sidebar
keywords: resource, resource group, policy
summary: 'Before you use SnapCenter, it is helpful to understand basic concepts related to the backup, clone, and restore operations you want to perform.'
---
= Key concepts of data protection
:icons: font
:imagesdir: ../media/

[.lead]
Before you use SnapCenter, it is helpful to understand basic concepts related to the backup, clone, and restore operations you want to perform. 

== Resources

Resources are typically databases, Windows file systems, or file shares that you back up or clone with SnapCenter.

However, depending on your environment, resources might be database instances, Microsoft SQL Server availability groups, Oracle databases, Oracle RAC databases, Windows file systems, or a group of custom applications.

== Resource group

A resource group is a collection of resources on a host or cluster. The resource group can also contain resources from multiple hosts and multiple clusters.

When you perform an operation on a resource group, you perform that operation on all the resources defined in the resource group according to the schedule you specify for the resource group.

You can back up on demand a single resource or a resource group. You also can configure scheduled backups for single resources and resource groups.

NOTE: If you put one host of a shared resource group on maintenance mode, and if there are schedules associated with the same shared resource group, all the scheduled operations will be suspended for all of the other hosts of the shared resource group.

You should use a database plug-in to back up databases, a file system plug-in to back up file systems, and the SnapCenter Plug-in for VMware vSphere to backup VMs and datastores.

== Policies

Policies specify the backup frequency, copy retention, replication, scripts, and other characteristics of data protection operations.

When you create a resource group, you select one or more policies for that group. You can also select a policy when you perform a backup on demand.

Think of a resource group as defining _what_ you want to protect and when you want to protect it in terms of day and time. Think of a policy as defining _how_ you want to protect it. If you are backing up all databases or backing up all file systems of a host, for example, you might create a resource group that includes all the databases or all the file systems in the host. You could then attach two policies to the resource group: a daily policy and an hourly policy.

When you create the resource group and attach the policies, you might configure the resource group to perform a full backup daily and another schedule that performs log backups hourly.

You can use custom prescripts and postscripts as part of your data protection operations. These scripts enable automation either before your data protection job or after. For example, you might include a script that automatically notifies you of data protection job failures or warnings. Before you set up your prescripts and postscripts, you should understand some of the requirements for creating these scripts.

== Usage of prescripts and postscripts in SnapCenter

You can use custom prescripts and postscripts as part of your data protection operations. These scripts enable automation either before your data protection job or after. For example, you might include a script that automatically notifies you of data protection job failures or warnings. Before you set up your prescripts and postscripts, you should understand some of the requirements for creating these scripts.

=== Supported script types

The following types of scripts are supported for Windows:

* Batch files
* PowerShell scripts
* Perl scripts

The following types of scripts are supported for UNIX:

* Perl scripts
* Python scripts
* Shell scripts
+
NOTE: Along with default bash shell other shells like sh-shell, k-shell, and c-shell are also supported.

=== Script path

All prescripts and postscripts that are run as part of SnapCenter operations, on nonvirtualized and on virtualized storage systems, are executed on the plug-in host.

* The Windows scripts should be located on the plug-in host. 

NOTE: The prescripts or postscripts path should not include drives or shares. The path should be relative to the SCRIPTS_PATH.

* The UNIX scripts should be located on the plug-in host.

NOTE: The script path is validated at the time of execution.

=== Where to specify scripts

Scripts are specified in backup policies. When a backup job is started, the policy automatically associates the script with the resources being backed up. When you create a backup policy, you can specify the prescript and postscript arguments.

NOTE: You cannot specify multiple scripts.

=== Script timeouts

The timeout is set to 60 seconds, by default. You can modify the timeout value.

=== Script output

The default directory for the Windows prescripts and postscripts output files is Windows\System32.

There is no default location for the UNIX prescripts and postscripts. You can redirect the output file to any preferred location.

