---
permalink: uninstall/reference_prerequisites_for_removing_a_host.html
sidebar: sidebar
keywords: uninstall, prereqiuisites
summary: 'You can remove a host if you no longer want to use SnapCenter to manage its data protection jobs. For example, you might want to remove a host if it no longer has data that needs to be protected. Before you remove a host from SnapCenter Server, you must perform the prerequisite tasks.'
---
= Prerequisites for removing a host
:icons: font
:imagesdir: ../media/

[.lead]
You can remove a host if you no longer want to use SnapCenter to manage its data protection jobs. For example, you might want to remove a host if it no longer has data that needs to be protected. Before you remove a host from SnapCenter Server, you should complete the prerequisites.

* You should log in as an administrator.
* If you are using SnapCenter Custom Plug-ins, you should delete all the clones that are associated with the host from SnapCenter.
* You should ensure that discovery jobs are not running on the host.
* You should be assigned a role with the required permissions to remove all of the objects associated with the host. Otherwise, the remove operation fails.
* You should confirm the fingerprint if the SSH key was modified after adding the host to SnapCenter.
* You should confirm the fingerprint if the SnapCenter host is upgraded to a later version of SnapCenter but the plug-in host is still running an earlier version of the plug-in.

== Prerequisites to remove a host using role-based access control

* You should have logged in using an RBAC role that has read, delete host, installation, uninstallation of plug-in, and delete objects permissions.
+
Objects can be clone, backup, resource group, storage system, and so on.

* You should have added the RBAC user to the RBAC role.
* You should assign the RBAC user to the host, plug-in, credential, resource groups, and storage system (for clones) that you want to delete.
* You should have logged in SnapCenter as an RBAC user.

== Prerequisites to remove a host with clones created from clone lifecycle operation

* You should have created clone jobs using clone lifecycle management for SQL databases.
* You should have created an RBAC role with clone read and delete, resource read and delete, resource group read and delete, storage read and delete, provision read and delete, mount, unmount, plug-in installation and uninstallation, host read and delete permissions.
* You should have assigned the RBAC user to the RBAC role.
* You should have assigned the RBAC user to the host, SnapCenter Plug-in for Microsoft SQL Server, credential, clone lifecycle resource group, and storage system.
* You should have logged in SnapCenter as an RBAC user.
