---
permalink: uninstall/task_uninstall_plug_ins_locally_on_a_host.html
sidebar: sidebar
keywords: uninstall, uninstall plug-in locally, uninstall plug-in from a host
summary: 'You can uninstall SnapCenter plug-ins locally on a host if you cannot reach the host from the SnapCenter Server.'
---
= Uninstall plug-ins locally on a host
:icons: font
:imagesdir: ../media/

[.lead]
You can uninstall SnapCenter plug-ins locally on a host if you cannot reach the host from the SnapCenter Server.

*About this task*

The best practice for uninstalling individual plug-ins or plug-in packages is to either use the SnapCenter GUI or use the Uninstall-SmHostPackage cmdlet on the SnapCenter Server host command-line interface. These procedures help the SnapCenter Server to stay up to date with any changes.

However, you might have a rare need to uninstall plug-ins locally. For example, you might have run an uninstall job from the SnapCenter Server but the job failed, or you uninstalled your SnapCenter Server and orphan plug-ins remain on a host.

IMPORTANT: Uninstalling a plug-in package locally on a host does not delete data associated with the host; for example scheduled jobs and backup metadata.

IMPORTANT: Do not attempt to uninstall the SnapCenter Plug-ins Package for Windows locally from the Control Panel. You must use the SnapCenter GUI to ensure that SnapCenter Plug-in for Microsoft Windows is properly uninstalled.

*Steps*

. On the host system, navigate to the Control Panel and click *Uninstall a program*.
. In the list of programs, select the SnapCenter plug-in or plug-in package you want to uninstall and click *Uninstall*.
+
Windows uninstalls all plug-ins in the selected package.
