---
permalink: uninstall/task_remove_a_host.html
sidebar: sidebar
keywords: uninstall, remove, remove host
summary: 'When the SnapCenter Server removes a host, it first removes the backup, clones, clone jobs, resource groups, and resources listed for that host on the SnapCenter Resources page, and then it uninstalls the plug-in packages on the host.'
---
= Remove a host
:icons: font
:imagesdir: ../media/

[.lead]
When the SnapCenter Server removes a host, it first removes the backup, clones, clone jobs, resource groups, and resources listed for that host on the SnapCenter Resources page, and then it uninstalls the plug-in packages on the host.

.About this task

* If you delete a host, the backups, clones, and resource groups associated with the host are also deleted.
* When you remove the resource groups, all the associated schedules are also removed.
* If the host has a resource group that is shared with another host and you delete the host, then the resource group is also deleted.
* You should use the _Remove-SmHost_ cmdlet to remove the decommissioned or unreachable plug-in hosts.
+
The information regarding the parameters that can be used with the cmdlet and their descriptions can be obtained by running _Get-Help command_name_. Alternatively, you can also refer to the https://library.netapp.com/ecm/ecm_download_file/ECMLP2886895[SnapCenter Software Cmdlet Reference Guide^]
* The time required to remove a host depends on the number of backups and the retention settings. This is because the Snapshot copies are deleted from each of the controllers and the metadata is cleaned.

.Steps

. In the left navigation pane, click *Hosts*.
. In the *Hosts* page, click *Managed Hosts*.
. Select the host you want to remove, and then click *Remove*.
. For Oracle RAC clusters, to remove SnapCenter software from all the hosts in the cluster, select *Include all the hosts of cluster*.
+
You can also remove one node of a cluster and in that way remove all the nodes one by one.

. Click *OK*.
+
NOTE: When you uninstall and reinstall host plug-ins on a cluster, the cluster resources are not automatically discovered. Select the cluster hostname, and then click *Refresh Resources* to automatically discover the cluster resources.
