---
permalink: protect-mysql/create-backup-policies-for-mysql.html
sidebar: sidebar
keywords: SnapCenter Plug-in for MySQL
summary: 'Before you use SnapCenter to back up MySQL database resources, you must create a backup policy for the resource or resource group that you want to back up. A backup policy is a set of rules that governs how you manage, schedule, and retain backups.'
---
= Create backup policies for MySQL
:icons: font
:imagesdir: ../media/

[.lead]
Before you use SnapCenter to back up MySQL resources, you must create a backup policy for the resource or resource group that you want to back up. A backup policy is a set of rules that governs how you manage, schedule, and retain backups.

.Before you begin

* You must have defined your backup strategy.
+
For details, see the information about defining a data protection strategy for MySQL databases.
* You must have prepared for data protection by completing tasks such as installing SnapCenter, adding hosts, setting up storage system connections, and adding resources.
* The SnapCenter administrator must have assigned the SVMs for both the source and destination volumes to you if you are replicating snapshots to a mirror or vault.
+
Additionally, you can specify replication, script, and application settings in the policy. These options saves time when you want to reuse the policy for another resource group.

.About this task

* SnapLock 

** If 'Retain the backup copies for a specific number of days' option is selected, then the SnapLock retention period must be lesser than or equal to the mentioned retention days.

** Specifying a snapshot locking period prevents deletion of the snapshots until the retention period expires. This could lead to retaining a larger number of snapshots than the count specified in the policy.

** For ONTAP 9.12.1 and below version, the clones created from the SnapLock Vault snapshots as part of restore will inherit the SnapLock Vault expiry time. Storage admin should manually cleanup the clones post the SnapLock expiry time.

.Steps

. In the left navigation pane, click *Settings*.
. In the Settings page, click *Policies*.
. Click *New*.
. In the Name page, enter the policy name and details.
. In the Policy type page, perform the following:
.. Select storage type.
.. In the Custom backup settings section, provide any specific backup settings that have to be passed to the plug-in in key-value format.
+
You can provide multiple key-values to be passed to the plug-in.
. In the Snapshot and Replication page, perform the following steps:
.. Specify the schedule type by selecting *On demand*, *Hourly*, *Daily*, *Weekly*, or *Monthly*.
+
NOTE: You can specify the schedule (start date, end date, and frequency) for the backup operation while creating a resource group. This enables you to create resource groups that share the same policy and backup frequency, but enables you to assign different backup schedules to each policy.
+
NOTE: If you have scheduled for 2:00 a.m., the schedule will not be triggered during daylight saving time (DST).

.. In the Snapshot settings section, specify the retention settings for the backup type and the schedule type selected in the *Backup Type* page:
+
|===
| If you want to...| Then...

a|
Keep a certain number of Snapshots 
a|
Select *Copies to keep*, and then specify the number of Snapshots that you want to keep.

If the number of Snapshots exceeds the specified number, the Snapshots are deleted with the oldest copies deleted first.

NOTE: You must set the retention count to 2 or higher if you plan to enable SnapVault replication. If you set the retention count to 1, the retention operation might fail because the first Snapshot is the reference Snapshot for the SnapVault relationship until a newer Snapshot is replicated to the target.

NOTE: The maximum retention value is 1018. Backups will fail if retention is set to a value higher than what the underlying ONTAP version supports.

a|
Keep the Snapshots for a certain number of days
a|
Select *Retain copies for*, and then specify the number of days for which you want to keep the Snapshots before deleting them.
a|
Snapshot copy locking period
a|
Select *Snapshot copy locking period*, and specify days, months, or years.

SnapLock retention period should be less than 100 years.
|===

.. Select a Policy label.
+
NOTE: You can assign SnapMirror labels to primary snapshots for remote replication, allowing the primary snapshots to offload the snapshot replication operation from SnapCenter to ONTAP secondary systems. This can be done without enabling SnapMirror or SnapVault option in the policy page.

. In the Select secondary replication options section, select one or both of the following secondary replication options:
+
|===
| For this field...| Do this...

a|
*Update SnapMirror after creating a local Snapshot copy*
a|
Select this field to create mirror copies of the backup sets on another volume (SnapMirror replication).

If the protection relationship in ONTAP is of type Mirror and Vault and if you select only this option, Snapshot created on the primary will not be transferred to the destination, but will be listed in the destination. If this Snapshot is selected from the destination to perform a restore operation, then the following error message is displayed: Secondary Location is not available for the selected vaulted/mirrored backup.

During secondary replication, the SnapLock expiry time loads the primary SnapLock expiry time.

Clicking the *Refresh* button in the Topology page refreshes the secondary and primary SnapLock expiry time that are retrieved from ONTAP.

See link:view-mysql-database-backups-and-clones-in-the-topology-page.html[View MySQL resource related backups and clones in the Topology page].
a|
*Update SnapVault after creating a local Snapshot copy*
a|
Select this option to perform disk-to-disk backup replication (SnapVault backups).

During secondary replication, the SnapLock expiry time loads the primary SnapLock expiry time. Clicking the *Refresh* button in the Topology page refreshes the secondary and primary SnapLock expiry time that are retrieved from ONTAP.

When SnapLock is configured only on the secondary from ONTAP known as SnapLock Vault, clicking the *Refresh* button in the Topology page refreshes the locking period on the secondary that is retrieved from ONTAP.

For more information on SnapLock Vault see Commit Snapshots to WORM on a vault
destination

See link:view-mysql-database-backups-and-clones-in-the-topology-page.html[View MySQL resource related backups and clones in the Topology page].
a|
*Error retry count*
a|
Enter the maximum number of replication attempts that can be allowed before the operation stops.
|===
NOTE: You should configure SnapMirror retention policy in ONTAP for the secondary storage to avoid reaching the maximum limit of Snapshots on the secondary storage.

. Review the summary, and then click *Finish*.