---
permalink: protect-mysql/snapcenter-plug-in-for-mysql-overview.html
sidebar: sidebar
keywords: SnapCenter Plug-in for MySQL
summary: 'The SnapCenter Plug-in for MySQL is a host-side component of the NetApp SnapCenter software that enables application-aware data protection management of MySQL databases. The Plug-in for MySQL Database automates the backup, restore, and cloning of MySQL databases in your SnapCenter environment.'
---
= SnapCenter Plug-in for MySQL overview
:icons: font
:imagesdir: ../media/

[.lead]
The SnapCenter Plug-in for MySQL Database is a host-side component of the NetApp SnapCenter software that enables application-aware data protection management of MySQL databases. The Plug-in for MySQL Database automates the backup, restore, and cloning of MySQL databases in your SnapCenter environment.

SnapCenter supports single instance and multi instance MySQL setups. You can use the Plug-in for MySQL Database in both Linux and Windows environments. In Windows environments, MySQL will be supported as manual resource.

When the Plug-in for MySQL Database is installed, you can use SnapCenter with NetApp SnapMirror technology to create mirror copies of backup sets on another volume. You can also use the plug-in with NetApp SnapVault technology to perform disk-to-disk backup replication for standards compliance.

SnapCenter Plug-in for MySQL supports NFS and SAN on ONTAP and Azure NetApp File storage layouts.

VMDK or virtual storage layout is supported.

