---
permalink: protect-mysql/types-of-restore-performed-for-auto-discovered-mysql.html
sidebar: sidebar
keywords: SnapCenter Plug-in for mysql
summary: 'SnapCenter supports volume-based SnapRestore \(VBSR\), Single File SnapRestore, and connect-and-copy restore types for automatically discovered mysql databases.'
---
= Types of restore operations for auto discovered mysql
:icons: font
:imagesdir: ../media/

[.lead]
SnapCenter Plug-in for mysql supports Single File SnapRestore, and connect-and-copy restore types for automatically discovered mysql databases.

== Single File SnapRestore is performed in NFS environments for the following scenarios:

* If only the *Complete Resource* option is selected
* When the backup selected is from a SnapMirror or SnapVault secondary location, and the *Complete Resource* option is selected

== Single File SnapRestore is performed in SAN environments for the following scenarios:

* If only the *Complete Resource* option is selected
* When the backup is selected from a SnapMirror or SnapVault secondary location, and the *Complete Resource* option is selected


